Pokemon.create!(
  id: 1,
  name: 'Bulbasaur',
  classification: 'Seed',
  height: 0.7,
  weight: 6.9,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 87.5,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 45,
  attack: 49,
  defense: 49,
  sp_attack: 65,
  sp_defense: 65,
  speed: 45,
  type_1: Type.find_by(name: 'Grass'),
  type_2: Type.find_by(name: 'Poison'),
  ability_1: Ability.find_by(name: 'overgrow'),
  hidden_ability: Ability.find_by(name: 'chlorophyll'),
)

Pokemon.create!(
  id: 2,
  name: 'Ivysaur',
  classification: 'Seed',
  height: 1.0,
  weight: 13.0,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 87.5,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 60,
  attack: 62,
  defense: 63,
  sp_attack: 80,
  sp_defense: 80,
  speed: 60,
  type_1: Type.find_by(name: 'Grass'),
  type_2: Type.find_by(name: 'Poison'),
  ability_1: Ability.find_by(name: 'overgrow'),
  hidden_ability: Ability.find_by(name: 'chlorophyll'),
)

Pokemon.create!(
  id: 3,
  name: 'Venusaur',
  classification: 'Seed',
  height: 2.0,
  weight: 100.0,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 87.5,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 80,
  attack: 82,
  defense: 83,
  sp_attack: 100,
  sp_defense: 100,
  speed: 80,
  type_1: Type.find_by(name: 'Grass'),
  type_2: Type.find_by(name: 'Poison'),
  ability_1: Ability.find_by(name: 'overgrow'),
  hidden_ability: Ability.find_by(name: 'chlorophyll'),
)

Pokemon.create!(
  id: 4,
  name: 'Charmander',
  classification: 'Lizard',
  height: 0.6,
  weight: 8.5,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 87.5,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 39,
  attack: 52,
  defense: 43,
  sp_attack: 60,
  sp_defense: 50,
  speed: 65,
  type_1: Type.find_by(name: 'Fire'),
  ability_1: Ability.find_by(name: 'blaze'),
  hidden_ability: Ability.find_by(name: 'solar_power'),
)

Pokemon.create!(
  id: 5,
  name: 'Charmeleon',
  classification: 'Flame',
  height: 1.1,
  weight: 19.0,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 87.5,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 58,
  attack: 64,
  defense: 58,
  sp_attack: 80,
  sp_defense: 65,
  speed: 80,
  type_1: Type.find_by(name: 'Fire'),
  ability_1: Ability.find_by(name: 'blaze'),
  hidden_ability: Ability.find_by(name: 'solar_power'),
)

Pokemon.create!(
  id: 6,
  name: 'Charizard',
  classification: 'Flame',
  height: 1.7,
  weight: 90.5,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 87.5,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 78,
  attack: 84,
  defense: 78,
  sp_attack: 109,
  sp_defense: 85,
  speed: 100,
  type_1: Type.find_by(name: 'Fire'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'blaze'),
  hidden_ability: Ability.find_by(name: 'solar_power'),
)

Pokemon.create!(
  id: 7,
  name: 'Squirtle',
  classification: 'Tiny Turtle',
  height: 0.5,
  weight: 9.0,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 87.5,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 44,
  attack: 48,
  defense: 65,
  sp_attack: 50,
  sp_defense: 64,
  speed: 43,
  type_1: Type.find_by(name: 'Water'),
  ability_1: Ability.find_by(name: 'torrent'),
  hidden_ability: Ability.find_by(name: 'rain_dish'),
)

Pokemon.create!(
  id: 8,
  name: 'Wartortle',
  classification: 'Turtle',
  height: 1.0,
  weight: 22.5,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 87.5,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 59,
  attack: 63,
  defense: 80,
  sp_attack: 65,
  sp_defense: 80,
  speed: 58,
  type_1: Type.find_by(name: 'Water'),
  ability_1: Ability.find_by(name: 'torrent'),
  hidden_ability: Ability.find_by(name: 'rain_dish'),
)

Pokemon.create!(
  id: 9,
  name: 'Blastoise',
  classification: 'Shellfish',
  height: 1.6,
  weight: 85.5,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 87.5,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 79,
  attack: 83,
  defense: 100,
  sp_attack: 85,
  sp_defense: 105,
  speed: 78,
  type_1: Type.find_by(name: 'Water'),
  ability_1: Ability.find_by(name: 'torrent'),
  hidden_ability: Ability.find_by(name: 'rain_dish'),
)

Pokemon.create!(
  id: 10,
  name: 'Caterpie',
  classification: 'Worm',
  height: 0.3,
  weight: 2.9,
  capture_rate: 255,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 45,
  attack: 30,
  defense: 35,
  sp_attack: 20,
  sp_defense: 20,
  speed: 45,
  type_1: Type.find_by(name: 'Bug'),
  ability_1: Ability.find_by(name: 'shield_dust'),
  hidden_ability: Ability.find_by(name: 'run_away'),
)

Pokemon.create!(
  id: 11,
  name: 'Metapod',
  classification: 'Cocoon',
  height: 0.7,
  weight: 9.9,
  capture_rate: 120,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 50,
  attack: 20,
  defense: 55,
  sp_attack: 25,
  sp_defense: 25,
  speed: 30,
  type_1: Type.find_by(name: 'Bug'),
  ability_1: Ability.find_by(name: 'shed_skin'),
)

Pokemon.create!(
  id: 12,
  name: 'Butterfree',
  classification: 'Butterfly',
  height: 1.1,
  weight: 32.0,
  capture_rate: 45,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 60,
  attack: 45,
  defense: 50,
  sp_attack: 90,
  sp_defense: 80,
  speed: 70,
  type_1: Type.find_by(name: 'Bug'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'compoundeyes'),
  hidden_ability: Ability.find_by(name: 'tinted_lens'),
)

Pokemon.create!(
  id: 13,
  name: 'Weedle',
  classification: 'Hairy',
  height: 0.3,
  weight: 3.2,
  capture_rate: 255,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 40,
  attack: 35,
  defense: 30,
  sp_attack: 20,
  sp_defense: 20,
  speed: 50,
  type_1: Type.find_by(name: 'Bug'),
  type_2: Type.find_by(name: 'Poison'),
  ability_1: Ability.find_by(name: 'shield_dust'),
  hidden_ability: Ability.find_by(name: 'run_away'),
)

Pokemon.create!(
  id: 14,
  name: 'Kakuna',
  classification: 'Cocoon',
  height: 0.6,
  weight: 10.0,
  capture_rate: 120,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 45,
  attack: 25,
  defense: 50,
  sp_attack: 25,
  sp_defense: 25,
  speed: 35,
  type_1: Type.find_by(name: 'Bug'),
  type_2: Type.find_by(name: 'Poison'),
  ability_1: Ability.find_by(name: 'shed_skin'),
)

Pokemon.create!(
  id: 15,
  name: 'Beedrill',
  classification: 'Poison Bee',
  height: 1.0,
  weight: 29.5,
  capture_rate: 45,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 65,
  attack: 90,
  defense: 40,
  sp_attack: 45,
  sp_defense: 80,
  speed: 75,
  type_1: Type.find_by(name: 'Bug'),
  type_2: Type.find_by(name: 'Poison'),
  ability_1: Ability.find_by(name: 'swarm'),
  hidden_ability: Ability.find_by(name: 'sniper'),
)

Pokemon.create!(
  id: 16,
  name: 'Pidgey',
  classification: 'Tiny Bird',
  height: 0.3,
  weight: 1.8,
  capture_rate: 255,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 40,
  attack: 45,
  defense: 40,
  sp_attack: 35,
  sp_defense: 35,
  speed: 56,
  type_1: Type.find_by(name: 'Normal'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'keen_eye'),
  ability_2: Ability.find_by(name: 'tangled_feet'),
  hidden_ability: Ability.find_by(name: 'big_pecks'),
)

Pokemon.create!(
  id: 17,
  name: 'Pidgeotto',
  classification: 'Bird',
  height: 1.1,
  weight: 30.0,
  capture_rate: 120,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 63,
  attack: 60,
  defense: 55,
  sp_attack: 50,
  sp_defense: 50,
  speed: 71,
  type_1: Type.find_by(name: 'Normal'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'keen_eye'),
  ability_2: Ability.find_by(name: 'tangled_feet'),
  hidden_ability: Ability.find_by(name: 'big_pecks'),
)

Pokemon.create!(
  id: 18,
  name: 'Pidgeot',
  classification: 'Bird',
  height: 1.5,
  weight: 39.5,
  capture_rate: 45,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 83,
  attack: 80,
  defense: 75,
  sp_attack: 70,
  sp_defense: 70,
  speed: 101,
  type_1: Type.find_by(name: 'Normal'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'keen_eye'),
  ability_2: Ability.find_by(name: 'tangled_feet'),
  hidden_ability: Ability.find_by(name: 'big_pecks'),
)

Pokemon.create!(
  id: 19,
  name: 'Rattata',
  classification: 'Mouse',
  height: 0.3,
  weight: 3.5,
  capture_rate: 255,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 30,
  attack: 56,
  defense: 35,
  sp_attack: 25,
  sp_defense: 35,
  speed: 72,
  type_1: Type.find_by(name: 'Normal'),
  ability_1: Ability.find_by(name: 'run_away'),
  ability_2: Ability.find_by(name: 'guts'),
  hidden_ability: Ability.find_by(name: 'hustle'),
)

Pokemon.create!(
  id: 20,
  name: 'Raticate',
  classification: 'Mouse',
  height: 0.7,
  weight: 18.5,
  capture_rate: 127,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 55,
  attack: 81,
  defense: 60,
  sp_attack: 50,
  sp_defense: 70,
  speed: 97,
  type_1: Type.find_by(name: 'Normal'),
  ability_1: Ability.find_by(name: 'run_away'),
  ability_2: Ability.find_by(name: 'guts'),
  hidden_ability: Ability.find_by(name: 'hustle'),
)
