Pokemon.create!(
  id: 21,
  name: 'Spearow',
  classification: 'Tiny Bird',
  height: 0.3,
  weight: 2.0,
  capture_rate: 255,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 40,
  attack: 60,
  defense: 30,
  sp_attack: 31,
  sp_defense: 31,
  speed: 70,
  type_1: Type.find_by(name: 'Normal'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'keen_eye'),
  hidden_ability: Ability.find_by(name: 'sniper')
)

Pokemon.create!(
  id: 22,
  name: 'Fearow',
  classification: 'Beak',
  height: 1.2,
  weight: 38.0,
  capture_rate: 90,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 65,
  attack: 90,
  defense: 65,
  sp_attack: 61,
  sp_defense: 61,
  speed: 100,
  type_1: Type.find_by(name: 'Normal'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'keen_eye'),
  hidden_ability: Ability.find_by(name: 'sniper')
)

Pokemon.create!(
  id: 23,
  name: 'Ekans',
  classification: 'Snake',
  height: 2.0,
  weight: 6.9,
  capture_rate: 255,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 35,
  attack: 60,
  defense: 44,
  sp_attack: 40,
  sp_defense: 54,
  speed: 55,
  type_1: Type.find_by(name: 'Poison'),
  ability_1: Ability.find_by(name: 'intimidate'),
  ability_2: Ability.find_by(name: 'shed_skin'),
  hidden_ability: Ability.find_by(name: 'unnerve')
)

Pokemon.create!(
  id: 24,
  name: 'Arbok',
  classification: 'Cobra',
  height: 3.5,
  weight: 65.0,
  capture_rate: 90,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 60,
  attack: 95,
  defense: 69,
  sp_attack: 65,
  sp_defense: 79,
  speed: 80,
  type_1: Type.find_by(name: 'Poison'),
  ability_1: Ability.find_by(name: 'intimidate'),
  ability_2: Ability.find_by(name: 'shed_skin'),
  hidden_ability: Ability.find_by(name: 'unnerve')
)

Pokemon.create!(
  id: 25,
  name: 'Pikachu',
  classification: 'Mouse',
  height: 0.4,
  weight: 6.0,
  capture_rate: 190,
  base_egg_steps: 2560,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 35,
  attack: 55,
  defense: 40,
  sp_attack: 50,
  sp_defense: 50,
  speed: 90,
  type_1: Type.find_by(name: 'Electric'),
  ability_1: Ability.find_by(name: 'static'),
  hidden_ability: Ability.find_by(name: 'lightningrod')
)

Pokemon.create!(
  id: 26,
  name: 'Raichu',
  classification: 'Mouse',
  height: 0.7,
  weight: 30.0,
  capture_rate: 75,
  base_egg_steps: 2560,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 60,
  attack: 90,
  defense: 55,
  sp_attack: 90,
  sp_defense: 80,
  speed: 110,
  type_1: Type.find_by(name: 'Electric'),
  ability_1: Ability.find_by(name: 'static'),
  ability_2: Ability.find_by(name: 'lightningrod'),
  hidden_ability: Ability.find_by(name: 'surge_surfer')
)

Pokemon.create!(
  id: 27,
  name: 'Sandshrew',
  classification: 'Mouse',
  height: 0.7,
  weight: 12.0,
  capture_rate: 255,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 50,
  attack: 75,
  defense: 85,
  sp_attack: 20,
  sp_defense: 30,
  speed: 40,
  type_1: Type.find_by(name: 'Ground'),
  ability_1: Ability.find_by(name: 'sand_veil'),
  ability_2: Ability.find_by(name: 'sand_rush'),
  hidden_ability: Ability.find_by(name: 'snow_cloak')
)

Pokemon.create!(
  id: 28,
  name: 'Sandslash',
  classification: 'Mouse',
  height: 1.2,
  weight: 29.5,
  capture_rate: 90,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 75,
  attack: 100,
  defense: 110,
  sp_attack: 45,
  sp_defense: 55,
  speed: 65,
  type_1: Type.find_by(name: 'Ground'),
  ability_1: Ability.find_by(name: 'sand_veil'),
  ability_2: Ability.find_by(name: 'sand_rush'),
  hidden_ability: Ability.find_by(name: 'snow_cloak')
)

Pokemon.create!(
  id: 29,
  name: 'Nidoran♀',
  classification: 'Poison Pin',
  height: 0.4,
  weight: 7.0,
  capture_rate: 235,
  base_egg_steps: 5120,
  male_gender_ratio: 0,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 55,
  attack: 47,
  defense: 52,
  sp_attack: 40,
  sp_defense: 40,
  speed: 41,
  type_1: Type.find_by(name: 'Poison'),
  ability_1: Ability.find_by(name: 'poison_point'),
  ability_2: Ability.find_by(name: 'rivalry'),
  hidden_ability: Ability.find_by(name: 'hustle')
)

Pokemon.create!(
  id: 30,
  name: 'Nidorina',
  classification: 'Poison Pin',
  height: 0.8,
  weight: 20.0,
  capture_rate: 120,
  base_egg_steps: 5120,
  male_gender_ratio: 0,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 70,
  attack: 62,
  defense: 67,
  sp_attack: 55,
  sp_defense: 55,
  speed: 56,
  type_1: Type.find_by(name: 'Poison'),
  ability_1: Ability.find_by(name: 'poison_point'),
  ability_2: Ability.find_by(name: 'rivalry'),
  hidden_ability: Ability.find_by(name: 'hustle')
)

Pokemon.create!(
  id: 31,
  name: 'Nidoqueen',
  classification: 'Drill',
  height: 1.3,
  weight: 60.0,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 0,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 90,
  attack: 92,
  defense: 87,
  sp_attack: 75,
  sp_defense: 85,
  speed: 76,
  type_1: Type.find_by(name: 'Poison'),
  type_2: Type.find_by(name: 'Ground'),
  ability_1: Ability.find_by(name: 'poison_point'),
  ability_2: Ability.find_by(name: 'rivalry'),
  hidden_ability: Ability.find_by(name: 'sheer_force')
)

Pokemon.create!(
  id: 32,
  name: 'Nidoran♂',
  classification: 'Poison Pin',
  height: 0.5,
  weight: 9.0,
  capture_rate: 235,
  base_egg_steps: 5120,
  male_gender_ratio: 100,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 46,
  attack: 57,
  defense: 40,
  sp_attack: 40,
  sp_defense: 40,
  speed: 50,
  type_1: Type.find_by(name: 'Poison'),
  ability_1: Ability.find_by(name: 'poison_point'),
  ability_2: Ability.find_by(name: 'rivalry'),
  hidden_ability: Ability.find_by(name: 'hustle')
)

Pokemon.create!(
  id: 33,
  name: 'Nidorino',
  classification: 'Poison Pin',
  height: 0.9,
  weight: 19.5,
  capture_rate: 120,
  base_egg_steps: 5120,
  male_gender_ratio: 100,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 61,
  attack: 72,
  defense: 57,
  sp_attack: 55,
  sp_defense: 55,
  speed: 65,
  type_1: Type.find_by(name: 'Poison'),
  ability_1: Ability.find_by(name: 'poison_point'),
  ability_2: Ability.find_by(name: 'rivalry'),
  hidden_ability: Ability.find_by(name: 'hustle')
)

Pokemon.create!(
  id: 34,
  name: 'Nidoking',
  classification: 'Drill',
  height: 1.4,
  weight: 62.0,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 100,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 81,
  attack: 102,
  defense: 77,
  sp_attack: 85,
  sp_defense: 75,
  speed: 85,
  type_1: Type.find_by(name: 'Poison'),
  type_2: Type.find_by(name: 'Ground'),
  ability_1: Ability.find_by(name: 'poison_point'),
  ability_2: Ability.find_by(name: 'rivalry'),
  hidden_ability: Ability.find_by(name: 'sheer_force')
)

Pokemon.create!(
  id: 35,
  name: 'Clefairy',
  classification: 'Fairy',
  height: 0.6,
  weight: 7.5,
  capture_rate: 150,
  base_egg_steps: 2560,
  male_gender_ratio: 25,
  experience_growth: 800_000,
  base_happiness: 140,
  hp: 70,
  attack: 45,
  defense: 48,
  sp_attack: 60,
  sp_defense: 65,
  speed: 35,
  type_1: Type.find_by(name: 'Fairy'),
  ability_1: Ability.find_by(name: 'cute_charm'),
  ability_2: Ability.find_by(name: 'magic_guard'),
  hidden_ability: Ability.find_by(name: 'friend_guard')
)

Pokemon.create!(
  id: 36,
  name: 'Clefable',
  classification: 'Fairy',
  height: 1.3,
  weight: 40.0,
  capture_rate: 25,
  base_egg_steps: 2560,
  male_gender_ratio: 25,
  experience_growth: 800_000,
  base_happiness: 140,
  hp: 95,
  attack: 70,
  defense: 73,
  sp_attack: 95,
  sp_defense: 90,
  speed: 60,
  type_1: Type.find_by(name: 'Fairy'),
  ability_1: Ability.find_by(name: 'cute_charm'),
  ability_2: Ability.find_by(name: 'magic_guard'),
  hidden_ability: Ability.find_by(name: 'unaware')
)

Pokemon.create!(
  id: 37,
  name: 'Vulpix',
  classification: 'Fox',
  height: 0.6,
  weight: 9.9,
  capture_rate: 190,
  base_egg_steps: 5120,
  male_gender_ratio: 25,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 38,
  attack: 41,
  defense: 40,
  sp_attack: 50,
  sp_defense: 65,
  speed: 65,
  type_1: Type.find_by(name: 'Fire'),
  type_2: Type.find_by(name: 'Ice'),
  ability_1: Ability.find_by(name: 'flash_fire'),
  ability_2: Ability.find_by(name: 'drought'),
  hidden_ability: Ability.find_by(name: 'snow_cloak')
)

Pokemon.create!(
  id: 38,
  name: 'Ninetales',
  classification: 'Fox',
  height: 1.1,
  weight: 19.9,
  capture_rate: 75,
  base_egg_steps: 5120,
  male_gender_ratio: 25,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 73,
  attack: 76,
  defense: 75,
  sp_attack: 81,
  sp_defense: 100,
  speed: 100,
  type_1: Type.find_by(name: 'Fire'),
  ability_1: Ability.find_by(name: 'flash_fire'),
  ability_2: Ability.find_by(name: 'drought'),
  hidden_ability: Ability.find_by(name: 'snow_cloak')
)

Pokemon.create!(
  id: 39,
  name: 'Jigglypuff',
  classification: 'Balloon',
  height: 0.5,
  weight: 5.5,
  capture_rate: 170,
  base_egg_steps: 2560,
  male_gender_ratio: 25,
  experience_growth: 800_000,
  base_happiness: 70,
  hp: 115,
  attack: 45,
  defense: 20,
  sp_attack: 45,
  sp_defense: 25,
  speed: 20,
  type_1: Type.find_by(name: 'Normal'),
  type_2: Type.find_by(name: 'Fairy'),
  ability_1: Ability.find_by(name: 'cute_charm'),
  ability_2: Ability.find_by(name: 'competitive'),
  hidden_ability: Ability.find_by(name: 'friend_guard')
)

Pokemon.create!(
  id: 40,
  name: 'Wigglytuff',
  classification: 'Balloon',
  height: 1.0,
  weight: 12.0,
  capture_rate: 50,
  base_egg_steps: 2560,
  male_gender_ratio: 25,
  experience_growth: 800_000,
  base_happiness: 70,
  hp: 140,
  attack: 70,
  defense: 45,
  sp_attack: 85,
  sp_defense: 50,
  speed: 45,
  type_1: Type.find_by(name: 'Normal'),
  type_2: Type.find_by(name: 'Fairy'),
  ability_1: Ability.find_by(name: 'cute_charm'),
  ability_2: Ability.find_by(name: 'competitive'),
  hidden_ability: Ability.find_by(name: 'frisk')
)
