Pokemon.create!(
  id: 61,
  name: 'Poliwhirl',
  classification: 'Tadpole',
  height: 1.0,
  weight: 20.0,
  capture_rate: 120,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 65,
  attack: 65,
  defense: 65,
  sp_attack: 50,
  sp_defense: 50,
  speed: 90,
  type_1: Type.find_by(name: 'Water'),
  ability_1: Ability.find_by(name: 'water_absorb'),
  ability_2: Ability.find_by(name: 'damp'),
  hidden_ability: Ability.find_by(name: 'swift_swim'),
)

Pokemon.create!(
  id: 62,
  name: 'Poliwrath',
  classification: 'Tadpole',
  height: 1.3,
  weight: 54.0,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 90,
  attack: 95,
  defense: 95,
  sp_attack: 70,
  sp_defense: 90,
  speed: 70,
  type_1: Type.find_by(name: 'Water'),
  type_2: Type.find_by(name: 'Fighting'),
  ability_1: Ability.find_by(name: 'water_absorb'),
  ability_2: Ability.find_by(name: 'damp'),
  hidden_ability: Ability.find_by(name: 'swift_swim'),
)

Pokemon.create!(
  id: 63,
  name: 'Abra',
  classification: 'Psi',
  height: 0.9,
  weight: 19.5,
  capture_rate: 200,
  base_egg_steps: 5120,
  male_gender_ratio: 75,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 25,
  attack: 20,
  defense: 15,
  sp_attack: 105,
  sp_defense: 55,
  speed: 90,
  type_1: Type.find_by(name: 'Psychic'),
  ability_1: Ability.find_by(name: 'synchronize'),
  ability_2: Ability.find_by(name: 'inner_focus'),
  hidden_ability: Ability.find_by(name: 'magic_guard'),
)

Pokemon.create!(
  id: 64,
  name: 'Kadabra',
  classification: 'Psi',
  height: 1.3,
  weight: 56.5,
  capture_rate: 100,
  base_egg_steps: 5120,
  male_gender_ratio: 75,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 40,
  attack: 35,
  defense: 30,
  sp_attack: 120,
  sp_defense: 70,
  speed: 105,
  type_1: Type.find_by(name: 'Psychic'),
  ability_1: Ability.find_by(name: 'synchronize'),
  ability_2: Ability.find_by(name: 'inner_focus'),
  hidden_ability: Ability.find_by(name: 'magic_guard'),
)

Pokemon.create!(
  id: 65,
  name: 'Alakazam',
  classification: 'Psi',
  height: 1.5,
  weight: 48.0,
  capture_rate: 50,
  base_egg_steps: 5120,
  male_gender_ratio: 75,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 55,
  attack: 50,
  defense: 45,
  sp_attack: 135,
  sp_defense: 95,
  speed: 120,
  type_1: Type.find_by(name: 'Psychic'),
  ability_1: Ability.find_by(name: 'synchronize'),
  ability_2: Ability.find_by(name: 'inner_focus'),
  hidden_ability: Ability.find_by(name: 'magic_guard'),
)

Pokemon.create!(
  id: 66,
  name: 'Machop',
  classification: 'Superpower',
  height: 0.8,
  weight: 19.5,
  capture_rate: 180,
  base_egg_steps: 5120,
  male_gender_ratio: 75,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 70,
  attack: 80,
  defense: 50,
  sp_attack: 35,
  sp_defense: 35,
  speed: 35,
  type_1: Type.find_by(name: 'Fighting'),
  ability_1: Ability.find_by(name: 'guts'),
  ability_2: Ability.find_by(name: 'no_guard'),
  hidden_ability: Ability.find_by(name: 'steadfast'),
)

Pokemon.create!(
  id: 67,
  name: 'Machoke',
  classification: 'Superpower',
  height: 1.5,
  weight: 70.5,
  capture_rate: 90,
  base_egg_steps: 5120,
  male_gender_ratio: 75,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 80,
  attack: 100,
  defense: 70,
  sp_attack: 50,
  sp_defense: 60,
  speed: 45,
  type_1: Type.find_by(name: 'Fighting'),
  ability_1: Ability.find_by(name: 'guts'),
  ability_2: Ability.find_by(name: 'no_guard'),
  hidden_ability: Ability.find_by(name: 'steadfast'),
)

Pokemon.create!(
  id: 68,
  name: 'Machamp',
  classification: 'Superpower',
  height: 1.6,
  weight: 130.0,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 75,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 90,
  attack: 130,
  defense: 80,
  sp_attack: 65,
  sp_defense: 85,
  speed: 55,
  type_1: Type.find_by(name: 'Fighting'),
  ability_1: Ability.find_by(name: 'guts'),
  ability_2: Ability.find_by(name: 'no_guard'),
  hidden_ability: Ability.find_by(name: 'steadfast'),
)

Pokemon.create!(
  id: 69,
  name: 'Bellsprout',
  classification: 'Flower',
  height: 0.7,
  weight: 4.0,
  capture_rate: 255,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 50,
  attack: 75,
  defense: 35,
  sp_attack: 70,
  sp_defense: 30,
  speed: 40,
  type_1: Type.find_by(name: 'Grass'),
  type_2: Type.find_by(name: 'Poison'),
  ability_1: Ability.find_by(name: 'chlorophyll'),
  hidden_ability: Ability.find_by(name: 'gluttony'),
)

Pokemon.create!(
  id: 70,
  name: 'Weepinbell',
  classification: 'Flycatcher',
  height: 1.0,
  weight: 6.4,
  capture_rate: 120,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 65,
  attack: 90,
  defense: 50,
  sp_attack: 85,
  sp_defense: 45,
  speed: 55,
  type_1: Type.find_by(name: 'Grass'),
  type_2: Type.find_by(name: 'Poison'),
  ability_1: Ability.find_by(name: 'chlorophyll'),
  hidden_ability: Ability.find_by(name: 'gluttony'),
)

Pokemon.create!(
  id: 71,
  name: 'Victreebel',
  classification: 'Flycatcher',
  height: 1.7,
  weight: 15.5,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 80,
  attack: 105,
  defense: 65,
  sp_attack: 100,
  sp_defense: 70,
  speed: 70,
  type_1: Type.find_by(name: 'Grass'),
  type_2: Type.find_by(name: 'Poison'),
  ability_1: Ability.find_by(name: 'chlorophyll'),
  hidden_ability: Ability.find_by(name: 'gluttony'),
)

Pokemon.create!(
  id: 72,
  name: 'Tentacool',
  classification: 'Jellyfish',
  height: 0.9,
  weight: 45.5,
  capture_rate: 190,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_250_000,
  base_happiness: 70,
  hp: 40,
  attack: 40,
  defense: 35,
  sp_attack: 50,
  sp_defense: 100,
  speed: 70,
  type_1: Type.find_by(name: 'Water'),
  type_2: Type.find_by(name: 'Poison'),
  ability_1: Ability.find_by(name: 'clear_body'),
  ability_2: Ability.find_by(name: 'liquid_ooze'),
  hidden_ability: Ability.find_by(name: 'rain_dish'),
)

Pokemon.create!(
  id: 73,
  name: 'Tentacruel',
  classification: 'Jellyfish',
  height: 1.6,
  weight: 55.0,
  capture_rate: 60,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_250_000,
  base_happiness: 70,
  hp: 80,
  attack: 70,
  defense: 65,
  sp_attack: 80,
  sp_defense: 120,
  speed: 100,
  type_1: Type.find_by(name: 'Water'),
  type_2: Type.find_by(name: 'Poison'),
  ability_1: Ability.find_by(name: 'clear_body'),
  ability_2: Ability.find_by(name: 'liquid_ooze'),
  hidden_ability: Ability.find_by(name: 'rain_dish'),
)

Pokemon.create!(
  id: 74,
  name: 'Geodude',
  classification: 'Rock',
  height: 0.4,
  weight: 20.0,
  capture_rate: 255,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 40,
  attack: 80,
  defense: 100,
  sp_attack: 30,
  sp_defense: 30,
  speed: 20,
  type_1: Type.find_by(name: 'Rock'),
  ability_1: Ability.find_by(name: 'rock_head'),
  ability_2: Ability.find_by(name: 'sturdy'),
  hidden_ability: Ability.find_by(name: 'sand_veil'),
)

Pokemon.create!(
  id: 75,
  name: 'Graveler',
  classification: 'Rock',
  height: 1.0,
  weight: 105.0,
  capture_rate: 120,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 55,
  attack: 95,
  defense: 115,
  sp_attack: 45,
  sp_defense: 45,
  speed: 35,
  type_1: Type.find_by(name: 'Rock'),
  ability_1: Ability.find_by(name: 'rock_head'),
  ability_2: Ability.find_by(name: 'sturdy'),
  hidden_ability: Ability.find_by(name: 'sand_veil'),
)

Pokemon.create!(
  id: 76,
  name: 'Golem',
  classification: 'Megaton',
  height: 1.7,
  weight: 300.0,
  capture_rate: 45,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 80,
  attack: 120,
  defense: 130,
  sp_attack: 55,
  sp_defense: 65,
  speed: 45,
  type_1: Type.find_by(name: 'Rock'),
  ability_1: Ability.find_by(name: 'rock_head'),
  ability_2: Ability.find_by(name: 'sturdy'),
  hidden_ability: Ability.find_by(name: 'sand_veil'),
)

Pokemon.create!(
  id: 77,
  name: 'Ponyta',
  classification: 'Fire Horse',
  height: 1.0,
  weight: 30.0,
  capture_rate: 190,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 50,
  attack: 85,
  defense: 55,
  sp_attack: 65,
  sp_defense: 65,
  speed: 90,
  type_1: Type.find_by(name: 'Fire'),
  ability_1: Ability.find_by(name: 'run_away'),
  ability_2: Ability.find_by(name: 'flash_fire'),
  hidden_ability: Ability.find_by(name: 'flame_body'),
)

Pokemon.create!(
  id: 78,
  name: 'Rapidash',
  classification: 'Fire Horse',
  height: 1.7,
  weight: 95.0,
  capture_rate: 60,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 65,
  attack: 100,
  defense: 70,
  sp_attack: 80,
  sp_defense: 80,
  speed: 105,
  type_1: Type.find_by(name: 'Fire'),
  ability_1: Ability.find_by(name: 'run_away'),
  ability_2: Ability.find_by(name: 'flash_fire'),
  hidden_ability: Ability.find_by(name: 'flame_body'),
)

Pokemon.create!(
  id: 79,
  name: 'Slowpoke',
  classification: 'Dopey',
  height: 1.2,
  weight: 36.0,
  capture_rate: 190,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 90,
  attack: 65,
  defense: 65,
  sp_attack: 40,
  sp_defense: 40,
  speed: 15,
  type_1: Type.find_by(name: 'Water'),
  type_2: Type.find_by(name: 'Psychic'),
  ability_1: Ability.find_by(name: 'oblivious'),
  ability_2: Ability.find_by(name: 'own_tempo'),
  hidden_ability: Ability.find_by(name: 'regenerator'),
)

Pokemon.create!(
  id: 80,
  name: 'Slowbro',
  classification: 'Hermit Crab',
  height: 1.6,
  weight: 78.5,
  capture_rate: 75,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 95,
  attack: 75,
  defense: 110,
  sp_attack: 100,
  sp_defense: 80,
  speed: 30,
  type_1: Type.find_by(name: 'Water'),
  type_2: Type.find_by(name: 'Psychic'),
  ability_1: Ability.find_by(name: 'oblivious'),
  ability_2: Ability.find_by(name: 'own_tempo'),
  hidden_ability: Ability.find_by(name: 'regenerator'),
)
