Pokemon.create!(
  id: 141,
  name: 'Kabutops',
  classification: 'Shellfish',
  height: 1.3,
  weight: 40.5,
  capture_rate: 45,
  base_egg_steps: 7680,
  male_gender_ratio: 87.5,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 60,
  attack: 115,
  defense: 105,
  sp_attack: 65,
  sp_defense: 70,
  speed: 80,
  type_1: Type.find_by(name: 'Rock'),
  type_2: Type.find_by(name: 'Water'),
  ability_1: Ability.find_by(name: 'swift_swim'),
  ability_2: Ability.find_by(name: 'battle_armor'),
  hidden_ability: Ability.find_by(name: 'weak_armor'),
)

Pokemon.create!(
  id: 142,
  name: 'Aerodactyl',
  classification: 'Fossil',
  height: 1.8,
  weight: 59.0,
  capture_rate: 45,
  base_egg_steps: 8960,
  male_gender_ratio: 87.5,
  experience_growth: 1_250_000,
  base_happiness: 70,
  hp: 80,
  attack: 105,
  defense: 65,
  sp_attack: 60,
  sp_defense: 75,
  speed: 130,
  type_1: Type.find_by(name: 'Rock'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'rock_head'),
  ability_2: Ability.find_by(name: 'pressure'),
  hidden_ability: Ability.find_by(name: 'unnerve'),
)

Pokemon.create!(
  id: 143,
  name: 'Snorlax',
  classification: 'Sleeping',
  height: 2.1,
  weight: 460.0,
  capture_rate: 25,
  base_egg_steps: 10240,
  male_gender_ratio: 87.5,
  experience_growth: 1_250_000,
  base_happiness: 70,
  hp: 160,
  attack: 110,
  defense: 65,
  sp_attack: 65,
  sp_defense: 110,
  speed: 30,
  type_1: Type.find_by(name: 'Normal'),
  ability_1: Ability.find_by(name: 'immunity'),
  ability_2: Ability.find_by(name: 'thick_fat'),
  hidden_ability: Ability.find_by(name: 'gluttony'),
)

Pokemon.create!(
  id: 144,
  name: 'Articuno',
  classification: 'Freeze',
  height: 1.7,
  weight: 55.4,
  capture_rate: 3,
  base_egg_steps: 20480,
  experience_growth: 1_250_000,
  base_happiness: 35,
  hp: 90,
  attack: 85,
  defense: 100,
  sp_attack: 95,
  sp_defense: 125,
  speed: 85,
  type_1: Type.find_by(name: 'Ice'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'pressure'),
  hidden_ability: Ability.find_by(name: 'snow_cloak'),
)

Pokemon.create!(
  id: 145,
  name: 'Zapdos',
  classification: 'Electric',
  height: 1.6,
  weight: 52.6,
  capture_rate: 3,
  base_egg_steps: 20480,
  experience_growth: 1_250_000,
  base_happiness: 35,
  hp: 90,
  attack: 90,
  defense: 85,
  sp_attack: 125,
  sp_defense: 90,
  speed: 100,
  type_1: Type.find_by(name: 'Electric'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'pressure'),
  hidden_ability: Ability.find_by(name: 'static'),
)

Pokemon.create!(
  id: 146,
  name: 'Moltres',
  classification: 'Flame',
  height: 2.0,
  weight: 60.0,
  capture_rate: 3,
  base_egg_steps: 20480,
  experience_growth: 1_250_000,
  base_happiness: 35,
  hp: 90,
  attack: 100,
  defense: 90,
  sp_attack: 125,
  sp_defense: 85,
  speed: 90,
  type_1: Type.find_by(name: 'Fire'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'pressure'),
  hidden_ability: Ability.find_by(name: 'flame_body'),
)

Pokemon.create!(
  id: 147,
  name: 'Dratini',
  classification: 'Dragon',
  height: 1.8,
  weight: 3.3,
  capture_rate: 45,
  base_egg_steps: 10240,
  male_gender_ratio: 50,
  experience_growth: 1_250_000,
  base_happiness: 35,
  hp: 41,
  attack: 64,
  defense: 45,
  sp_attack: 50,
  sp_defense: 50,
  speed: 50,
  type_1: Type.find_by(name: 'Dragon'),
  ability_1: Ability.find_by(name: 'shed_skin'),
  hidden_ability: Ability.find_by(name: 'marvel_scale'),
)

Pokemon.create!(
  id: 148,
  name: 'Dragonair',
  classification: 'Dragon',
  height: 4.0,
  weight: 16.5,
  capture_rate: 45,
  base_egg_steps: 10240,
  male_gender_ratio: 50,
  experience_growth: 1_250_000,
  base_happiness: 35,
  hp: 61,
  attack: 84,
  defense: 65,
  sp_attack: 70,
  sp_defense: 70,
  speed: 70,
  type_1: Type.find_by(name: 'Dragon'),
  ability_1: Ability.find_by(name: 'shed_skin'),
  hidden_ability: Ability.find_by(name: 'marvel_scale'),
)

Pokemon.create!(
  id: 149,
  name: 'Dragonite',
  classification: 'Dragon',
  height: 2.2,
  weight: 210.0,
  capture_rate: 45,
  base_egg_steps: 10240,
  male_gender_ratio: 50,
  experience_growth: 1_250_000,
  base_happiness: 35,
  hp: 91,
  attack: 134,
  defense: 95,
  sp_attack: 100,
  sp_defense: 100,
  speed: 80,
  type_1: Type.find_by(name: 'Dragon'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'inner_focus'),
  hidden_ability: Ability.find_by(name: 'multiscale'),
)

Pokemon.create!(
  id: 150,
  name: 'Mewtwo',
  classification: 'Genetic',
  height: 2.0,
  weight: 122.0,
  capture_rate: 3,
  base_egg_steps: 30720,
  experience_growth: 1_250_000,
  base_happiness: 0,
  hp: 106,
  attack: 110,
  defense: 90,
  sp_attack: 154,
  sp_defense: 90,
  speed: 130,
  type_1: Type.find_by(name: 'Psychic'),
  ability_1: Ability.find_by(name: 'pressure'),
  hidden_ability: Ability.find_by(name: 'unnerve'),
)

Pokemon.create!(
  id: 151,
  name: 'Mew',
  classification: 'New Species',
  height: 0.4,
  weight: 4.0,
  capture_rate: 45,
  base_egg_steps: 30720,
  experience_growth: 1_059_860,
  base_happiness: 100,
  hp: 100,
  attack: 100,
  defense: 100,
  sp_attack: 100,
  sp_defense: 100,
  speed: 100,
  type_1: Type.find_by(name: 'Psychic'),
  ability_1: Ability.find_by(name: 'synchronize'),
)

Pokemon.create!(
  id: 152,
  name: 'Chikorita',
  classification: 'Leaf',
  height: 0.9,
  weight: 6.4,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 87.5,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 45,
  attack: 49,
  defense: 65,
  sp_attack: 49,
  sp_defense: 65,
  speed: 45,
  type_1: Type.find_by(name: 'Grass'),
  ability_1: Ability.find_by(name: 'overgrow'),
  hidden_ability: Ability.find_by(name: 'leaf_guard'),
)

Pokemon.create!(
  id: 153,
  name: 'Bayleef',
  classification: 'Leaf',
  height: 1.2,
  weight: 15.8,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 87.5,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 60,
  attack: 62,
  defense: 80,
  sp_attack: 63,
  sp_defense: 80,
  speed: 60,
  type_1: Type.find_by(name: 'Grass'),
  ability_1: Ability.find_by(name: 'overgrow'),
  hidden_ability: Ability.find_by(name: 'leaf_guard'),
)

Pokemon.create!(
  id: 154,
  name: 'Meganium',
  classification: 'Herb',
  height: 1.8,
  weight: 100.5,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 87.5,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 80,
  attack: 82,
  defense: 100,
  sp_attack: 83,
  sp_defense: 100,
  speed: 80,
  type_1: Type.find_by(name: 'Grass'),
  ability_1: Ability.find_by(name: 'overgrow'),
  hidden_ability: Ability.find_by(name: 'leaf_guard'),
)

Pokemon.create!(
  id: 155,
  name: 'Cyndaquil',
  classification: 'Fire Mouse',
  height: 0.5,
  weight: 7.9,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 87.5,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 39,
  attack: 52,
  defense: 43,
  sp_attack: 60,
  sp_defense: 50,
  speed: 65,
  type_1: Type.find_by(name: 'Fire'),
  ability_1: Ability.find_by(name: 'blaze'),
  hidden_ability: Ability.find_by(name: 'flash_fire'),
)

Pokemon.create!(
  id: 156,
  name: 'Quilava',
  classification: 'Volcano',
  height: 0.9,
  weight: 19.0,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 87.5,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 58,
  attack: 64,
  defense: 58,
  sp_attack: 80,
  sp_defense: 65,
  speed: 80,
  type_1: Type.find_by(name: 'Fire'),
  ability_1: Ability.find_by(name: 'blaze'),
  hidden_ability: Ability.find_by(name: 'flash_fire'),
)

Pokemon.create!(
  id: 157,
  name: 'Typhlosion',
  classification: 'Volcano',
  height: 1.7,
  weight: 79.5,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 87.5,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 78,
  attack: 84,
  defense: 78,
  sp_attack: 109,
  sp_defense: 85,
  speed: 100,
  type_1: Type.find_by(name: 'Fire'),
  ability_1: Ability.find_by(name: 'blaze'),
  hidden_ability: Ability.find_by(name: 'flash_fire'),
)

Pokemon.create!(
  id: 158,
  name: 'Totodile',
  classification: 'Big Jaw',
  height: 0.6,
  weight: 9.5,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 87.5,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 50,
  attack: 65,
  defense: 64,
  sp_attack: 44,
  sp_defense: 48,
  speed: 43,
  type_1: Type.find_by(name: 'Water'),
  ability_1: Ability.find_by(name: 'torrent'),
  hidden_ability: Ability.find_by(name: 'sheer_force'),
)

Pokemon.create!(
  id: 159,
  name: 'Croconaw',
  classification: 'Big Jaw',
  height: 1.1,
  weight: 25.0,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 87.5,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 65,
  attack: 80,
  defense: 80,
  sp_attack: 59,
  sp_defense: 63,
  speed: 58,
  type_1: Type.find_by(name: 'Water'),
  ability_1: Ability.find_by(name: 'torrent'),
  hidden_ability: Ability.find_by(name: 'sheer_force'),
)

Pokemon.create!(
  id: 160,
  name: 'Feraligatr',
  classification: 'Big Jaw',
  height: 2.3,
  weight: 88.8,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 87.5,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 85,
  attack: 105,
  defense: 100,
  sp_attack: 79,
  sp_defense: 83,
  speed: 78,
  type_1: Type.find_by(name: 'Water'),
  ability_1: Ability.find_by(name: 'torrent'),
  hidden_ability: Ability.find_by(name: 'sheer_force'),
)
