Pokemon.create!(
  id: 161,
  name: 'Sentret',
  classification: 'Scout',
  height: 0.8,
  weight: 6.0,
  capture_rate: 255,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 35,
  attack: 46,
  defense: 34,
  sp_attack: 35,
  sp_defense: 45,
  speed: 20,
  type_1: Type.find_by(name: 'Normal'),
  ability_1: Ability.find_by(name: 'run_away'),
  ability_2: Ability.find_by(name: 'keen_eye'),
  hidden_ability: Ability.find_by(name: 'frisk'),
)

Pokemon.create!(
  id: 162,
  name: 'Furret',
  classification: 'Long Body',
  height: 1.8,
  weight: 32.5,
  capture_rate: 90,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 85,
  attack: 76,
  defense: 64,
  sp_attack: 45,
  sp_defense: 55,
  speed: 90,
  type_1: Type.find_by(name: 'Normal'),
  ability_1: Ability.find_by(name: 'run_away'),
  ability_2: Ability.find_by(name: 'keen_eye'),
  hidden_ability: Ability.find_by(name: 'frisk'),
)

Pokemon.create!(
  id: 163,
  name: 'Hoothoot',
  classification: 'Owl',
  height: 0.7,
  weight: 21.2,
  capture_rate: 255,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 60,
  attack: 30,
  defense: 30,
  sp_attack: 36,
  sp_defense: 56,
  speed: 50,
  type_1: Type.find_by(name: 'Normal'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'insomnia'),
  ability_2: Ability.find_by(name: 'keen_eye'),
  hidden_ability: Ability.find_by(name: 'tinted_lens'),
)

Pokemon.create!(
  id: 164,
  name: 'Noctowl',
  classification: 'Owl',
  height: 1.6,
  weight: 40.8,
  capture_rate: 90,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 100,
  attack: 50,
  defense: 50,
  sp_attack: 86,
  sp_defense: 96,
  speed: 70,
  type_1: Type.find_by(name: 'Normal'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'insomnia'),
  ability_2: Ability.find_by(name: 'keen_eye'),
  hidden_ability: Ability.find_by(name: 'tinted_lens'),
)

Pokemon.create!(
  id: 165,
  name: 'Ledyba',
  classification: 'Five Star',
  height: 1.0,
  weight: 10.8,
  capture_rate: 255,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 800_000,
  base_happiness: 70,
  hp: 40,
  attack: 20,
  defense: 30,
  sp_attack: 40,
  sp_defense: 80,
  speed: 55,
  type_1: Type.find_by(name: 'Bug'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'swarm'),
  ability_2: Ability.find_by(name: 'early_bird'),
  hidden_ability: Ability.find_by(name: 'rattled'),
)

Pokemon.create!(
  id: 166,
  name: 'Ledian',
  classification: 'Five Star',
  height: 1.4,
  weight: 35.6,
  capture_rate: 90,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 800_000,
  base_happiness: 70,
  hp: 55,
  attack: 35,
  defense: 50,
  sp_attack: 55,
  sp_defense: 110,
  speed: 85,
  type_1: Type.find_by(name: 'Bug'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'swarm'),
  ability_2: Ability.find_by(name: 'early_bird'),
  hidden_ability: Ability.find_by(name: 'iron_fist'),
)

Pokemon.create!(
  id: 167,
  name: 'Spinarak',
  classification: 'String Spit',
  height: 0.5,
  weight: 8.5,
  capture_rate: 255,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 800_000,
  base_happiness: 70,
  hp: 40,
  attack: 60,
  defense: 40,
  sp_attack: 40,
  sp_defense: 40,
  speed: 30,
  type_1: Type.find_by(name: 'Bug'),
  type_2: Type.find_by(name: 'Poison'),
  ability_1: Ability.find_by(name: 'swarm'),
  ability_2: Ability.find_by(name: 'insomnia'),
  hidden_ability: Ability.find_by(name: 'sniper'),
)

Pokemon.create!(
  id: 168,
  name: 'Ariados',
  classification: 'Long Leg',
  height: 1.1,
  weight: 33.5,
  capture_rate: 90,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 800_000,
  base_happiness: 70,
  hp: 70,
  attack: 90,
  defense: 70,
  sp_attack: 60,
  sp_defense: 70,
  speed: 40,
  type_1: Type.find_by(name: 'Bug'),
  type_2: Type.find_by(name: 'Poison'),
  ability_1: Ability.find_by(name: 'swarm'),
  ability_2: Ability.find_by(name: 'insomnia'),
  hidden_ability: Ability.find_by(name: 'sniper'),
)

Pokemon.create!(
  id: 169,
  name: 'Crobat',
  classification: 'Bat',
  height: 1.8,
  weight: 75.0,
  capture_rate: 90,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 85,
  attack: 90,
  defense: 80,
  sp_attack: 70,
  sp_defense: 80,
  speed: 130,
  type_1: Type.find_by(name: 'Poison'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'inner_focus'),
  hidden_ability: Ability.find_by(name: 'infiltrator'),
)

Pokemon.create!(
  id: 170,
  name: 'Chinchou',
  classification: 'Angler',
  height: 0.5,
  weight: 12.0,
  capture_rate: 190,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_250_000,
  base_happiness: 70,
  hp: 75,
  attack: 38,
  defense: 38,
  sp_attack: 56,
  sp_defense: 56,
  speed: 67,
  type_1: Type.find_by(name: 'Water'),
  type_2: Type.find_by(name: 'Electric'),
  ability_1: Ability.find_by(name: 'volt_absorb'),
  ability_2: Ability.find_by(name: 'illuminate'),
  hidden_ability: Ability.find_by(name: 'water_absorb'),
)

Pokemon.create!(
  id: 171,
  name: 'Lanturn',
  classification: 'Light',
  height: 1.2,
  weight: 22.5,
  capture_rate: 75,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_250_000,
  base_happiness: 70,
  hp: 125,
  attack: 58,
  defense: 58,
  sp_attack: 76,
  sp_defense: 76,
  speed: 67,
  type_1: Type.find_by(name: 'Water'),
  type_2: Type.find_by(name: 'Electric'),
  ability_1: Ability.find_by(name: 'volt_absorb'),
  ability_2: Ability.find_by(name: 'illuminate'),
  hidden_ability: Ability.find_by(name: 'water_absorb'),
)

Pokemon.create!(
  id: 172,
  name: 'Pichu',
  classification: 'Tiny Mouse',
  height: 0.3,
  weight: 2.0,
  capture_rate: 190,
  base_egg_steps: 2560,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 20,
  attack: 40,
  defense: 15,
  sp_attack: 35,
  sp_defense: 35,
  speed: 60,
  type_1: Type.find_by(name: 'Electric'),
  ability_1: Ability.find_by(name: 'static'),
  hidden_ability: Ability.find_by(name: 'lightningrod'),
)

Pokemon.create!(
  id: 173,
  name: 'Cleffa',
  classification: 'Star Shape',
  height: 0.3,
  weight: 3.0,
  capture_rate: 150,
  base_egg_steps: 2560,
  male_gender_ratio: 25,
  experience_growth: 800_000,
  base_happiness: 140,
  hp: 50,
  attack: 25,
  defense: 28,
  sp_attack: 45,
  sp_defense: 55,
  speed: 15,
  type_1: Type.find_by(name: 'Fairy'),
  ability_1: Ability.find_by(name: 'cute_charm'),
  ability_2: Ability.find_by(name: 'magic_guard'),
  hidden_ability: Ability.find_by(name: 'friend_guard'),
)

Pokemon.create!(
  id: 174,
  name: 'Igglybuff',
  classification: 'Balloon',
  height: 0.3,
  weight: 1.0,
  capture_rate: 170,
  base_egg_steps: 2560,
  male_gender_ratio: 25,
  experience_growth: 800_000,
  base_happiness: 70,
  hp: 90,
  attack: 30,
  defense: 15,
  sp_attack: 40,
  sp_defense: 20,
  speed: 15,
  type_1: Type.find_by(name: 'Normal'),
  type_2: Type.find_by(name: 'Fairy'),
  ability_1: Ability.find_by(name: 'cute_charm'),
  ability_2: Ability.find_by(name: 'competitive'),
  hidden_ability: Ability.find_by(name: 'friend_guard'),
)

Pokemon.create!(
  id: 175,
  name: 'Togepi',
  classification: 'Spike Ball',
  height: 0.3,
  weight: 1.5,
  capture_rate: 190,
  base_egg_steps: 2560,
  male_gender_ratio: 87.5,
  experience_growth: 800_000,
  base_happiness: 70,
  hp: 35,
  attack: 20,
  defense: 65,
  sp_attack: 40,
  sp_defense: 65,
  speed: 20,
  type_1: Type.find_by(name: 'Fairy'),
  ability_1: Ability.find_by(name: 'hustle'),
  ability_2: Ability.find_by(name: 'serene_grace'),
  hidden_ability: Ability.find_by(name: 'super_luck'),
)

Pokemon.create!(
  id: 176,
  name: 'Togetic',
  classification: 'Happiness',
  height: 0.6,
  weight: 3.2,
  capture_rate: 75,
  base_egg_steps: 2560,
  male_gender_ratio: 87.5,
  experience_growth: 800_000,
  base_happiness: 70,
  hp: 55,
  attack: 40,
  defense: 85,
  sp_attack: 80,
  sp_defense: 105,
  speed: 40,
  type_1: Type.find_by(name: 'Fairy'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'hustle'),
  ability_2: Ability.find_by(name: 'serene_grace'),
  hidden_ability: Ability.find_by(name: 'super_luck'),
)

Pokemon.create!(
  id: 177,
  name: 'Natu',
  classification: 'Little Bird',
  height: 0.2,
  weight: 2.0,
  capture_rate: 190,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 40,
  attack: 50,
  defense: 45,
  sp_attack: 70,
  sp_defense: 45,
  speed: 70,
  type_1: Type.find_by(name: 'Psychic'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'synchronize'),
  ability_2: Ability.find_by(name: 'early_bird'),
  hidden_ability: Ability.find_by(name: 'magic_bounce'),
)

Pokemon.create!(
  id: 178,
  name: 'Xatu',
  classification: 'Mystic',
  height: 1.5,
  weight: 15.0,
  capture_rate: 75,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 65,
  attack: 75,
  defense: 70,
  sp_attack: 95,
  sp_defense: 70,
  speed: 95,
  type_1: Type.find_by(name: 'Psychic'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'synchronize'),
  ability_2: Ability.find_by(name: 'early_bird'),
  hidden_ability: Ability.find_by(name: 'magic_bounce'),
)

Pokemon.create!(
  id: 179,
  name: 'Mareep',
  classification: 'Wool',
  height: 0.6,
  weight: 7.8,
  capture_rate: 235,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 55,
  attack: 40,
  defense: 40,
  sp_attack: 65,
  sp_defense: 45,
  speed: 35,
  type_1: Type.find_by(name: 'Electric'),
  ability_1: Ability.find_by(name: 'static'),
  hidden_ability: Ability.find_by(name: 'plus'),
)

Pokemon.create!(
  id: 180,
  name: 'Flaaffy',
  classification: 'Wool',
  height: 0.8,
  weight: 13.3,
  capture_rate: 120,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 70,
  attack: 55,
  defense: 55,
  sp_attack: 80,
  sp_defense: 60,
  speed: 45,
  type_1: Type.find_by(name: 'Electric'),
  ability_1: Ability.find_by(name: 'static'),
  hidden_ability: Ability.find_by(name: 'plus'),
)
