Pokemon.create!(
  id: 181,
  name: 'Ampharos',
  classification: 'Light',
  height: 1.4,
  weight: 61.5,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 90,
  attack: 75,
  defense: 85,
  sp_attack: 115,
  sp_defense: 90,
  speed: 55,
  type_1: Type.find_by(name: 'Electric'),
  ability_1: Ability.find_by(name: 'static'),
  hidden_ability: Ability.find_by(name: 'plus'),
)

Pokemon.create!(
  id: 182,
  name: 'Bellossom',
  classification: 'Flower',
  height: 0.4,
  weight: 5.8,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 75,
  attack: 80,
  defense: 95,
  sp_attack: 90,
  sp_defense: 100,
  speed: 50,
  type_1: Type.find_by(name: 'Grass'),
  ability_1: Ability.find_by(name: 'chlorophyll'),
  hidden_ability: Ability.find_by(name: 'healer'),
)

Pokemon.create!(
  id: 183,
  name: 'Marill',
  classification: 'Aquamouse',
  height: 0.4,
  weight: 8.5,
  capture_rate: 190,
  base_egg_steps: 2560,
  male_gender_ratio: 50,
  experience_growth: 800_000,
  base_happiness: 70,
  hp: 70,
  attack: 20,
  defense: 50,
  sp_attack: 20,
  sp_defense: 50,
  speed: 40,
  type_1: Type.find_by(name: 'Water'),
  type_2: Type.find_by(name: 'Fairy'),
  ability_1: Ability.find_by(name: 'thick_fat'),
  ability_2: Ability.find_by(name: 'huge_power'),
  hidden_ability: Ability.find_by(name: 'sap_sipper'),
)

Pokemon.create!(
  id: 184,
  name: 'Azumarill',
  classification: 'Aquarabbit',
  height: 0.8,
  weight: 28.5,
  capture_rate: 75,
  base_egg_steps: 2560,
  male_gender_ratio: 50,
  experience_growth: 800_000,
  base_happiness: 70,
  hp: 100,
  attack: 50,
  defense: 80,
  sp_attack: 60,
  sp_defense: 80,
  speed: 50,
  type_1: Type.find_by(name: 'Water'),
  type_2: Type.find_by(name: 'Fairy'),
  ability_1: Ability.find_by(name: 'thick_fat'),
  ability_2: Ability.find_by(name: 'huge_power'),
  hidden_ability: Ability.find_by(name: 'sap_sipper'),
)

Pokemon.create!(
  id: 185,
  name: 'Sudowoodo',
  classification: 'Imitation',
  height: 1.2,
  weight: 38.0,
  capture_rate: 65,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 70,
  attack: 100,
  defense: 115,
  sp_attack: 30,
  sp_defense: 65,
  speed: 30,
  type_1: Type.find_by(name: 'Rock'),
  ability_1: Ability.find_by(name: 'sturdy'),
  ability_2: Ability.find_by(name: 'rock_head'),
  hidden_ability: Ability.find_by(name: 'rattled'),
)

Pokemon.create!(
  id: 186,
  name: 'Politoed',
  classification: 'Frog',
  height: 1.1,
  weight: 33.9,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 90,
  attack: 75,
  defense: 75,
  sp_attack: 90,
  sp_defense: 100,
  speed: 70,
  type_1: Type.find_by(name: 'Water'),
  ability_1: Ability.find_by(name: 'water_absorb'),
  ability_2: Ability.find_by(name: 'damp'),
  hidden_ability: Ability.find_by(name: 'drizzle'),
)

Pokemon.create!(
  id: 187,
  name: 'Hoppip',
  classification: 'Cottonweed',
  height: 0.4,
  weight: 0.5,
  capture_rate: 255,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 35,
  attack: 35,
  defense: 40,
  sp_attack: 35,
  sp_defense: 55,
  speed: 50,
  type_1: Type.find_by(name: 'Grass'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'chlorophyll'),
  ability_2: Ability.find_by(name: 'leaf_guard'),
  hidden_ability: Ability.find_by(name: 'infiltrator'),
)

Pokemon.create!(
  id: 188,
  name: 'Skiploom',
  classification: 'Cottonweed',
  height: 0.6,
  weight: 1.0,
  capture_rate: 120,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 55,
  attack: 45,
  defense: 50,
  sp_attack: 45,
  sp_defense: 65,
  speed: 80,
  type_1: Type.find_by(name: 'Grass'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'chlorophyll'),
  ability_2: Ability.find_by(name: 'leaf_guard'),
  hidden_ability: Ability.find_by(name: 'infiltrator'),
)

Pokemon.create!(
  id: 189,
  name: 'Jumpluff',
  classification: 'Cottonweed',
  height: 0.8,
  weight: 3.0,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 75,
  attack: 55,
  defense: 70,
  sp_attack: 55,
  sp_defense: 95,
  speed: 110,
  type_1: Type.find_by(name: 'Grass'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'chlorophyll'),
  ability_2: Ability.find_by(name: 'leaf_guard'),
  hidden_ability: Ability.find_by(name: 'infiltrator'),
)

Pokemon.create!(
  id: 190,
  name: 'Aipom',
  classification: 'Long Tail',
  height: 0.8,
  weight: 11.5,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 800_000,
  base_happiness: 70,
  hp: 55,
  attack: 70,
  defense: 55,
  sp_attack: 40,
  sp_defense: 55,
  speed: 85,
  type_1: Type.find_by(name: 'Normal'),
  ability_1: Ability.find_by(name: 'run_away'),
  ability_2: Ability.find_by(name: 'pickup'),
  hidden_ability: Ability.find_by(name: 'skill_link'),
)

Pokemon.create!(
  id: 191,
  name: 'Sunkern',
  classification: 'Seed',
  height: 0.3,
  weight: 1.8,
  capture_rate: 235,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 30,
  attack: 30,
  defense: 30,
  sp_attack: 30,
  sp_defense: 30,
  speed: 30,
  type_1: Type.find_by(name: 'Grass'),
  ability_1: Ability.find_by(name: 'chlorophyll'),
  ability_2: Ability.find_by(name: 'solar_power'),
  hidden_ability: Ability.find_by(name: 'early_bird'),
)

Pokemon.create!(
  id: 192,
  name: 'Sunflora',
  classification: 'Sun',
  height: 0.8,
  weight: 8.5,
  capture_rate: 120,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 75,
  attack: 75,
  defense: 55,
  sp_attack: 105,
  sp_defense: 85,
  speed: 30,
  type_1: Type.find_by(name: 'Grass'),
  ability_1: Ability.find_by(name: 'chlorophyll'),
  ability_2: Ability.find_by(name: 'solar_power'),
  hidden_ability: Ability.find_by(name: 'early_bird'),
)

Pokemon.create!(
  id: 193,
  name: 'Yanma',
  classification: 'Clear Wing',
  height: 1.2,
  weight: 38.0,
  capture_rate: 75,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 65,
  attack: 65,
  defense: 45,
  sp_attack: 75,
  sp_defense: 45,
  speed: 95,
  type_1: Type.find_by(name: 'Bug'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'speed_boost'),
  ability_2: Ability.find_by(name: 'compoundeyes'),
  hidden_ability: Ability.find_by(name: 'frisk'),
)

Pokemon.create!(
  id: 194,
  name: 'Wooper',
  classification: 'Water Fish',
  height: 0.4,
  weight: 8.5,
  capture_rate: 255,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 55,
  attack: 45,
  defense: 45,
  sp_attack: 25,
  sp_defense: 25,
  speed: 15,
  type_1: Type.find_by(name: 'Water'),
  type_2: Type.find_by(name: 'Ground'),
  ability_1: Ability.find_by(name: 'damp'),
  ability_2: Ability.find_by(name: 'water_absorb'),
  hidden_ability: Ability.find_by(name: 'unaware'),
)

Pokemon.create!(
  id: 195,
  name: 'Quagsire',
  classification: 'Water Fish',
  height: 1.4,
  weight: 75.0,
  capture_rate: 90,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 95,
  attack: 85,
  defense: 85,
  sp_attack: 65,
  sp_defense: 65,
  speed: 35,
  type_1: Type.find_by(name: 'Water'),
  type_2: Type.find_by(name: 'Ground'),
  ability_1: Ability.find_by(name: 'damp'),
  ability_2: Ability.find_by(name: 'water_absorb'),
  hidden_ability: Ability.find_by(name: 'unaware'),
)

Pokemon.create!(
  id: 196,
  name: 'Espeon',
  classification: 'Sun',
  height: 0.9,
  weight: 26.5,
  capture_rate: 45,
  base_egg_steps: 8960,
  male_gender_ratio: 87.5,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 65,
  attack: 65,
  defense: 60,
  sp_attack: 130,
  sp_defense: 95,
  speed: 110,
  type_1: Type.find_by(name: 'Psychic'),
  ability_1: Ability.find_by(name: 'synchronize'),
  hidden_ability: Ability.find_by(name: 'magic_bounce'),
)

Pokemon.create!(
  id: 197,
  name: 'Umbreon',
  classification: 'Moonlight',
  height: 1.0,
  weight: 27.0,
  capture_rate: 45,
  base_egg_steps: 8960,
  male_gender_ratio: 87.5,
  experience_growth: 1_000_000,
  base_happiness: 35,
  hp: 95,
  attack: 65,
  defense: 110,
  sp_attack: 60,
  sp_defense: 130,
  speed: 65,
  type_1: Type.find_by(name: 'Dark'),
  ability_1: Ability.find_by(name: 'synchronize'),
  hidden_ability: Ability.find_by(name: 'inner_focus'),
)

Pokemon.create!(
  id: 198,
  name: 'Murkrow',
  classification: 'Darkness',
  height: 0.5,
  weight: 2.1,
  capture_rate: 30,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 35,
  hp: 60,
  attack: 85,
  defense: 42,
  sp_attack: 85,
  sp_defense: 42,
  speed: 91,
  type_1: Type.find_by(name: 'Dark'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'insomnia'),
  ability_2: Ability.find_by(name: 'super_luck'),
  hidden_ability: Ability.find_by(name: 'prankster'),
)

Pokemon.create!(
  id: 199,
  name: 'Slowking',
  classification: 'Royal',
  height: 2.0,
  weight: 79.5,
  capture_rate: 70,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 95,
  attack: 75,
  defense: 80,
  sp_attack: 100,
  sp_defense: 110,
  speed: 30,
  type_1: Type.find_by(name: 'Water'),
  type_2: Type.find_by(name: 'Psychic'),
  ability_1: Ability.find_by(name: 'oblivious'),
  ability_2: Ability.find_by(name: 'own_tempo'),
  hidden_ability: Ability.find_by(name: 'regenerator'),
)

Pokemon.create!(
  id: 200,
  name: 'Misdreavus',
  classification: 'Screech',
  height: 0.7,
  weight: 1.0,
  capture_rate: 45,
  base_egg_steps: 6400,
  male_gender_ratio: 50,
  experience_growth: 800_000,
  base_happiness: 35,
  hp: 60,
  attack: 60,
  defense: 60,
  sp_attack: 85,
  sp_defense: 85,
  speed: 85,
  type_1: Type.find_by(name: 'Ghost'),
  ability_1: Ability.find_by(name: 'levitate'),
)
