Pokemon.create!(
  id: 201,
  name: 'Unown',
  classification: 'Symbol',
  height: 0.5,
  weight: 5.0,
  capture_rate: 225,
  base_egg_steps: 10240,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 48,
  attack: 72,
  defense: 48,
  sp_attack: 72,
  sp_defense: 48,
  speed: 48,
  type_1: Type.find_by(name: 'Psychic'),
  ability_1: Ability.find_by(name: 'levitate'),
)

Pokemon.create!(
  id: 202,
  name: 'Wobbuffet',
  classification: 'Patient',
  height: 1.3,
  weight: 28.5,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 190,
  attack: 33,
  defense: 58,
  sp_attack: 33,
  sp_defense: 58,
  speed: 33,
  type_1: Type.find_by(name: 'Psychic'),
  ability_1: Ability.find_by(name: 'shadow_tag'),
  hidden_ability: Ability.find_by(name: 'telepathy'),
)

Pokemon.create!(
  id: 203,
  name: 'Girafarig',
  classification: 'Long Neck',
  height: 1.5,
  weight: 41.5,
  capture_rate: 60,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 70,
  attack: 80,
  defense: 65,
  sp_attack: 90,
  sp_defense: 65,
  speed: 85,
  type_1: Type.find_by(name: 'Normal'),
  type_2: Type.find_by(name: 'Psychic'),
  ability_1: Ability.find_by(name: 'inner_focus'),
  ability_2: Ability.find_by(name: 'early_bird'),
  hidden_ability: Ability.find_by(name: 'sap_sipper'),
)

Pokemon.create!(
  id: 204,
  name: 'Pineco',
  classification: 'Bagworm',
  height: 0.6,
  weight: 7.2,
  capture_rate: 190,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 50,
  attack: 65,
  defense: 90,
  sp_attack: 35,
  sp_defense: 35,
  speed: 15,
  type_1: Type.find_by(name: 'Bug'),
  ability_1: Ability.find_by(name: 'sturdy'),
  ability_2: Ability.find_by(name: 'overcoat'),
  hidden_ability: Ability.find_by(name: 'powder_moves'),
)

Pokemon.create!(
  id: 205,
  name: 'Forretress',
  classification: 'Bagworm',
  height: 1.2,
  weight: 125.8,
  capture_rate: 75,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 75,
  attack: 90,
  defense: 140,
  sp_attack: 60,
  sp_defense: 60,
  speed: 40,
  type_1: Type.find_by(name: 'Bug'),
  type_2: Type.find_by(name: 'Steel'),
  ability_1: Ability.find_by(name: 'sturdy'),
  ability_2: Ability.find_by(name: 'overcoat'),
  hidden_ability: Ability.find_by(name: 'powder_moves'),
)

Pokemon.create!(
  id: 206,
  name: 'Dunsparce',
  classification: 'Land Snake',
  height: 1.5,
  weight: 14.0,
  capture_rate: 190,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 100,
  attack: 70,
  defense: 70,
  sp_attack: 65,
  sp_defense: 65,
  speed: 45,
  type_1: Type.find_by(name: 'Normal'),
  ability_1: Ability.find_by(name: 'serene_grace'),
  ability_2: Ability.find_by(name: 'run_away'),
  hidden_ability: Ability.find_by(name: 'rattled'),
)

Pokemon.create!(
  id: 207,
  name: 'Gligar',
  classification: 'Flyscorpion',
  height: 1.1,
  weight: 64.8,
  capture_rate: 60,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 65,
  attack: 75,
  defense: 105,
  sp_attack: 35,
  sp_defense: 65,
  speed: 85,
  type_1: Type.find_by(name: 'Ground'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'hyper_cutter'),
  ability_2: Ability.find_by(name: 'sand_veil'),
  hidden_ability: Ability.find_by(name: 'immunity'),
)

Pokemon.create!(
  id: 208,
  name: 'Steelix',
  classification: 'Iron Snake',
  height: 9.2,
  weight: 400.0,
  capture_rate: 25,
  base_egg_steps: 6400,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 75,
  attack: 85,
  defense: 200,
  sp_attack: 55,
  sp_defense: 65,
  speed: 30,
  type_1: Type.find_by(name: 'Steel'),
  type_2: Type.find_by(name: 'Ground'),
  ability_1: Ability.find_by(name: 'rock_head'),
  ability_2: Ability.find_by(name: 'sturdy'),
  hidden_ability: Ability.find_by(name: 'sheer_force'),
)

Pokemon.create!(
  id: 209,
  name: 'Snubbull',
  classification: 'Fairy',
  height: 0.6,
  weight: 7.8,
  capture_rate: 190,
  base_egg_steps: 5120,
  male_gender_ratio: 25,
  experience_growth: 800_000,
  base_happiness: 70,
  hp: 60,
  attack: 80,
  defense: 50,
  sp_attack: 40,
  sp_defense: 40,
  speed: 30,
  type_1: Type.find_by(name: 'Fairy'),
  ability_1: Ability.find_by(name: 'intimidate'),
  ability_2: Ability.find_by(name: 'run_away'),
  hidden_ability: Ability.find_by(name: 'rattled'),
)

Pokemon.create!(
  id: 210,
  name: 'Granbull',
  classification: 'Fairy',
  height: 1.4,
  weight: 48.7,
  capture_rate: 75,
  base_egg_steps: 5120,
  male_gender_ratio: 25,
  experience_growth: 800_000,
  base_happiness: 70,
  hp: 90,
  attack: 120,
  defense: 75,
  sp_attack: 60,
  sp_defense: 60,
  speed: 45,
  type_1: Type.find_by(name: 'Fairy'),
  ability_1: Ability.find_by(name: 'intimidate'),
  ability_2: Ability.find_by(name: 'quick_feet'),
  hidden_ability: Ability.find_by(name: 'rattled'),
)

Pokemon.create!(
  id: 211,
  name: 'Qwilfish',
  classification: 'Balloon',
  height: 0.5,
  weight: 3.9,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 65,
  attack: 95,
  defense: 85,
  sp_attack: 55,
  sp_defense: 55,
  speed: 85,
  type_1: Type.find_by(name: 'Water'),
  type_2: Type.find_by(name: 'Poison'),
  ability_1: Ability.find_by(name: 'poison_point'),
  ability_2: Ability.find_by(name: 'swift_swim'),
  hidden_ability: Ability.find_by(name: 'intimidate'),
)

Pokemon.create!(
  id: 212,
  name: 'Scizor',
  classification: 'Pincer',
  height: 1.8,
  weight: 118.0,
  capture_rate: 25,
  base_egg_steps: 6400,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 70,
  attack: 130,
  defense: 100,
  sp_attack: 55,
  sp_defense: 80,
  speed: 65,
  type_1: Type.find_by(name: 'Bug'),
  type_2: Type.find_by(name: 'Steel'),
  ability_1: Ability.find_by(name: 'swarm'),
  ability_2: Ability.find_by(name: 'technician'),
  hidden_ability: Ability.find_by(name: 'light_metal'),
)

Pokemon.create!(
  id: 213,
  name: 'Shuckle',
  classification: 'Mold',
  height: 0.6,
  weight: 20.5,
  capture_rate: 190,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 20,
  attack: 10,
  defense: 230,
  sp_attack: 10,
  sp_defense: 230,
  speed: 5,
  type_1: Type.find_by(name: 'Bug'),
  type_2: Type.find_by(name: 'Rock'),
  ability_1: Ability.find_by(name: 'sturdy'),
  ability_2: Ability.find_by(name: 'gluttony'),
  hidden_ability: Ability.find_by(name: 'contrary'),
)

Pokemon.create!(
  id: 214,
  name: 'Heracross',
  classification: 'Singlehorn',
  height: 1.5,
  weight: 54.0,
  capture_rate: 45,
  base_egg_steps: 6400,
  male_gender_ratio: 50,
  experience_growth: 1_250_000,
  base_happiness: 70,
  hp: 80,
  attack: 125,
  defense: 75,
  sp_attack: 40,
  sp_defense: 95,
  speed: 85,
  type_1: Type.find_by(name: 'Bug'),
  type_2: Type.find_by(name: 'Fighting'),
  ability_1: Ability.find_by(name: 'swarm'),
  ability_2: Ability.find_by(name: 'guts'),
  hidden_ability: Ability.find_by(name: 'moxie'),
)

Pokemon.create!(
  id: 215,
  name: 'Sneasel',
  classification: 'Sharp Claw',
  height: 0.9,
  weight: 28.0,
  capture_rate: 60,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 35,
  hp: 55,
  attack: 95,
  defense: 55,
  sp_attack: 35,
  sp_defense: 75,
  speed: 115,
  type_1: Type.find_by(name: 'Dark'),
  type_2: Type.find_by(name: 'Ice'),
  ability_1: Ability.find_by(name: 'inner_focus'),
  ability_2: Ability.find_by(name: 'keen_eye'),
  hidden_ability: Ability.find_by(name: 'pickpocket'),
)

Pokemon.create!(
  id: 216,
  name: 'Teddiursa',
  classification: 'Little Bear',
  height: 0.6,
  weight: 8.8,
  capture_rate: 120,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 60,
  attack: 80,
  defense: 50,
  sp_attack: 50,
  sp_defense: 50,
  speed: 40,
  type_1: Type.find_by(name: 'Normal'),
  ability_1: Ability.find_by(name: 'pickup'),
  ability_2: Ability.find_by(name: 'quick_feet'),
  hidden_ability: Ability.find_by(name: 'honey_gather'),
)

Pokemon.create!(
  id: 217,
  name: 'Ursaring',
  classification: 'Hibernator',
  height: 1.8,
  weight: 125.8,
  capture_rate: 60,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 90,
  attack: 130,
  defense: 75,
  sp_attack: 75,
  sp_defense: 75,
  speed: 55,
  type_1: Type.find_by(name: 'Normal'),
  ability_1: Ability.find_by(name: 'guts'),
  ability_2: Ability.find_by(name: 'quick_feet'),
  hidden_ability: Ability.find_by(name: 'unnerve'),
)

Pokemon.create!(
  id: 218,
  name: 'Slugma',
  classification: 'Lava',
  height: 0.7,
  weight: 35.0,
  capture_rate: 190,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 40,
  attack: 40,
  defense: 40,
  sp_attack: 70,
  sp_defense: 40,
  speed: 20,
  type_1: Type.find_by(name: 'Fire'),
  ability_1: Ability.find_by(name: 'magma_armor'),
  ability_2: Ability.find_by(name: 'flame_body'),
  hidden_ability: Ability.find_by(name: 'weak_armor'),
)

Pokemon.create!(
  id: 219,
  name: 'Magcargo',
  classification: 'Lava',
  height: 0.8,
  weight: 55.0,
  capture_rate: 75,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 60,
  attack: 50,
  defense: 120,
  sp_attack: 90,
  sp_defense: 80,
  speed: 30,
  type_1: Type.find_by(name: 'Fire'),
  type_2: Type.find_by(name: 'Rock'),
  ability_1: Ability.find_by(name: 'magma_armor'),
  ability_2: Ability.find_by(name: 'flame_body'),
  hidden_ability: Ability.find_by(name: 'weak_armor'),
)

Pokemon.create!(
  id: 220,
  name: 'Swinub',
  classification: 'Pig',
  height: 0.4,
  weight: 6.5,
  capture_rate: 225,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_250_000,
  base_happiness: 70,
  hp: 50,
  attack: 50,
  defense: 40,
  sp_attack: 30,
  sp_defense: 30,
  speed: 50,
  type_1: Type.find_by(name: 'Ice'),
  type_2: Type.find_by(name: 'Ground'),
  ability_1: Ability.find_by(name: 'oblivious'),
  ability_2: Ability.find_by(name: 'snow_cloak'),
  hidden_ability: Ability.find_by(name: 'thick_fat'),
)
