Pokemon.create!(
  id: 261,
  name: 'Poochyena',
  classification: 'Bite',
  height: 0.5,
  weight: 13.6,
  capture_rate: 255,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 35,
  attack: 55,
  defense: 35,
  sp_attack: 30,
  sp_defense: 30,
  speed: 35,
  type_1: Type.find_by(name: 'Dark'),
  ability_1: Ability.find_by(name: 'run_away'),
  ability_2: Ability.find_by(name: 'quick_feet'),
  hidden_ability: Ability.find_by(name: 'rattled')
)

Pokemon.create!(
  id: 262,
  name: 'Mightyena',
  classification: 'Bite',
  height: 1.0,
  weight: 37.0,
  capture_rate: 127,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 70,
  attack: 90,
  defense: 70,
  sp_attack: 60,
  sp_defense: 60,
  speed: 70,
  type_1: Type.find_by(name: 'Dark'),
  ability_1: Ability.find_by(name: 'intimidate'),
  ability_2: Ability.find_by(name: 'quick_feet'),
  hidden_ability: Ability.find_by(name: 'moxie')
)

Pokemon.create!(
  id: 263,
  name: 'Zigzagoon',
  classification: 'Tiny Racoon',
  height: 0.4,
  weight: 17.5,
  capture_rate: 255,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 38,
  attack: 30,
  defense: 41,
  sp_attack: 30,
  sp_defense: 41,
  speed: 60,
  type_1: Type.find_by(name: 'Normal'),
  ability_1: Ability.find_by(name: 'pickup'),
  ability_2: Ability.find_by(name: 'gluttony'),
  hidden_ability: Ability.find_by(name: 'quick_feet')
)

Pokemon.create!(
  id: 264,
  name: 'Linoone',
  classification: 'Rush',
  height: 0.5,
  weight: 32.5,
  capture_rate: 90,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 78,
  attack: 70,
  defense: 61,
  sp_attack: 50,
  sp_defense: 61,
  speed: 100,
  type_1: Type.find_by(name: 'Normal'),
  ability_1: Ability.find_by(name: 'pickup'),
  ability_2: Ability.find_by(name: 'gluttony'),
  hidden_ability: Ability.find_by(name: 'quick_feet')
)

Pokemon.create!(
  id: 265,
  name: 'Wurmple',
  classification: 'Worm',
  height: 0.3,
  weight: 3.6,
  capture_rate: 255,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 45,
  attack: 45,
  defense: 35,
  sp_attack: 20,
  sp_defense: 30,
  speed: 20,
  type_1: Type.find_by(name: 'Bug'),
  ability_1: Ability.find_by(name: 'shield_dust'),
  hidden_ability: Ability.find_by(name: 'run_away')
)

Pokemon.create!(
  id: 266,
  name: 'Silcoon',
  classification: 'Cocoon',
  height: 0.6,
  weight: 10.0,
  capture_rate: 120,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 50,
  attack: 35,
  defense: 55,
  sp_attack: 25,
  sp_defense: 25,
  speed: 15,
  type_1: Type.find_by(name: 'Bug'),
  ability_1: Ability.find_by(name: 'shed_skin')
)

Pokemon.create!(
  id: 267,
  name: 'Beautifly',
  classification: 'Butterfly',
  height: 1.0,
  weight: 28.4,
  capture_rate: 45,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 60,
  attack: 70,
  defense: 50,
  sp_attack: 100,
  sp_defense: 50,
  speed: 65,
  type_1: Type.find_by(name: 'Bug'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'swarm'),
  hidden_ability: Ability.find_by(name: 'rivalry')
)

Pokemon.create!(
  id: 268,
  name: 'Cascoon',
  classification: 'Cocoon',
  height: 0.7,
  weight: 11.5,
  capture_rate: 120,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 50,
  attack: 35,
  defense: 55,
  sp_attack: 25,
  sp_defense: 25,
  speed: 15,
  type_1: Type.find_by(name: 'Bug'),
  ability_1: Ability.find_by(name: 'shed_skin')
)

Pokemon.create!(
  id: 269,
  name: 'Dustox',
  classification: 'Poison Moth',
  height: 1.2,
  weight: 31.6,
  capture_rate: 45,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 60,
  attack: 50,
  defense: 70,
  sp_attack: 50,
  sp_defense: 90,
  speed: 65,
  type_1: Type.find_by(name: 'Bug'),
  type_2: Type.find_by(name: 'Poison'),
  ability_1: Ability.find_by(name: 'shield_dust'),
  hidden_ability: Ability.find_by(name: 'compoundeyes')
)

Pokemon.create!(
  id: 270,
  name: 'Lotad',
  classification: 'Water Weed',
  height: 0.5,
  weight: 2.6,
  capture_rate: 255,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 40,
  attack: 30,
  defense: 30,
  sp_attack: 40,
  sp_defense: 50,
  speed: 30,
  type_1: Type.find_by(name: 'Water'),
  type_2: Type.find_by(name: 'Grass'),
  ability_1: Ability.find_by(name: 'swift_swim'),
  ability_2: Ability.find_by(name: 'rain_dish'),
  hidden_ability: Ability.find_by(name: 'own_tempo')
)

Pokemon.create!(
  id: 271,
  name: 'Lombre',
  classification: 'Jolly',
  height: 1.2,
  weight: 32.5,
  capture_rate: 120,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 60,
  attack: 50,
  defense: 50,
  sp_attack: 60,
  sp_defense: 70,
  speed: 50,
  type_1: Type.find_by(name: 'Water'),
  type_2: Type.find_by(name: 'Grass'),
  ability_1: Ability.find_by(name: 'swift_swim'),
  ability_2: Ability.find_by(name: 'rain_dish'),
  hidden_ability: Ability.find_by(name: 'own_tempo')
)

Pokemon.create!(
  id: 272,
  name: 'Ludicolo',
  classification: 'Carefree',
  height: 1.5,
  weight: 55.0,
  capture_rate: 45,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 80,
  attack: 70,
  defense: 70,
  sp_attack: 90,
  sp_defense: 100,
  speed: 70,
  type_1: Type.find_by(name: 'Water'),
  type_2: Type.find_by(name: 'Grass'),
  ability_1: Ability.find_by(name: 'swift_swim'),
  ability_2: Ability.find_by(name: 'rain_dish'),
  hidden_ability: Ability.find_by(name: 'own_tempo')
)

Pokemon.create!(
  id: 273,
  name: 'Seedot',
  classification: 'Acorn',
  height: 0.5,
  weight: 4.0,
  capture_rate: 255,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 40,
  attack: 40,
  defense: 50,
  sp_attack: 30,
  sp_defense: 30,
  speed: 30,
  type_1: Type.find_by(name: 'Grass'),
  ability_1: Ability.find_by(name: 'chlorophyll'),
  ability_2: Ability.find_by(name: 'early_bird'),
  hidden_ability: Ability.find_by(name: 'pickpocket')
)

Pokemon.create!(
  id: 274,
  name: 'Nuzleaf',
  classification: 'Wily',
  height: 1.0,
  weight: 28.0,
  capture_rate: 120,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 70,
  attack: 70,
  defense: 40,
  sp_attack: 60,
  sp_defense: 40,
  speed: 60,
  type_1: Type.find_by(name: 'Grass'),
  type_2: Type.find_by(name: 'Dark'),
  ability_1: Ability.find_by(name: 'chlorophyll'),
  ability_2: Ability.find_by(name: 'early_bird'),
  hidden_ability: Ability.find_by(name: 'pickpocket')
)

Pokemon.create!(
  id: 275,
  name: 'Shiftry',
  classification: 'Wickid',
  height: 1.3,
  weight: 59.6,
  capture_rate: 45,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 90,
  attack: 100,
  defense: 60,
  sp_attack: 90,
  sp_defense: 60,
  speed: 80,
  type_1: Type.find_by(name: 'Grass'),
  type_2: Type.find_by(name: 'Dark'),
  ability_1: Ability.find_by(name: 'chlorophyll'),
  ability_2: Ability.find_by(name: 'early_bird'),
  hidden_ability: Ability.find_by(name: 'pickpocket')
)

Pokemon.create!(
  id: 276,
  name: 'Taillow',
  classification: 'TinySwallow',
  height: 0.3,
  weight: 2.3,
  capture_rate: 200,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 40,
  attack: 55,
  defense: 30,
  sp_attack: 30,
  sp_defense: 30,
  speed: 85,
  type_1: Type.find_by(name: 'Normal'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'guts'),
  hidden_ability: Ability.find_by(name: 'scrappy')
)

Pokemon.create!(
  id: 277,
  name: 'Swellow',
  classification: 'Swallow',
  height: 0.7,
  weight: 19.8,
  capture_rate: 45,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 60,
  attack: 85,
  defense: 60,
  sp_attack: 75,
  sp_defense: 50,
  speed: 125,
  type_1: Type.find_by(name: 'Normal'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'guts'),
  hidden_ability: Ability.find_by(name: 'scrappy')
)

Pokemon.create!(
  id: 278,
  name: 'Wingull',
  classification: 'Seagull',
  height: 0.6,
  weight: 9.5,
  capture_rate: 190,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 40,
  attack: 30,
  defense: 30,
  sp_attack: 55,
  sp_defense: 30,
  speed: 85,
  type_1: Type.find_by(name: 'Water'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'keen_eye'),
  ability_2: Ability.find_by(name: 'hydration'),
  hidden_ability: Ability.find_by(name: 'rain_dish')
)

Pokemon.create!(
  id: 279,
  name: 'Pelipper',
  classification: 'Water Bird',
  height: 1.2,
  weight: 28.0,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 60,
  attack: 50,
  defense: 100,
  sp_attack: 95,
  sp_defense: 70,
  speed: 65,
  type_1: Type.find_by(name: 'Water'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'keen_eye'),
  ability_2: Ability.find_by(name: 'drizzle'),
  hidden_ability: Ability.find_by(name: 'rain_dish')
)

Pokemon.create!(
  id: 280,
  name: 'Ralts',
  classification: 'Feeling',
  height: 0.4,
  weight: 6.6,
  capture_rate: 235,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_250_000,
  base_happiness: 35,
  hp: 28,
  attack: 25,
  defense: 25,
  sp_attack: 45,
  sp_defense: 35,
  speed: 40,
  type_1: Type.find_by(name: 'Psychic'),
  type_2: Type.find_by(name: 'Fairy'),
  ability_1: Ability.find_by(name: 'synchronize'),
  ability_2: Ability.find_by(name: 'trace'),
  hidden_ability: Ability.find_by(name: 'telepathy')
)
