Pokemon.create!(
  id: 301,
  name: 'Delcatty',
  classification: 'Prim',
  height: 1.1,
  weight: 32.6,
  capture_rate: 60,
  base_egg_steps: 3840,
  male_gender_ratio: 25,
  experience_growth: 800_000,
  base_happiness: 70,
  hp: 70,
  attack: 65,
  defense: 65,
  sp_attack: 55,
  sp_defense: 55,
  speed: 90,
  type_1: Type.find_by(name: 'Normal'),
  ability_1: Ability.find_by(name: 'cute_charm'),
  ability_2: Ability.find_by(name: 'normalize'),
  hidden_ability: Ability.find_by(name: 'wonder_skin_'),
)

Pokemon.create!(
  id: 302,
  name: 'Sableye',
  classification: 'Darkness',
  height: 0.5,
  weight: 11.0,
  capture_rate: 45,
  base_egg_steps: 6400,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 35,
  hp: 50,
  attack: 75,
  defense: 75,
  sp_attack: 65,
  sp_defense: 65,
  speed: 50,
  type_1: Type.find_by(name: 'Dark'),
  type_2: Type.find_by(name: 'Ghost'),
  ability_1: Ability.find_by(name: 'keen_eye'),
  ability_2: Ability.find_by(name: 'stall'),
  hidden_ability: Ability.find_by(name: 'prankster'),
)

Pokemon.create!(
  id: 303,
  name: 'Mawile',
  classification: 'Deceiver',
  height: 0.6,
  weight: 11.5,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 800_000,
  base_happiness: 70,
  hp: 50,
  attack: 85,
  defense: 85,
  sp_attack: 55,
  sp_defense: 55,
  speed: 50,
  type_1: Type.find_by(name: 'Steel'),
  type_2: Type.find_by(name: 'Fairy'),
  ability_1: Ability.find_by(name: 'hyper_cutter'),
  ability_2: Ability.find_by(name: 'intimidate'),
  hidden_ability: Ability.find_by(name: 'sheer_force'),
)

Pokemon.create!(
  id: 304,
  name: 'Aron',
  classification: 'Iron Armor',
  height: 0.4,
  weight: 60.0,
  capture_rate: 180,
  base_egg_steps: 8960,
  male_gender_ratio: 50,
  experience_growth: 1_250_000,
  base_happiness: 35,
  hp: 50,
  attack: 70,
  defense: 100,
  sp_attack: 40,
  sp_defense: 40,
  speed: 30,
  type_1: Type.find_by(name: 'Steel'),
  type_2: Type.find_by(name: 'Rock'),
  ability_1: Ability.find_by(name: 'sturdy'),
  ability_2: Ability.find_by(name: 'rock_head'),
  hidden_ability: Ability.find_by(name: 'heavy_metal'),
)

Pokemon.create!(
  id: 305,
  name: 'Lairon',
  classification: 'Iron Armor',
  height: 0.9,
  weight: 120.0,
  capture_rate: 90,
  base_egg_steps: 8960,
  male_gender_ratio: 50,
  experience_growth: 1_250_000,
  base_happiness: 35,
  hp: 60,
  attack: 90,
  defense: 140,
  sp_attack: 50,
  sp_defense: 50,
  speed: 40,
  type_1: Type.find_by(name: 'Steel'),
  type_2: Type.find_by(name: 'Rock'),
  ability_1: Ability.find_by(name: 'sturdy'),
  ability_2: Ability.find_by(name: 'rock_head'),
  hidden_ability: Ability.find_by(name: 'heavy_metal'),
)

Pokemon.create!(
  id: 306,
  name: 'Aggron',
  classification: 'Iron Armor',
  height: 2.1,
  weight: 360.0,
  capture_rate: 45,
  base_egg_steps: 8960,
  male_gender_ratio: 50,
  experience_growth: 1_250_000,
  base_happiness: 35,
  hp: 70,
  attack: 110,
  defense: 180,
  sp_attack: 60,
  sp_defense: 60,
  speed: 50,
  type_1: Type.find_by(name: 'Steel'),
  type_2: Type.find_by(name: 'Rock'),
  ability_1: Ability.find_by(name: 'sturdy'),
  ability_2: Ability.find_by(name: 'rock_head'),
  hidden_ability: Ability.find_by(name: 'heavy_metal'),
)

Pokemon.create!(
  id: 307,
  name: 'Meditite',
  classification: 'Meditate',
  height: 0.6,
  weight: 11.2,
  capture_rate: 180,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 30,
  attack: 40,
  defense: 55,
  sp_attack: 40,
  sp_defense: 55,
  speed: 60,
  type_1: Type.find_by(name: 'Fighting'),
  type_2: Type.find_by(name: 'Psychic'),
  ability_1: Ability.find_by(name: 'pure_power'),
  hidden_ability: Ability.find_by(name: 'telepathy'),
)

Pokemon.create!(
  id: 308,
  name: 'Medicham',
  classification: 'Meditate',
  height: 1.3,
  weight: 31.5,
  capture_rate: 90,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 60,
  attack: 60,
  defense: 75,
  sp_attack: 60,
  sp_defense: 75,
  speed: 80,
  type_1: Type.find_by(name: 'Fighting'),
  type_2: Type.find_by(name: 'Psychic'),
  ability_1: Ability.find_by(name: 'pure_power'),
  hidden_ability: Ability.find_by(name: 'telepathy'),
)

Pokemon.create!(
  id: 309,
  name: 'Electrike',
  classification: 'Lightning',
  height: 0.6,
  weight: 15.2,
  capture_rate: 120,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_250_000,
  base_happiness: 70,
  hp: 40,
  attack: 45,
  defense: 40,
  sp_attack: 65,
  sp_defense: 40,
  speed: 65,
  type_1: Type.find_by(name: 'Electric'),
  ability_1: Ability.find_by(name: 'static'),
  ability_2: Ability.find_by(name: 'lightningrod'),
  hidden_ability: Ability.find_by(name: 'minus'),
)

Pokemon.create!(
  id: 310,
  name: 'Manectric',
  classification: 'Discharge',
  height: 1.5,
  weight: 40.2,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_250_000,
  base_happiness: 70,
  hp: 70,
  attack: 75,
  defense: 60,
  sp_attack: 105,
  sp_defense: 60,
  speed: 105,
  type_1: Type.find_by(name: 'Electric'),
  ability_1: Ability.find_by(name: 'static'),
  ability_2: Ability.find_by(name: 'lightningrod'),
  hidden_ability: Ability.find_by(name: 'minus'),
)

Pokemon.create!(
  id: 311,
  name: 'Plusle',
  classification: 'Cheering',
  height: 0.4,
  weight: 4.2,
  capture_rate: 200,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 60,
  attack: 50,
  defense: 40,
  sp_attack: 85,
  sp_defense: 75,
  speed: 95,
  type_1: Type.find_by(name: 'Electric'),
  ability_1: Ability.find_by(name: 'plus'),
  hidden_ability: Ability.find_by(name: 'lightningrod'),
)

Pokemon.create!(
  id: 312,
  name: 'Minun',
  classification: 'Cheering',
  height: 0.4,
  weight: 4.2,
  capture_rate: 200,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 60,
  attack: 40,
  defense: 50,
  sp_attack: 75,
  sp_defense: 85,
  speed: 95,
  type_1: Type.find_by(name: 'Electric'),
  ability_1: Ability.find_by(name: 'minus'),
  hidden_ability: Ability.find_by(name: 'volt_absorb'),
)

Pokemon.create!(
  id: 313,
  name: 'Volbeat',
  classification: 'Firefly',
  height: 0.7,
  weight: 17.7,
  capture_rate: 150,
  base_egg_steps: 3840,
  male_gender_ratio: 100,
  experience_growth: 600_000,
  base_happiness: 70,
  hp: 65,
  attack: 73,
  defense: 75,
  sp_attack: 47,
  sp_defense: 85,
  speed: 85,
  type_1: Type.find_by(name: 'Bug'),
  ability_1: Ability.find_by(name: 'illuminate'),
  ability_2: Ability.find_by(name: 'swarm'),
  hidden_ability: Ability.find_by(name: 'prankster'),
)

Pokemon.create!(
  id: 314,
  name: 'Illumise',
  classification: 'Firefly',
  height: 0.6,
  weight: 17.7,
  capture_rate: 150,
  base_egg_steps: 3840,
  male_gender_ratio: 0,
  experience_growth: 1_640_000,
  base_happiness: 70,
  hp: 65,
  attack: 47,
  defense: 75,
  sp_attack: 73,
  sp_defense: 85,
  speed: 85,
  type_1: Type.find_by(name: 'Bug'),
  ability_1: Ability.find_by(name: 'oblivious'),
  ability_2: Ability.find_by(name: 'tinted_lens'),
  hidden_ability: Ability.find_by(name: 'prankster'),
)

Pokemon.create!(
  id: 315,
  name: 'Roselia',
  classification: 'Thorn',
  height: 0.3,
  weight: 2.0,
  capture_rate: 150,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 50,
  attack: 60,
  defense: 45,
  sp_attack: 100,
  sp_defense: 80,
  speed: 65,
  type_1: Type.find_by(name: 'Grass'),
  type_2: Type.find_by(name: 'Poison'),
  ability_1: Ability.find_by(name: 'natural_cure'),
  ability_2: Ability.find_by(name: 'poison_point'),
  hidden_ability: Ability.find_by(name: 'leaf_guard'),
)

Pokemon.create!(
  id: 316,
  name: 'Gulpin',
  classification: 'Stomach',
  height: 0.4,
  weight: 10.3,
  capture_rate: 225,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_640_000,
  base_happiness: 70,
  hp: 70,
  attack: 43,
  defense: 53,
  sp_attack: 43,
  sp_defense: 53,
  speed: 40,
  type_1: Type.find_by(name: 'Poison'),
  ability_1: Ability.find_by(name: 'liquid_ooze'),
  ability_2: Ability.find_by(name: 'sticky_hold'),
  hidden_ability: Ability.find_by(name: 'gluttony'),
)

Pokemon.create!(
  id: 317,
  name: 'Swalot',
  classification: 'Poison Bag',
  height: 1.7,
  weight: 80.0,
  capture_rate: 75,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_640_000,
  base_happiness: 70,
  hp: 100,
  attack: 73,
  defense: 83,
  sp_attack: 73,
  sp_defense: 83,
  speed: 55,
  type_1: Type.find_by(name: 'Poison'),
  ability_1: Ability.find_by(name: 'liquid_ooze'),
  ability_2: Ability.find_by(name: 'sticky_hold'),
  hidden_ability: Ability.find_by(name: 'gluttony'),
)

Pokemon.create!(
  id: 318,
  name: 'Carvanha',
  classification: 'Savage',
  height: 0.8,
  weight: 20.8,
  capture_rate: 225,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_250_000,
  base_happiness: 35,
  hp: 45,
  attack: 90,
  defense: 20,
  sp_attack: 65,
  sp_defense: 20,
  speed: 65,
  type_1: Type.find_by(name: 'Water'),
  type_2: Type.find_by(name: 'Dark'),
  ability_1: Ability.find_by(name: 'rough_skin'),
  hidden_ability: Ability.find_by(name: 'speed_boost'),
)

Pokemon.create!(
  id: 319,
  name: 'Sharpedo',
  classification: 'Brutal',
  height: 1.8,
  weight: 88.8,
  capture_rate: 60,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_250_000,
  base_happiness: 35,
  hp: 70,
  attack: 120,
  defense: 40,
  sp_attack: 95,
  sp_defense: 40,
  speed: 95,
  type_1: Type.find_by(name: 'Water'),
  type_2: Type.find_by(name: 'Dark'),
  ability_1: Ability.find_by(name: 'rough_skin'),
  hidden_ability: Ability.find_by(name: 'speed_boost'),
)

Pokemon.create!(
  id: 320,
  name: 'Wailmer',
  classification: 'Ball Whale',
  height: 2.0,
  weight: 130.0,
  capture_rate: 125,
  base_egg_steps: 10240,
  male_gender_ratio: 50,
  experience_growth: 1_640_000,
  base_happiness: 70,
  hp: 130,
  attack: 70,
  defense: 35,
  sp_attack: 70,
  sp_defense: 35,
  speed: 60,
  type_1: Type.find_by(name: 'Water'),
  ability_1: Ability.find_by(name: 'water_veil'),
  ability_2: Ability.find_by(name: 'oblivious'),
  hidden_ability: Ability.find_by(name: 'pressure'),
)
