Pokemon.create!(
  id: 321,
  name: 'Wailord',
  classification: 'Float Whale',
  height: 14.5,
  weight: 398.0,
  capture_rate: 60,
  base_egg_steps: 10240,
  male_gender_ratio: 50,
  experience_growth: 1_640_000,
  base_happiness: 70,
  hp: 170,
  attack: 90,
  defense: 45,
  sp_attack: 90,
  sp_defense: 45,
  speed: 60,
  type_1: Type.find_by(name: 'Water'),
  ability_1: Ability.find_by(name: 'water_veil'),
  ability_2: Ability.find_by(name: 'oblivious'),
  hidden_ability: Ability.find_by(name: 'pressure'),
)

Pokemon.create!(
  id: 322,
  name: 'Numel',
  classification: 'Numb',
  height: 0.7,
  weight: 24.0,
  capture_rate: 255,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 60,
  attack: 60,
  defense: 40,
  sp_attack: 65,
  sp_defense: 45,
  speed: 35,
  type_1: Type.find_by(name: 'Fire'),
  type_2: Type.find_by(name: 'Ground'),
  ability_1: Ability.find_by(name: 'oblivious'),
  ability_2: Ability.find_by(name: 'simple'),
  hidden_ability: Ability.find_by(name: 'own_tempo'),
)

Pokemon.create!(
  id: 323,
  name: 'Camerupt',
  classification: 'Eruption',
  height: 1.9,
  weight: 220.0,
  capture_rate: 150,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 70,
  attack: 100,
  defense: 70,
  sp_attack: 105,
  sp_defense: 75,
  speed: 40,
  type_1: Type.find_by(name: 'Fire'),
  type_2: Type.find_by(name: 'Ground'),
  ability_1: Ability.find_by(name: 'magma_armor'),
  ability_2: Ability.find_by(name: 'solid_rock'),
  hidden_ability: Ability.find_by(name: 'anger_point'),
)

Pokemon.create!(
  id: 324,
  name: 'Torkoal',
  classification: 'Coal',
  height: 0.5,
  weight: 80.4,
  capture_rate: 90,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 70,
  attack: 85,
  defense: 140,
  sp_attack: 85,
  sp_defense: 70,
  speed: 20,
  type_1: Type.find_by(name: 'Fire'),
  ability_1: Ability.find_by(name: 'white_smoke'),
  ability_2: Ability.find_by(name: 'drought'),
  hidden_ability: Ability.find_by(name: 'shell_armor'),
)

Pokemon.create!(
  id: 325,
  name: 'Spoink',
  classification: 'Bounce',
  height: 0.7,
  weight: 30.6,
  capture_rate: 255,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 800_000,
  base_happiness: 70,
  hp: 60,
  attack: 25,
  defense: 35,
  sp_attack: 70,
  sp_defense: 80,
  speed: 60,
  type_1: Type.find_by(name: 'Psychic'),
  ability_1: Ability.find_by(name: 'thick_fat'),
  ability_2: Ability.find_by(name: 'own_tempo'),
  hidden_ability: Ability.find_by(name: 'gluttony'),
)

Pokemon.create!(
  id: 326,
  name: 'Grumpig',
  classification: 'Manipulate',
  height: 0.9,
  weight: 71.5,
  capture_rate: 60,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 800_000,
  base_happiness: 70,
  hp: 80,
  attack: 45,
  defense: 65,
  sp_attack: 90,
  sp_defense: 110,
  speed: 80,
  type_1: Type.find_by(name: 'Psychic'),
  ability_1: Ability.find_by(name: 'thick_fat'),
  ability_2: Ability.find_by(name: 'own_tempo'),
  hidden_ability: Ability.find_by(name: 'gluttony'),
)

Pokemon.create!(
  id: 327,
  name: 'Spinda',
  classification: 'Spot Panda',
  height: 1.1,
  weight: 5.0,
  capture_rate: 255,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 800_000,
  base_happiness: 70,
  hp: 60,
  attack: 60,
  defense: 60,
  sp_attack: 60,
  sp_defense: 60,
  speed: 60,
  type_1: Type.find_by(name: 'Normal'),
  ability_1: Ability.find_by(name: 'own_tempo'),
  ability_2: Ability.find_by(name: 'tangled_feet'),
  hidden_ability: Ability.find_by(name: 'contrary'),
)

Pokemon.create!(
  id: 328,
  name: 'Trapinch',
  classification: 'Ant Pit',
  height: 0.7,
  weight: 15.0,
  capture_rate: 255,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 45,
  attack: 100,
  defense: 45,
  sp_attack: 45,
  sp_defense: 45,
  speed: 10,
  type_1: Type.find_by(name: 'Ground'),
  ability_1: Ability.find_by(name: 'hyper_cutter'),
  ability_2: Ability.find_by(name: 'arena_trap'),
  hidden_ability: Ability.find_by(name: 'sheer_force'),
)

Pokemon.create!(
  id: 329,
  name: 'Vibrava',
  classification: 'Vibration',
  height: 1.1,
  weight: 15.3,
  capture_rate: 120,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 50,
  attack: 70,
  defense: 50,
  sp_attack: 50,
  sp_defense: 50,
  speed: 70,
  type_1: Type.find_by(name: 'Ground'),
  type_2: Type.find_by(name: 'Dragon'),
  ability_1: Ability.find_by(name: 'levitate'),
)

Pokemon.create!(
  id: 330,
  name: 'Flygon',
  classification: 'Mystic',
  height: 2.0,
  weight: 82.0,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 80,
  attack: 100,
  defense: 80,
  sp_attack: 80,
  sp_defense: 80,
  speed: 100,
  type_1: Type.find_by(name: 'Ground'),
  type_2: Type.find_by(name: 'Dragon'),
  ability_1: Ability.find_by(name: 'levitate'),
)

Pokemon.create!(
  id: 331,
  name: 'Cacnea',
  classification: 'Cactus',
  height: 0.4,
  weight: 51.3,
  capture_rate: 190,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 35,
  hp: 50,
  attack: 85,
  defense: 40,
  sp_attack: 85,
  sp_defense: 40,
  speed: 35,
  type_1: Type.find_by(name: 'Grass'),
  ability_1: Ability.find_by(name: 'sand_veil'),
  hidden_ability: Ability.find_by(name: 'water_absorb'),
)

Pokemon.create!(
  id: 332,
  name: 'Cacturne',
  classification: 'Scarecrow',
  height: 1.3,
  weight: 77.4,
  capture_rate: 60,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 35,
  hp: 70,
  attack: 115,
  defense: 60,
  sp_attack: 115,
  sp_defense: 60,
  speed: 55,
  type_1: Type.find_by(name: 'Grass'),
  type_2: Type.find_by(name: 'Dark'),
  ability_1: Ability.find_by(name: 'sand_veil'),
  hidden_ability: Ability.find_by(name: 'water_absorb'),
)

Pokemon.create!(
  id: 333,
  name: 'Swablu',
  classification: 'Cotton Bird',
  height: 0.4,
  weight: 1.2,
  capture_rate: 255,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 600_000,
  base_happiness: 70,
  hp: 45,
  attack: 40,
  defense: 60,
  sp_attack: 40,
  sp_defense: 75,
  speed: 50,
  type_1: Type.find_by(name: 'Normal'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'natural_cure'),
  hidden_ability: Ability.find_by(name: 'cloud_nine'),
)

Pokemon.create!(
  id: 334,
  name: 'Altaria',
  classification: 'Humming',
  height: 1.1,
  weight: 20.6,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 600_000,
  base_happiness: 70,
  hp: 75,
  attack: 70,
  defense: 90,
  sp_attack: 70,
  sp_defense: 105,
  speed: 80,
  type_1: Type.find_by(name: 'Dragon'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'natural_cure'),
  hidden_ability: Ability.find_by(name: 'cloud_nine'),
)

Pokemon.create!(
  id: 335,
  name: 'Zangoose',
  classification: 'Cat Ferret',
  height: 1.3,
  weight: 40.3,
  capture_rate: 90,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 600_000,
  base_happiness: 70,
  hp: 73,
  attack: 115,
  defense: 60,
  sp_attack: 60,
  sp_defense: 60,
  speed: 90,
  type_1: Type.find_by(name: 'Normal'),
  ability_1: Ability.find_by(name: 'immunity'),
  hidden_ability: Ability.find_by(name: 'toxic_boost'),
)

Pokemon.create!(
  id: 336,
  name: 'Seviper',
  classification: 'Fang Snake',
  height: 2.7,
  weight: 52.5,
  capture_rate: 90,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_640_000,
  base_happiness: 70,
  hp: 73,
  attack: 100,
  defense: 60,
  sp_attack: 100,
  sp_defense: 60,
  speed: 65,
  type_1: Type.find_by(name: 'Poison'),
  ability_1: Ability.find_by(name: 'shed_skin'),
  hidden_ability: Ability.find_by(name: 'infiltrator'),
)

Pokemon.create!(
  id: 337,
  name: 'Lunatone',
  classification: 'Meteorite',
  height: 1.0,
  weight: 168.0,
  capture_rate: 45,
  base_egg_steps: 6400,
  experience_growth: 800_000,
  base_happiness: 70,
  hp: 90,
  attack: 55,
  defense: 65,
  sp_attack: 95,
  sp_defense: 85,
  speed: 70,
  type_1: Type.find_by(name: 'Rock'),
  type_2: Type.find_by(name: 'Psychic'),
  ability_1: Ability.find_by(name: 'levitate'),
)

Pokemon.create!(
  id: 338,
  name: 'Solrock',
  classification: 'Meteorite',
  height: 1.2,
  weight: 154.0,
  capture_rate: 45,
  base_egg_steps: 6400,
  experience_growth: 800_000,
  base_happiness: 70,
  hp: 90,
  attack: 95,
  defense: 85,
  sp_attack: 55,
  sp_defense: 65,
  speed: 70,
  type_1: Type.find_by(name: 'Rock'),
  type_2: Type.find_by(name: 'Psychic'),
  ability_1: Ability.find_by(name: 'levitate'),
)

Pokemon.create!(
  id: 339,
  name: 'Barboach',
  classification: 'Whiskers',
  height: 0.4,
  weight: 1.9,
  capture_rate: 190,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 50,
  attack: 48,
  defense: 43,
  sp_attack: 46,
  sp_defense: 41,
  speed: 60,
  type_1: Type.find_by(name: 'Water'),
  type_2: Type.find_by(name: 'Ground'),
  ability_1: Ability.find_by(name: 'oblivious'),
  ability_2: Ability.find_by(name: 'anticipation'),
  hidden_ability: Ability.find_by(name: 'hydration'),
)

Pokemon.create!(
  id: 340,
  name: 'Whiscash',
  classification: 'Whiskers',
  height: 0.9,
  weight: 23.6,
  capture_rate: 75,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 110,
  attack: 78,
  defense: 73,
  sp_attack: 76,
  sp_defense: 71,
  speed: 60,
  type_1: Type.find_by(name: 'Water'),
  type_2: Type.find_by(name: 'Ground'),
  ability_1: Ability.find_by(name: 'oblivious'),
  ability_2: Ability.find_by(name: 'anticipation'),
  hidden_ability: Ability.find_by(name: 'hydration'),
)
