Pokemon.create!(
  id: 341,
  name: 'Corphish',
  classification: 'Ruffian',
  height: 0.6,
  weight: 11.5,
  capture_rate: 205,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_640_000,
  base_happiness: 70,
  hp: 43,
  attack: 80,
  defense: 65,
  sp_attack: 50,
  sp_defense: 35,
  speed: 35,
  type_1: Type.find_by(name: 'Water'),
  ability_1: Ability.find_by(name: 'hyper_cutter'),
  ability_2: Ability.find_by(name: 'shell_armor'),
  hidden_ability: Ability.find_by(name: 'adaptability')
)

Pokemon.create!(
  id: 342,
  name: 'Crawdaunt',
  classification: 'Rogue',
  height: 1.1,
  weight: 32.8,
  capture_rate: 155,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_640_000,
  base_happiness: 70,
  hp: 63,
  attack: 120,
  defense: 85,
  sp_attack: 90,
  sp_defense: 55,
  speed: 55,
  type_1: Type.find_by(name: 'Water'),
  type_2: Type.find_by(name: 'Dark'),
  ability_1: Ability.find_by(name: 'hyper_cutter'),
  ability_2: Ability.find_by(name: 'shell_armor'),
  hidden_ability: Ability.find_by(name: 'adaptability')
)

Pokemon.create!(
  id: 343,
  name: 'Baltoy',
  classification: 'Clay Doll',
  height: 0.5,
  weight: 21.5,
  capture_rate: 255,
  base_egg_steps: 5120,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 40,
  attack: 40,
  defense: 55,
  sp_attack: 40,
  sp_defense: 70,
  speed: 55,
  type_1: Type.find_by(name: 'Ground'),
  type_2: Type.find_by(name: 'Psychic'),
  ability_1: Ability.find_by(name: 'levitate')
)

Pokemon.create!(
  id: 344,
  name: 'Claydol',
  classification: 'Clay Doll',
  height: 1.5,
  weight: 108.0,
  capture_rate: 90,
  base_egg_steps: 5120,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 60,
  attack: 70,
  defense: 105,
  sp_attack: 70,
  sp_defense: 120,
  speed: 75,
  type_1: Type.find_by(name: 'Ground'),
  type_2: Type.find_by(name: 'Psychic'),
  ability_1: Ability.find_by(name: 'levitate')
)

Pokemon.create!(
  id: 345,
  name: 'Lileep',
  classification: 'Sea Lily',
  height: 1.0,
  weight: 23.8,
  capture_rate: 45,
  base_egg_steps: 7680,
  male_gender_ratio: 87.5,
  experience_growth: 600_000,
  base_happiness: 70,
  hp: 66,
  attack: 41,
  defense: 77,
  sp_attack: 61,
  sp_defense: 87,
  speed: 23,
  type_1: Type.find_by(name: 'Rock'),
  type_2: Type.find_by(name: 'Grass'),
  ability_1: Ability.find_by(name: 'suction_cups'),
  hidden_ability: Ability.find_by(name: 'storm_drain')
)

Pokemon.create!(
  id: 346,
  name: 'Cradily',
  classification: 'Barnacle',
  height: 1.5,
  weight: 60.4,
  capture_rate: 45,
  base_egg_steps: 7680,
  male_gender_ratio: 87.5,
  experience_growth: 600_000,
  base_happiness: 70,
  hp: 86,
  attack: 81,
  defense: 97,
  sp_attack: 81,
  sp_defense: 107,
  speed: 43,
  type_1: Type.find_by(name: 'Rock'),
  type_2: Type.find_by(name: 'Grass'),
  ability_1: Ability.find_by(name: 'suction_cups'),
  hidden_ability: Ability.find_by(name: 'storm_drain')
)

Pokemon.create!(
  id: 347,
  name: 'Anorith',
  classification: 'Old Shrimp',
  height: 0.7,
  weight: 12.5,
  capture_rate: 45,
  base_egg_steps: 7680,
  male_gender_ratio: 87.5,
  experience_growth: 600_000,
  base_happiness: 70,
  hp: 45,
  attack: 95,
  defense: 50,
  sp_attack: 40,
  sp_defense: 50,
  speed: 75,
  type_1: Type.find_by(name: 'Rock'),
  type_2: Type.find_by(name: 'Bug'),
  ability_1: Ability.find_by(name: 'battle_armor'),
  hidden_ability: Ability.find_by(name: 'swift_swim')
)

Pokemon.create!(
  id: 348,
  name: 'Armaldo',
  classification: 'Plate',
  height: 1.5,
  weight: 68.2,
  capture_rate: 45,
  base_egg_steps: 7680,
  male_gender_ratio: 87.5,
  experience_growth: 600_000,
  base_happiness: 70,
  hp: 75,
  attack: 125,
  defense: 100,
  sp_attack: 70,
  sp_defense: 80,
  speed: 45,
  type_1: Type.find_by(name: 'Rock'),
  type_2: Type.find_by(name: 'Bug'),
  ability_1: Ability.find_by(name: 'battle_armor'),
  hidden_ability: Ability.find_by(name: 'swift_swim')
)

Pokemon.create!(
  id: 349,
  name: 'Feebas',
  classification: 'Fish',
  height: 0.6,
  weight: 7.4,
  capture_rate: 255,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 600_000,
  base_happiness: 70,
  hp: 20,
  attack: 15,
  defense: 20,
  sp_attack: 10,
  sp_defense: 55,
  speed: 80,
  type_1: Type.find_by(name: 'Water'),
  ability_1: Ability.find_by(name: 'swift_swim'),
  ability_2: Ability.find_by(name: 'oblivious'),
  hidden_ability: Ability.find_by(name: 'adaptability')
)

Pokemon.create!(
  id: 350,
  name: 'Milotic',
  classification: 'Tender',
  height: 6.2,
  weight: 162.0,
  capture_rate: 60,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 600_000,
  base_happiness: 70,
  hp: 95,
  attack: 60,
  defense: 79,
  sp_attack: 100,
  sp_defense: 125,
  speed: 81,
  type_1: Type.find_by(name: 'Water'),
  ability_1: Ability.find_by(name: 'marvel_scale'),
  ability_2: Ability.find_by(name: 'competitive'),
  hidden_ability: Ability.find_by(name: 'cute_charm')
)

Pokemon.create!(
  id: 351,
  name: 'Castform',
  classification: 'Weather',
  height: 0.3,
  weight: 0.8,
  capture_rate: 45,
  base_egg_steps: 6400,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 70,
  attack: 70,
  defense: 70,
  sp_attack: 70,
  sp_defense: 70,
  speed: 70,
  type_1: Type.find_by(name: 'Normal'),
  ability_1: Ability.find_by(name: 'forecast')
)

Pokemon.create!(
  id: 352,
  name: 'Kecleon',
  classification: 'Color Swap',
  height: 1.0,
  weight: 22.0,
  capture_rate: 200,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 60,
  attack: 90,
  defense: 70,
  sp_attack: 60,
  sp_defense: 120,
  speed: 40,
  type_1: Type.find_by(name: 'Normal'),
  ability_1: Ability.find_by(name: 'color_change'),
  hidden_ability: Ability.find_by(name: 'protean')
)

Pokemon.create!(
  id: 353,
  name: 'Shuppet',
  classification: 'Puppet',
  height: 0.6,
  weight: 2.3,
  capture_rate: 225,
  base_egg_steps: 6400,
  male_gender_ratio: 50,
  experience_growth: 800_000,
  base_happiness: 35,
  hp: 44,
  attack: 75,
  defense: 35,
  sp_attack: 63,
  sp_defense: 33,
  speed: 45,
  type_1: Type.find_by(name: 'Ghost'),
  ability_1: Ability.find_by(name: 'insomnia'),
  ability_2: Ability.find_by(name: 'frisk'),
  hidden_ability: Ability.find_by(name: 'cursed_body')
)

Pokemon.create!(
  id: 354,
  name: 'Banette',
  classification: 'Marionette',
  height: 1.1,
  weight: 12.5,
  capture_rate: 45,
  base_egg_steps: 6400,
  male_gender_ratio: 50,
  experience_growth: 800_000,
  base_happiness: 35,
  hp: 64,
  attack: 115,
  defense: 65,
  sp_attack: 83,
  sp_defense: 63,
  speed: 65,
  type_1: Type.find_by(name: 'Ghost'),
  ability_1: Ability.find_by(name: 'insomnia'),
  ability_2: Ability.find_by(name: 'frisk'),
  hidden_ability: Ability.find_by(name: 'cursed_body')
)

Pokemon.create!(
  id: 355,
  name: 'Duskull',
  classification: 'Requiem',
  height: 0.8,
  weight: 15.0,
  capture_rate: 190,
  base_egg_steps: 6400,
  male_gender_ratio: 50,
  experience_growth: 800_000,
  base_happiness: 35,
  hp: 20,
  attack: 40,
  defense: 90,
  sp_attack: 30,
  sp_defense: 90,
  speed: 25,
  type_1: Type.find_by(name: 'Ghost'),
  ability_1: Ability.find_by(name: 'levitate'),
  hidden_ability: Ability.find_by(name: 'frisk')
)

Pokemon.create!(
  id: 356,
  name: 'Dusclops',
  classification: 'Beckon',
  height: 1.6,
  weight: 30.6,
  capture_rate: 90,
  base_egg_steps: 6400,
  male_gender_ratio: 50,
  experience_growth: 800_000,
  base_happiness: 35,
  hp: 40,
  attack: 70,
  defense: 130,
  sp_attack: 60,
  sp_defense: 130,
  speed: 25,
  type_1: Type.find_by(name: 'Ghost'),
  ability_1: Ability.find_by(name: 'pressure'),
  hidden_ability: Ability.find_by(name: 'frisk')
)

Pokemon.create!(
  id: 357,
  name: 'Tropius',
  classification: 'Fruit',
  height: 2.0,
  weight: 100.0,
  capture_rate: 200,
  base_egg_steps: 6400,
  male_gender_ratio: 50,
  experience_growth: 1_250_000,
  base_happiness: 70,
  hp: 99,
  attack: 68,
  defense: 83,
  sp_attack: 72,
  sp_defense: 87,
  speed: 51,
  type_1: Type.find_by(name: 'Grass'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'chlorophyll'),
  ability_2: Ability.find_by(name: 'solar_power'),
  hidden_ability: Ability.find_by(name: 'harvest')
)

Pokemon.create!(
  id: 358,
  name: 'Chimecho',
  classification: 'Wind Chime',
  height: 0.6,
  weight: 1.0,
  capture_rate: 45,
  base_egg_steps: 6400,
  male_gender_ratio: 50,
  experience_growth: 800_000,
  base_happiness: 70,
  hp: 75,
  attack: 50,
  defense: 80,
  sp_attack: 95,
  sp_defense: 90,
  speed: 65,
  type_1: Type.find_by(name: 'Psychic'),
  ability_1: Ability.find_by(name: 'levitate')
)

Pokemon.create!(
  id: 359,
  name: 'Absol',
  classification: 'Disaster',
  height: 1.2,
  weight: 47.0,
  capture_rate: 30,
  base_egg_steps: 6400,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 35,
  hp: 65,
  attack: 130,
  defense: 60,
  sp_attack: 75,
  sp_defense: 60,
  speed: 75,
  type_1: Type.find_by(name: 'Dark'),
  ability_1: Ability.find_by(name: 'pressure'),
  ability_2: Ability.find_by(name: 'super_luck'),
  hidden_ability: Ability.find_by(name: 'justified')
)

Pokemon.create!(
  id: 360,
  name: 'Wynaut',
  classification: 'Bright',
  height: 0.6,
  weight: 14.0,
  capture_rate: 125,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 95,
  attack: 23,
  defense: 48,
  sp_attack: 23,
  sp_defense: 48,
  speed: 23,
  type_1: Type.find_by(name: 'Psychic'),
  ability_1: Ability.find_by(name: 'shadow_tag'),
  hidden_ability: Ability.find_by(name: 'telepathy')
)
