Pokemon.create!(
  id: 361,
  name: 'Snorunt',
  classification: 'Snow Hat',
  height: 0.7,
  weight: 16.8,
  capture_rate: 190,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 50,
  attack: 50,
  defense: 50,
  sp_attack: 50,
  sp_defense: 50,
  speed: 50,
  type_1: Type.find_by(name: 'Ice'),
  ability_1: Ability.find_by(name: 'inner_focus'),
  ability_2: Ability.find_by(name: 'ice_body'),
  hidden_ability: Ability.find_by(name: 'moody')
)

Pokemon.create!(
  id: 362,
  name: 'Glalie',
  classification: 'Face',
  height: 1.5,
  weight: 256.5,
  capture_rate: 75,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 80,
  attack: 80,
  defense: 80,
  sp_attack: 80,
  sp_defense: 80,
  speed: 80,
  type_1: Type.find_by(name: 'Ice'),
  ability_1: Ability.find_by(name: 'inner_focus'),
  ability_2: Ability.find_by(name: 'ice_body'),
  hidden_ability: Ability.find_by(name: 'moody')
)

Pokemon.create!(
  id: 363,
  name: 'Spheal',
  classification: 'Clap',
  height: 0.8,
  weight: 39.5,
  capture_rate: 255,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 70,
  attack: 40,
  defense: 50,
  sp_attack: 55,
  sp_defense: 50,
  speed: 25,
  type_1: Type.find_by(name: 'Ice'),
  type_2: Type.find_by(name: 'Water'),
  ability_1: Ability.find_by(name: 'thick_fat'),
  ability_2: Ability.find_by(name: 'ice_body'),
  hidden_ability: Ability.find_by(name: 'oblivious')
)

Pokemon.create!(
  id: 364,
  name: 'Sealeo',
  classification: 'Ball Roll',
  height: 1.1,
  weight: 87.6,
  capture_rate: 120,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 90,
  attack: 60,
  defense: 70,
  sp_attack: 75,
  sp_defense: 70,
  speed: 45,
  type_1: Type.find_by(name: 'Ice'),
  type_2: Type.find_by(name: 'Water'),
  ability_1: Ability.find_by(name: 'thick_fat'),
  ability_2: Ability.find_by(name: 'ice_body'),
  hidden_ability: Ability.find_by(name: 'oblivious')
)

Pokemon.create!(
  id: 365,
  name: 'Walrein',
  classification: 'Ice Break',
  height: 1.4,
  weight: 150.6,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 110,
  attack: 80,
  defense: 90,
  sp_attack: 95,
  sp_defense: 90,
  speed: 65,
  type_1: Type.find_by(name: 'Ice'),
  type_2: Type.find_by(name: 'Water'),
  ability_1: Ability.find_by(name: 'thick_fat'),
  ability_2: Ability.find_by(name: 'ice_body'),
  hidden_ability: Ability.find_by(name: 'oblivious')
)

Pokemon.create!(
  id: 366,
  name: 'Clamperl',
  classification: 'Bivalve',
  height: 0.4,
  weight: 52.5,
  capture_rate: 255,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 600_000,
  base_happiness: 70,
  hp: 35,
  attack: 64,
  defense: 85,
  sp_attack: 74,
  sp_defense: 55,
  speed: 32,
  type_1: Type.find_by(name: 'Water'),
  ability_1: Ability.find_by(name: 'shell_armor'),
  hidden_ability: Ability.find_by(name: 'rattled')
)

Pokemon.create!(
  id: 367,
  name: 'Huntail',
  classification: 'Deep Sea',
  height: 1.7,
  weight: 27.0,
  capture_rate: 60,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 600_000,
  base_happiness: 70,
  hp: 55,
  attack: 104,
  defense: 105,
  sp_attack: 94,
  sp_defense: 75,
  speed: 52,
  type_1: Type.find_by(name: 'Water'),
  ability_1: Ability.find_by(name: 'swift_swim'),
  hidden_ability: Ability.find_by(name: 'water_veil')
)

Pokemon.create!(
  id: 368,
  name: 'Gorebyss',
  classification: 'South Sea',
  height: 1.8,
  weight: 22.6,
  capture_rate: 60,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 600_000,
  base_happiness: 70,
  hp: 55,
  attack: 84,
  defense: 105,
  sp_attack: 114,
  sp_defense: 75,
  speed: 52,
  type_1: Type.find_by(name: 'Water'),
  ability_1: Ability.find_by(name: 'swift_swim'),
  hidden_ability: Ability.find_by(name: 'hydration')
)

Pokemon.create!(
  id: 369,
  name: 'Relicanth',
  classification: 'Longevity',
  height: 1.0,
  weight: 23.4,
  capture_rate: 25,
  base_egg_steps: 10_240,
  male_gender_ratio: 87.5,
  experience_growth: 1_250_000,
  base_happiness: 70,
  hp: 100,
  attack: 90,
  defense: 130,
  sp_attack: 45,
  sp_defense: 65,
  speed: 55,
  type_1: Type.find_by(name: 'Water'),
  type_2: Type.find_by(name: 'Rock'),
  ability_1: Ability.find_by(name: 'swift_swim'),
  ability_2: Ability.find_by(name: 'rock_head'),
  hidden_ability: Ability.find_by(name: 'sturdy')
)

Pokemon.create!(
  id: 370,
  name: 'Luvdisc',
  classification: 'Rendezvous',
  height: 0.6,
  weight: 8.7,
  capture_rate: 225,
  base_egg_steps: 5120,
  male_gender_ratio: 25,
  experience_growth: 800_000,
  base_happiness: 70,
  hp: 43,
  attack: 30,
  defense: 55,
  sp_attack: 40,
  sp_defense: 65,
  speed: 97,
  type_1: Type.find_by(name: 'Water'),
  ability_1: Ability.find_by(name: 'swift_swim'),
  hidden_ability: Ability.find_by(name: 'hydration')
)

Pokemon.create!(
  id: 371,
  name: 'Bagon',
  classification: 'Rock Head',
  height: 0.6,
  weight: 42.1,
  capture_rate: 45,
  base_egg_steps: 10_240,
  male_gender_ratio: 50,
  experience_growth: 1_250_000,
  base_happiness: 35,
  hp: 45,
  attack: 75,
  defense: 60,
  sp_attack: 40,
  sp_defense: 30,
  speed: 50,
  type_1: Type.find_by(name: 'Dragon'),
  ability_1: Ability.find_by(name: 'rock_head'),
  hidden_ability: Ability.find_by(name: 'sheer_force')
)

Pokemon.create!(
  id: 372,
  name: 'Shelgon',
  classification: 'Endurance',
  height: 1.1,
  weight: 110.5,
  capture_rate: 45,
  base_egg_steps: 10_240,
  male_gender_ratio: 50,
  experience_growth: 1_250_000,
  base_happiness: 35,
  hp: 65,
  attack: 95,
  defense: 100,
  sp_attack: 60,
  sp_defense: 50,
  speed: 50,
  type_1: Type.find_by(name: 'Dragon'),
  ability_1: Ability.find_by(name: 'rock_head'),
  ability_2: Ability.find_by(name: 'overcoat'),
  hidden_ability: Ability.find_by(name: 'powder_moves')
)

Pokemon.create!(
  id: 373,
  name: 'Salamence',
  classification: 'Dragon',
  height: 1.5,
  weight: 102.6,
  capture_rate: 45,
  base_egg_steps: 10_240,
  male_gender_ratio: 50,
  experience_growth: 1_250_000,
  base_happiness: 35,
  hp: 95,
  attack: 135,
  defense: 80,
  sp_attack: 110,
  sp_defense: 80,
  speed: 100,
  type_1: Type.find_by(name: 'Dragon'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'intimidate'),
  hidden_ability: Ability.find_by(name: 'moxie')
)

Pokemon.create!(
  id: 374,
  name: 'Beldum',
  classification: 'Iron Ball',
  height: 0.6,
  weight: 95.2,
  capture_rate: 3,
  base_egg_steps: 10_240,
  experience_growth: 1_250_000,
  base_happiness: 35,
  hp: 40,
  attack: 55,
  defense: 80,
  sp_attack: 35,
  sp_defense: 60,
  speed: 30,
  type_1: Type.find_by(name: 'Steel'),
  type_2: Type.find_by(name: 'Psychic'),
  ability_1: Ability.find_by(name: 'clear_body'),
  hidden_ability: Ability.find_by(name: 'light_metal')
)

Pokemon.create!(
  id: 375,
  name: 'Metang',
  classification: 'Iron Claw',
  height: 1.2,
  weight: 202.5,
  capture_rate: 3,
  base_egg_steps: 10_240,
  experience_growth: 1_250_000,
  base_happiness: 35,
  hp: 60,
  attack: 75,
  defense: 100,
  sp_attack: 55,
  sp_defense: 80,
  speed: 50,
  type_1: Type.find_by(name: 'Steel'),
  type_2: Type.find_by(name: 'Psychic'),
  ability_1: Ability.find_by(name: 'clear_body'),
  hidden_ability: Ability.find_by(name: 'light_metal')
)

Pokemon.create!(
  id: 376,
  name: 'Metagross',
  classification: 'Iron Leg',
  height: 1.6,
  weight: 550.0,
  capture_rate: 3,
  base_egg_steps: 10_240,
  experience_growth: 1_250_000,
  base_happiness: 35,
  hp: 80,
  attack: 135,
  defense: 130,
  sp_attack: 95,
  sp_defense: 90,
  speed: 70,
  type_1: Type.find_by(name: 'Steel'),
  type_2: Type.find_by(name: 'Psychic'),
  ability_1: Ability.find_by(name: 'clear_body'),
  hidden_ability: Ability.find_by(name: 'light_metal')
)

Pokemon.create!(
  id: 377,
  name: 'Regirock',
  classification: 'Rock Peak',
  height: 1.7,
  weight: 230.0,
  capture_rate: 3,
  base_egg_steps: 20_480,
  experience_growth: 1_250_000,
  base_happiness: 35,
  hp: 80,
  attack: 100,
  defense: 200,
  sp_attack: 50,
  sp_defense: 100,
  speed: 50,
  type_1: Type.find_by(name: 'Rock'),
  ability_1: Ability.find_by(name: 'clear_body'),
  hidden_ability: Ability.find_by(name: 'sturdy')
)

Pokemon.create!(
  id: 378,
  name: 'Regice',
  classification: 'Iceberg',
  height: 1.8,
  weight: 175.0,
  capture_rate: 3,
  base_egg_steps: 20_480,
  experience_growth: 1_250_000,
  base_happiness: 35,
  hp: 80,
  attack: 50,
  defense: 100,
  sp_attack: 100,
  sp_defense: 200,
  speed: 50,
  type_1: Type.find_by(name: 'Ice'),
  ability_1: Ability.find_by(name: 'clear_body'),
  hidden_ability: Ability.find_by(name: 'ice_body')
)

Pokemon.create!(
  id: 379,
  name: 'Registeel',
  classification: 'Iron',
  height: 1.9,
  weight: 205.0,
  capture_rate: 3,
  base_egg_steps: 20_480,
  experience_growth: 1_250_000,
  base_happiness: 35,
  hp: 80,
  attack: 75,
  defense: 150,
  sp_attack: 75,
  sp_defense: 150,
  speed: 50,
  type_1: Type.find_by(name: 'Steel'),
  ability_1: Ability.find_by(name: 'clear_body'),
  hidden_ability: Ability.find_by(name: 'light_metal')
)

Pokemon.create!(
  id: 380,
  name: 'Latias',
  classification: 'Eon',
  height: 1.4,
  weight: 40.0,
  capture_rate: 3,
  base_egg_steps: 30_720,
  male_gender_ratio: 0,
  experience_growth: 1_250_000,
  base_happiness: 90,
  hp: 80,
  attack: 80,
  defense: 90,
  sp_attack: 110,
  sp_defense: 130,
  speed: 110,
  type_1: Type.find_by(name: 'Dragon'),
  type_2: Type.find_by(name: 'Psychic'),
  ability_1: Ability.find_by(name: 'levitate')
)
