Pokemon.create!(
  id: 401,
  name: 'Kricketot',
  classification: 'Cricket',
  height: 0.3,
  weight: 2.2,
  capture_rate: 255,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 37,
  attack: 25,
  defense: 41,
  sp_attack: 25,
  sp_defense: 41,
  speed: 25,
  type_1: Type.find_by(name: 'Bug'),
  ability_1: Ability.find_by(name: 'shed_skin'),
  hidden_ability: Ability.find_by(name: 'run_away')
)

Pokemon.create!(
  id: 402,
  name: 'Kricketune',
  classification: 'Cricket',
  height: 1.0,
  weight: 25.5,
  capture_rate: 45,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 77,
  attack: 85,
  defense: 51,
  sp_attack: 55,
  sp_defense: 51,
  speed: 65,
  type_1: Type.find_by(name: 'Bug'),
  ability_1: Ability.find_by(name: 'swarm'),
  hidden_ability: Ability.find_by(name: 'technician')
)

Pokemon.create!(
  id: 403,
  name: 'Shinx',
  classification: 'Flash',
  height: 0.5,
  weight: 9.5,
  capture_rate: 235,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 45,
  attack: 65,
  defense: 34,
  sp_attack: 40,
  sp_defense: 34,
  speed: 45,
  type_1: Type.find_by(name: 'Electric'),
  ability_1: Ability.find_by(name: 'rivalry'),
  ability_2: Ability.find_by(name: 'intimidate'),
  hidden_ability: Ability.find_by(name: 'guts')
)

Pokemon.create!(
  id: 404,
  name: 'Luxio',
  classification: 'Spark',
  height: 0.9,
  weight: 30.5,
  capture_rate: 120,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 100,
  hp: 60,
  attack: 85,
  defense: 49,
  sp_attack: 60,
  sp_defense: 49,
  speed: 60,
  type_1: Type.find_by(name: 'Electric'),
  ability_1: Ability.find_by(name: 'rivalry'),
  ability_2: Ability.find_by(name: 'intimidate'),
  hidden_ability: Ability.find_by(name: 'guts')
)

Pokemon.create!(
  id: 405,
  name: 'Luxray',
  classification: 'Gleam Eyes',
  height: 1.4,
  weight: 42.0,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 80,
  attack: 120,
  defense: 79,
  sp_attack: 95,
  sp_defense: 79,
  speed: 70,
  type_1: Type.find_by(name: 'Electric'),
  ability_1: Ability.find_by(name: 'rivalry'),
  ability_2: Ability.find_by(name: 'intimidate'),
  hidden_ability: Ability.find_by(name: 'guts')
)

Pokemon.create!(
  id: 406,
  name: 'Budew',
  classification: 'Bud',
  height: 0.2,
  weight: 1.2,
  capture_rate: 255,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 40,
  attack: 30,
  defense: 35,
  sp_attack: 50,
  sp_defense: 70,
  speed: 55,
  type_1: Type.find_by(name: 'Grass'),
  type_2: Type.find_by(name: 'Poison'),
  ability_1: Ability.find_by(name: 'natural_cure'),
  ability_2: Ability.find_by(name: 'poison_point'),
  hidden_ability: Ability.find_by(name: 'leaf_guard')
)

Pokemon.create!(
  id: 407,
  name: 'Roserade',
  classification: 'Bouquet',
  height: 0.9,
  weight: 14.5,
  capture_rate: 75,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 60,
  attack: 70,
  defense: 65,
  sp_attack: 125,
  sp_defense: 105,
  speed: 90,
  type_1: Type.find_by(name: 'Grass'),
  type_2: Type.find_by(name: 'Poison'),
  ability_1: Ability.find_by(name: 'natural_cure'),
  ability_2: Ability.find_by(name: 'poison_point'),
  hidden_ability: Ability.find_by(name: 'technician')
)

Pokemon.create!(
  id: 408,
  name: 'Cranidos',
  classification: 'Head Butt',
  height: 0.9,
  weight: 31.5,
  capture_rate: 45,
  base_egg_steps: 7680,
  male_gender_ratio: 87.5,
  experience_growth: 600_000,
  base_happiness: 70,
  hp: 67,
  attack: 125,
  defense: 40,
  sp_attack: 30,
  sp_defense: 30,
  speed: 58,
  type_1: Type.find_by(name: 'Rock'),
  ability_1: Ability.find_by(name: 'mold_breaker'),
  hidden_ability: Ability.find_by(name: 'sheer_force')
)

Pokemon.create!(
  id: 409,
  name: 'Rampardos',
  classification: 'Head Butt',
  height: 1.6,
  weight: 102.5,
  capture_rate: 45,
  base_egg_steps: 7680,
  male_gender_ratio: 87.5,
  experience_growth: 600_000,
  base_happiness: 70,
  hp: 97,
  attack: 165,
  defense: 60,
  sp_attack: 65,
  sp_defense: 50,
  speed: 58,
  type_1: Type.find_by(name: 'Rock'),
  ability_1: Ability.find_by(name: 'mold_breaker'),
  hidden_ability: Ability.find_by(name: 'sheer_force')
)

Pokemon.create!(
  id: 410,
  name: 'Shieldon',
  classification: 'Shield',
  height: 0.5,
  weight: 57.0,
  capture_rate: 45,
  base_egg_steps: 7680,
  male_gender_ratio: 87.5,
  experience_growth: 600_000,
  base_happiness: 70,
  hp: 30,
  attack: 42,
  defense: 118,
  sp_attack: 42,
  sp_defense: 88,
  speed: 30,
  type_1: Type.find_by(name: 'Rock'),
  type_2: Type.find_by(name: 'Steel'),
  ability_1: Ability.find_by(name: 'sturdy'),
  hidden_ability: Ability.find_by(name: 'soundproof')
)

Pokemon.create!(
  id: 411,
  name: 'Bastiodon',
  classification: 'Shield',
  height: 1.3,
  weight: 149.5,
  capture_rate: 45,
  base_egg_steps: 7680,
  male_gender_ratio: 87.5,
  experience_growth: 600_000,
  base_happiness: 70,
  hp: 60,
  attack: 52,
  defense: 168,
  sp_attack: 47,
  sp_defense: 138,
  speed: 30,
  type_1: Type.find_by(name: 'Rock'),
  type_2: Type.find_by(name: 'Steel'),
  ability_1: Ability.find_by(name: 'sturdy'),
  hidden_ability: Ability.find_by(name: 'soundproof')
)

Pokemon.create!(
  id: 412,
  name: 'Burmy',
  classification: 'Bagworm',
  height: 0.2,
  weight: 3.4,
  capture_rate: 120,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 40,
  attack: 29,
  defense: 45,
  sp_attack: 29,
  sp_defense: 45,
  speed: 36,
  type_1: Type.find_by(name: 'Bug'),
  ability_1: Ability.find_by(name: 'shed_skin'),
  ability_2: Ability.find_by(name: 'overcoat'),
  hidden_ability: Ability.find_by(name: 'powder_moves')
)

Pokemon.create!(
  id: 413,
  name: 'Wormadam',
  classification: 'Bagworm',
  height: 0.5,
  weight: 6.5,
  capture_rate: 45,
  base_egg_steps: 3840,
  male_gender_ratio: 0,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 60,
  attack: 59,
  defense: 85,
  sp_attack: 79,
  sp_defense: 105,
  speed: 36,
  type_1: Type.find_by(name: 'Bug'),
  ability_1: Ability.find_by(name: 'anticipation'),
  ability_2: Ability.find_by(name: 'overcoat'),
  hidden_ability: Ability.find_by(name: 'powder_moves')
)

Pokemon.create!(
  id: 414,
  name: 'Mothim',
  classification: 'Moth',
  height: 0.9,
  weight: 23.3,
  capture_rate: 45,
  base_egg_steps: 3840,
  male_gender_ratio: 100,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 70,
  attack: 94,
  defense: 50,
  sp_attack: 94,
  sp_defense: 50,
  speed: 66,
  type_1: Type.find_by(name: 'Bug'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'swarm'),
  hidden_ability: Ability.find_by(name: 'tinted_lens')
)

Pokemon.create!(
  id: 415,
  name: 'Combee',
  classification: 'Tiny Bee',
  height: 0.3,
  weight: 5.5,
  capture_rate: 120,
  base_egg_steps: 3840,
  male_gender_ratio: 87.5,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 30,
  attack: 30,
  defense: 42,
  sp_attack: 30,
  sp_defense: 42,
  speed: 70,
  type_1: Type.find_by(name: 'Bug'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'honey_gather'),
  hidden_ability: Ability.find_by(name: 'hustle')
)

Pokemon.create!(
  id: 416,
  name: 'Vespiquen',
  classification: 'Beehive',
  height: 1.2,
  weight: 38.5,
  capture_rate: 45,
  base_egg_steps: 3840,
  male_gender_ratio: 0,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 70,
  attack: 80,
  defense: 102,
  sp_attack: 80,
  sp_defense: 102,
  speed: 40,
  type_1: Type.find_by(name: 'Bug'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'pressure'),
  hidden_ability: Ability.find_by(name: 'unnerve')
)

Pokemon.create!(
  id: 417,
  name: 'Pachirisu',
  classification: 'EleSquirrel',
  height: 0.4,
  weight: 3.9,
  capture_rate: 200,
  base_egg_steps: 2560,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 100,
  hp: 60,
  attack: 45,
  defense: 70,
  sp_attack: 45,
  sp_defense: 90,
  speed: 95,
  type_1: Type.find_by(name: 'Electric'),
  ability_1: Ability.find_by(name: 'run_away'),
  ability_2: Ability.find_by(name: 'pickup'),
  hidden_ability: Ability.find_by(name: 'volt_absorb')
)

Pokemon.create!(
  id: 418,
  name: 'Buizel',
  classification: 'Sea Weasel',
  height: 0.7,
  weight: 29.5,
  capture_rate: 190,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 55,
  attack: 65,
  defense: 35,
  sp_attack: 60,
  sp_defense: 30,
  speed: 85,
  type_1: Type.find_by(name: 'Water'),
  ability_1: Ability.find_by(name: 'swift_swim'),
  hidden_ability: Ability.find_by(name: 'water_veil')
)

Pokemon.create!(
  id: 419,
  name: 'Floatzel',
  classification: 'Sea Weasel',
  height: 1.1,
  weight: 33.5,
  capture_rate: 75,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 85,
  attack: 105,
  defense: 55,
  sp_attack: 85,
  sp_defense: 50,
  speed: 115,
  type_1: Type.find_by(name: 'Water'),
  ability_1: Ability.find_by(name: 'swift_swim'),
  hidden_ability: Ability.find_by(name: 'water_veil')
)

Pokemon.create!(
  id: 420,
  name: 'Cherubi',
  classification: 'Cherry',
  height: 0.4,
  weight: 3.3,
  capture_rate: 190,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 45,
  attack: 35,
  defense: 45,
  sp_attack: 62,
  sp_defense: 53,
  speed: 35,
  type_1: Type.find_by(name: 'Grass'),
  ability_1: Ability.find_by(name: 'chlorophyll')
)
