Pokemon.create!(
  id: 421,
  name: 'Cherrim',
  classification: 'Blossom',
  height: 0.5,
  weight: 9.3,
  capture_rate: 75,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 70,
  attack: 60,
  defense: 70,
  sp_attack: 87,
  sp_defense: 78,
  speed: 85,
  type_1: Type.find_by(name: 'Grass'),
  ability_1: Ability.find_by(name: 'flower_gift')
)

Pokemon.create!(
  id: 422,
  name: 'Shellos',
  classification: 'Sea Slug',
  height: 0.3,
  weight: 6.3,
  capture_rate: 190,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 76,
  attack: 48,
  defense: 48,
  sp_attack: 57,
  sp_defense: 62,
  speed: 34,
  type_1: Type.find_by(name: 'Water'),
  ability_1: Ability.find_by(name: 'sticky_hold'),
  ability_2: Ability.find_by(name: 'storm_drain'),
  hidden_ability: Ability.find_by(name: 'sand_force')
)

Pokemon.create!(
  id: 423,
  name: 'Gastrodon',
  classification: 'Sea Slug',
  height: 0.9,
  weight: 29.9,
  capture_rate: 75,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 111,
  attack: 83,
  defense: 68,
  sp_attack: 92,
  sp_defense: 82,
  speed: 39,
  type_1: Type.find_by(name: 'Water'),
  type_2: Type.find_by(name: 'Ground'),
  ability_1: Ability.find_by(name: 'sticky_hold'),
  ability_2: Ability.find_by(name: 'storm_drain'),
  hidden_ability: Ability.find_by(name: 'sand_force')
)

Pokemon.create!(
  id: 424,
  name: 'Ambipom',
  classification: 'Long Tail',
  height: 1.2,
  weight: 20.3,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 800_000,
  base_happiness: 100,
  hp: 75,
  attack: 100,
  defense: 66,
  sp_attack: 60,
  sp_defense: 66,
  speed: 115,
  type_1: Type.find_by(name: 'Normal'),
  ability_1: Ability.find_by(name: 'technician'),
  ability_2: Ability.find_by(name: 'pickup'),
  hidden_ability: Ability.find_by(name: 'skill_link')
)

Pokemon.create!(
  id: 425,
  name: 'Drifloon',
  classification: 'Balloon',
  height: 0.4,
  weight: 1.2,
  capture_rate: 125,
  base_egg_steps: 7680,
  male_gender_ratio: 50,
  experience_growth: 1_640_000,
  base_happiness: 70,
  hp: 90,
  attack: 50,
  defense: 34,
  sp_attack: 60,
  sp_defense: 44,
  speed: 70,
  type_1: Type.find_by(name: 'Ghost'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'aftermath'),
  ability_2: Ability.find_by(name: 'unburden'),
  hidden_ability: Ability.find_by(name: 'flare_boost')
)

Pokemon.create!(
  id: 426,
  name: 'Drifblim',
  classification: 'Blimp',
  height: 1.2,
  weight: 15.0,
  capture_rate: 60,
  base_egg_steps: 7680,
  male_gender_ratio: 50,
  experience_growth: 1_640_000,
  base_happiness: 70,
  hp: 150,
  attack: 80,
  defense: 44,
  sp_attack: 90,
  sp_defense: 54,
  speed: 80,
  type_1: Type.find_by(name: 'Ghost'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'aftermath'),
  ability_2: Ability.find_by(name: 'unburden'),
  hidden_ability: Ability.find_by(name: 'flare_boost')
)

Pokemon.create!(
  id: 427,
  name: 'Buneary',
  classification: 'Rabbit',
  height: 0.4,
  weight: 5.5,
  capture_rate: 190,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 0,
  hp: 55,
  attack: 66,
  defense: 44,
  sp_attack: 44,
  sp_defense: 56,
  speed: 85,
  type_1: Type.find_by(name: 'Normal'),
  ability_1: Ability.find_by(name: 'run_away'),
  ability_2: Ability.find_by(name: 'klutz'),
  hidden_ability: Ability.find_by(name: 'limber')
)

Pokemon.create!(
  id: 428,
  name: 'Lopunny',
  classification: 'Rabbit',
  height: 1.2,
  weight: 33.3,
  capture_rate: 60,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 140,
  hp: 65,
  attack: 76,
  defense: 84,
  sp_attack: 54,
  sp_defense: 96,
  speed: 105,
  type_1: Type.find_by(name: 'Normal'),
  ability_1: Ability.find_by(name: 'cute_charm'),
  ability_2: Ability.find_by(name: 'klutz'),
  hidden_ability: Ability.find_by(name: 'limber')
)

Pokemon.create!(
  id: 429,
  name: 'Mismagius',
  classification: 'Magical',
  height: 0.9,
  weight: 4.4,
  capture_rate: 45,
  base_egg_steps: 6400,
  male_gender_ratio: 50,
  experience_growth: 800_000,
  base_happiness: 35,
  hp: 60,
  attack: 60,
  defense: 60,
  sp_attack: 105,
  sp_defense: 105,
  speed: 105,
  type_1: Type.find_by(name: 'Ghost'),
  ability_1: Ability.find_by(name: 'levitate')
)

Pokemon.create!(
  id: 430,
  name: 'Honchkrow',
  classification: 'Big Boss',
  height: 0.9,
  weight: 27.3,
  capture_rate: 30,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 35,
  hp: 100,
  attack: 125,
  defense: 52,
  sp_attack: 105,
  sp_defense: 52,
  speed: 71,
  type_1: Type.find_by(name: 'Dark'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'insomnia'),
  ability_2: Ability.find_by(name: 'super_luck'),
  hidden_ability: Ability.find_by(name: 'moxie')
)

Pokemon.create!(
  id: 431,
  name: 'Glameow',
  classification: 'Catty',
  height: 0.5,
  weight: 3.9,
  capture_rate: 190,
  base_egg_steps: 5120,
  male_gender_ratio: 25,
  experience_growth: 800_000,
  base_happiness: 70,
  hp: 49,
  attack: 55,
  defense: 42,
  sp_attack: 42,
  sp_defense: 37,
  speed: 85,
  type_1: Type.find_by(name: 'Normal'),
  ability_1: Ability.find_by(name: 'limber'),
  ability_2: Ability.find_by(name: 'own_tempo'),
  hidden_ability: Ability.find_by(name: 'keen_eye')
)

Pokemon.create!(
  id: 432,
  name: 'Purugly',
  classification: 'Tiger Cat',
  height: 1.0,
  weight: 43.8,
  capture_rate: 75,
  base_egg_steps: 5120,
  male_gender_ratio: 25,
  experience_growth: 800_000,
  base_happiness: 70,
  hp: 71,
  attack: 82,
  defense: 64,
  sp_attack: 64,
  sp_defense: 59,
  speed: 112,
  type_1: Type.find_by(name: 'Normal'),
  ability_1: Ability.find_by(name: 'thick_fat'),
  ability_2: Ability.find_by(name: 'own_tempo'),
  hidden_ability: Ability.find_by(name: 'defiant')
)

Pokemon.create!(
  id: 433,
  name: 'Chingling',
  classification: 'Bell',
  height: 0.2,
  weight: 0.6,
  capture_rate: 120,
  base_egg_steps: 6400,
  male_gender_ratio: 50,
  experience_growth: 800_000,
  base_happiness: 70,
  hp: 45,
  attack: 30,
  defense: 50,
  sp_attack: 65,
  sp_defense: 50,
  speed: 45,
  type_1: Type.find_by(name: 'Psychic'),
  ability_1: Ability.find_by(name: 'levitate')
)

Pokemon.create!(
  id: 434,
  name: 'Stunky',
  classification: 'Skunk',
  height: 0.4,
  weight: 19.2,
  capture_rate: 225,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 63,
  attack: 63,
  defense: 47,
  sp_attack: 41,
  sp_defense: 41,
  speed: 74,
  type_1: Type.find_by(name: 'Poison'),
  type_2: Type.find_by(name: 'Dark'),
  ability_1: Ability.find_by(name: 'stench'),
  ability_2: Ability.find_by(name: 'aftermath'),
  hidden_ability: Ability.find_by(name: 'keen_eye')
)

Pokemon.create!(
  id: 435,
  name: 'Skuntank',
  classification: 'Skunk',
  height: 1.0,
  weight: 38.0,
  capture_rate: 60,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 103,
  attack: 93,
  defense: 67,
  sp_attack: 71,
  sp_defense: 61,
  speed: 84,
  type_1: Type.find_by(name: 'Poison'),
  type_2: Type.find_by(name: 'Dark'),
  ability_1: Ability.find_by(name: 'stench'),
  ability_2: Ability.find_by(name: 'aftermath'),
  hidden_ability: Ability.find_by(name: 'keen_eye')
)

Pokemon.create!(
  id: 436,
  name: 'Bronzor',
  classification: 'Bronze',
  height: 0.5,
  weight: 60.5,
  capture_rate: 255,
  base_egg_steps: 5120,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 57,
  attack: 24,
  defense: 86,
  sp_attack: 24,
  sp_defense: 86,
  speed: 23,
  type_1: Type.find_by(name: 'Steel'),
  type_2: Type.find_by(name: 'Psychic'),
  ability_1: Ability.find_by(name: 'levitate'),
  ability_2: Ability.find_by(name: 'heatproof'),
  hidden_ability: Ability.find_by(name: 'heavy_metal')
)

Pokemon.create!(
  id: 437,
  name: 'Bronzong',
  classification: 'Bronze Bell',
  height: 1.3,
  weight: 187.0,
  capture_rate: 90,
  base_egg_steps: 5120,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 67,
  attack: 89,
  defense: 116,
  sp_attack: 79,
  sp_defense: 116,
  speed: 33,
  type_1: Type.find_by(name: 'Steel'),
  type_2: Type.find_by(name: 'Psychic'),
  ability_1: Ability.find_by(name: 'levitate'),
  ability_2: Ability.find_by(name: 'heatproof'),
  hidden_ability: Ability.find_by(name: 'heavy_metal')
)

Pokemon.create!(
  id: 438,
  name: 'Bonsly',
  classification: 'Bonsai',
  height: 0.5,
  weight: 15.0,
  capture_rate: 255,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 50,
  attack: 80,
  defense: 95,
  sp_attack: 10,
  sp_defense: 45,
  speed: 10,
  type_1: Type.find_by(name: 'Rock'),
  ability_1: Ability.find_by(name: 'sturdy'),
  ability_2: Ability.find_by(name: 'rock_head'),
  hidden_ability: Ability.find_by(name: 'rattled')
)

Pokemon.create!(
  id: 439,
  name: 'Mime Jr.',
  classification: 'Mime',
  height: 0.6,
  weight: 13.0,
  capture_rate: 145,
  base_egg_steps: 6400,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 20,
  attack: 25,
  defense: 45,
  sp_attack: 70,
  sp_defense: 90,
  speed: 60,
  type_1: Type.find_by(name: 'Psychic'),
  type_2: Type.find_by(name: 'Fairy'),
  ability_1: Ability.find_by(name: 'soundproof'),
  ability_2: Ability.find_by(name: 'filter'),
  hidden_ability: Ability.find_by(name: 'technician')
)

Pokemon.create!(
  id: 440,
  name: 'Happiny',
  classification: 'Playhouse',
  height: 0.6,
  weight: 24.4,
  capture_rate: 130,
  base_egg_steps: 10_240,
  male_gender_ratio: 0,
  experience_growth: 800_000,
  base_happiness: 140,
  hp: 100,
  attack: 5,
  defense: 5,
  sp_attack: 15,
  sp_defense: 65,
  speed: 30,
  type_1: Type.find_by(name: 'Normal'),
  ability_1: Ability.find_by(name: 'natural_cure'),
  ability_2: Ability.find_by(name: 'serene_grace'),
  hidden_ability: Ability.find_by(name: 'friend_guard')
)
