Pokemon.create!(
  id: 461,
  name: 'Weavile',
  classification: 'Sharp Claw',
  height: 1.1,
  weight: 34.0,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 35,
  hp: 70,
  attack: 120,
  defense: 65,
  sp_attack: 45,
  sp_defense: 85,
  speed: 125,
  type_1: Type.find_by(name: 'Dark'),
  type_2: Type.find_by(name: 'Ice'),
  ability_1: Ability.find_by(name: 'pressure'),
  hidden_ability: Ability.find_by(name: 'pickpocket'),
)

Pokemon.create!(
  id: 462,
  name: 'Magnezone',
  classification: 'Magnet Area',
  height: 1.2,
  weight: 180.0,
  capture_rate: 30,
  base_egg_steps: 5120,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 70,
  attack: 70,
  defense: 115,
  sp_attack: 130,
  sp_defense: 90,
  speed: 60,
  type_1: Type.find_by(name: 'Electric'),
  type_2: Type.find_by(name: 'Steel'),
  ability_1: Ability.find_by(name: 'magnet_pull'),
  ability_2: Ability.find_by(name: 'sturdy'),
  hidden_ability: Ability.find_by(name: 'analytic'),
)

Pokemon.create!(
  id: 463,
  name: 'Lickilicky',
  classification: 'Licking',
  height: 1.7,
  weight: 140.0,
  capture_rate: 30,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 110,
  attack: 85,
  defense: 95,
  sp_attack: 80,
  sp_defense: 95,
  speed: 50,
  type_1: Type.find_by(name: 'Normal'),
  ability_1: Ability.find_by(name: 'own_tempo'),
  ability_2: Ability.find_by(name: 'oblivious'),
  hidden_ability: Ability.find_by(name: 'cloud_nine'),
)

Pokemon.create!(
  id: 464,
  name: 'Rhyperior',
  classification: 'Drill',
  height: 2.4,
  weight: 282.8,
  capture_rate: 30,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_250_000,
  base_happiness: 70,
  hp: 115,
  attack: 140,
  defense: 130,
  sp_attack: 55,
  sp_defense: 55,
  speed: 40,
  type_1: Type.find_by(name: 'Ground'),
  type_2: Type.find_by(name: 'Rock'),
  ability_1: Ability.find_by(name: 'lightningrod'),
  ability_2: Ability.find_by(name: 'solid_rock'),
  hidden_ability: Ability.find_by(name: 'reckless'),
)

Pokemon.create!(
  id: 465,
  name: 'Tangrowth',
  classification: 'Vine',
  height: 2.0,
  weight: 128.6,
  capture_rate: 30,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 100,
  attack: 100,
  defense: 125,
  sp_attack: 110,
  sp_defense: 50,
  speed: 50,
  type_1: Type.find_by(name: 'Grass'),
  ability_1: Ability.find_by(name: 'chlorophyll'),
  ability_2: Ability.find_by(name: 'leaf_guard'),
  hidden_ability: Ability.find_by(name: 'regenerator'),
)

Pokemon.create!(
  id: 466,
  name: 'Electivire',
  classification: 'Thunderbolt',
  height: 1.8,
  weight: 138.6,
  capture_rate: 30,
  base_egg_steps: 6400,
  male_gender_ratio: 75,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 75,
  attack: 123,
  defense: 67,
  sp_attack: 95,
  sp_defense: 85,
  speed: 95,
  type_1: Type.find_by(name: 'Electric'),
  ability_1: Ability.find_by(name: 'motor_drive'),
  hidden_ability: Ability.find_by(name: 'vital_spirit'),
)

Pokemon.create!(
  id: 467,
  name: 'Magmortar',
  classification: 'Blast',
  height: 1.6,
  weight: 68.0,
  capture_rate: 30,
  base_egg_steps: 6400,
  male_gender_ratio: 75,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 75,
  attack: 95,
  defense: 67,
  sp_attack: 125,
  sp_defense: 95,
  speed: 83,
  type_1: Type.find_by(name: 'Fire'),
  ability_1: Ability.find_by(name: 'flame_body'),
  hidden_ability: Ability.find_by(name: 'vital_spirit'),
)

Pokemon.create!(
  id: 468,
  name: 'Togekiss',
  classification: 'Jubilee',
  height: 1.5,
  weight: 38.0,
  capture_rate: 30,
  base_egg_steps: 2560,
  male_gender_ratio: 87.5,
  experience_growth: 800_000,
  base_happiness: 70,
  hp: 85,
  attack: 50,
  defense: 95,
  sp_attack: 120,
  sp_defense: 115,
  speed: 80,
  type_1: Type.find_by(name: 'Fairy'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'hustle'),
  ability_2: Ability.find_by(name: 'serene_grace'),
  hidden_ability: Ability.find_by(name: 'super_luck'),
)

Pokemon.create!(
  id: 469,
  name: 'Yanmega',
  classification: 'Ogre Darner',
  height: 1.9,
  weight: 51.5,
  capture_rate: 30,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 86,
  attack: 76,
  defense: 86,
  sp_attack: 116,
  sp_defense: 56,
  speed: 95,
  type_1: Type.find_by(name: 'Bug'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'speed_boost'),
  ability_2: Ability.find_by(name: 'tinted_lens'),
  hidden_ability: Ability.find_by(name: 'frisk'),
)

Pokemon.create!(
  id: 470,
  name: 'Leafeon',
  classification: 'Verdant',
  height: 1.0,
  weight: 25.5,
  capture_rate: 45,
  base_egg_steps: 8960,
  male_gender_ratio: 87.5,
  experience_growth: 1_000_000,
  base_happiness: 35,
  hp: 65,
  attack: 110,
  defense: 130,
  sp_attack: 60,
  sp_defense: 65,
  speed: 95,
  type_1: Type.find_by(name: 'Grass'),
  ability_1: Ability.find_by(name: 'leaf_guard'),
  hidden_ability: Ability.find_by(name: 'chlorophyll'),
)

Pokemon.create!(
  id: 471,
  name: 'Glaceon',
  classification: 'Fresh Snow',
  height: 0.8,
  weight: 25.9,
  capture_rate: 45,
  base_egg_steps: 8960,
  male_gender_ratio: 87.5,
  experience_growth: 1_000_000,
  base_happiness: 35,
  hp: 65,
  attack: 60,
  defense: 110,
  sp_attack: 130,
  sp_defense: 95,
  speed: 65,
  type_1: Type.find_by(name: 'Ice'),
  ability_1: Ability.find_by(name: 'snow_cloak'),
  hidden_ability: Ability.find_by(name: 'ice_body'),
)

Pokemon.create!(
  id: 472,
  name: 'Gliscor',
  classification: 'Fang Scorp',
  height: 2.0,
  weight: 42.5,
  capture_rate: 30,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 75,
  attack: 95,
  defense: 125,
  sp_attack: 45,
  sp_defense: 75,
  speed: 95,
  type_1: Type.find_by(name: 'Ground'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'hyper_cutter'),
  ability_2: Ability.find_by(name: 'sand_veil'),
  hidden_ability: Ability.find_by(name: 'poison_heal'),
)

Pokemon.create!(
  id: 473,
  name: 'Mamoswine',
  classification: 'Twin Tusk',
  height: 2.5,
  weight: 291.0,
  capture_rate: 50,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_250_000,
  base_happiness: 70,
  hp: 110,
  attack: 130,
  defense: 80,
  sp_attack: 70,
  sp_defense: 60,
  speed: 80,
  type_1: Type.find_by(name: 'Ice'),
  type_2: Type.find_by(name: 'Ground'),
  ability_1: Ability.find_by(name: 'oblivious'),
  ability_2: Ability.find_by(name: 'snow_cloak'),
  hidden_ability: Ability.find_by(name: 'thick_fat'),
)

Pokemon.create!(
  id: 474,
  name: 'Porygon-Z',
  classification: 'Virtual',
  height: 0.9,
  weight: 34.0,
  capture_rate: 30,
  base_egg_steps: 5120,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 85,
  attack: 80,
  defense: 70,
  sp_attack: 135,
  sp_defense: 75,
  speed: 90,
  type_1: Type.find_by(name: 'Normal'),
  ability_1: Ability.find_by(name: 'adaptability'),
  ability_2: Ability.find_by(name: 'download'),
  hidden_ability: Ability.find_by(name: 'analytic'),
)

Pokemon.create!(
  id: 475,
  name: 'Gallade',
  classification: 'Blade',
  height: 1.6,
  weight: 52.0,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 100,
  experience_growth: 1_250_000,
  base_happiness: 35,
  hp: 68,
  attack: 125,
  defense: 65,
  sp_attack: 65,
  sp_defense: 115,
  speed: 80,
  type_1: Type.find_by(name: 'Psychic'),
  type_2: Type.find_by(name: 'Fighting'),
  ability_1: Ability.find_by(name: 'steadfast'),
  hidden_ability: Ability.find_by(name: 'justified'),
)

Pokemon.create!(
  id: 476,
  name: 'Probopass',
  classification: 'Compass',
  height: 1.4,
  weight: 340.0,
  capture_rate: 60,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 60,
  attack: 55,
  defense: 145,
  sp_attack: 75,
  sp_defense: 150,
  speed: 40,
  type_1: Type.find_by(name: 'Rock'),
  type_2: Type.find_by(name: 'Steel'),
  ability_1: Ability.find_by(name: 'sturdy'),
  ability_2: Ability.find_by(name: 'magnet_pull'),
  hidden_ability: Ability.find_by(name: 'sand_force'),
)

Pokemon.create!(
  id: 477,
  name: 'Dusknoir',
  classification: 'Gripper',
  height: 2.2,
  weight: 106.6,
  capture_rate: 45,
  base_egg_steps: 6400,
  male_gender_ratio: 50,
  experience_growth: 800_000,
  base_happiness: 35,
  hp: 45,
  attack: 100,
  defense: 135,
  sp_attack: 65,
  sp_defense: 135,
  speed: 45,
  type_1: Type.find_by(name: 'Ghost'),
  ability_1: Ability.find_by(name: 'pressure'),
  hidden_ability: Ability.find_by(name: 'frisk'),
)

Pokemon.create!(
  id: 478,
  name: 'Froslass',
  classification: 'Snow Land',
  height: 1.3,
  weight: 26.6,
  capture_rate: 75,
  base_egg_steps: 5120,
  male_gender_ratio: 0,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 70,
  attack: 80,
  defense: 70,
  sp_attack: 80,
  sp_defense: 70,
  speed: 110,
  type_1: Type.find_by(name: 'Ice'),
  type_2: Type.find_by(name: 'Ghost'),
  ability_1: Ability.find_by(name: 'snow_cloak'),
  hidden_ability: Ability.find_by(name: 'cursed_body'),
)

Pokemon.create!(
  id: 479,
  name: 'Rotom',
  classification: 'Plasma',
  height: 0.3,
  weight: 0.3,
  capture_rate: 45,
  base_egg_steps: 5120,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 50,
  attack: 50,
  defense: 77,
  sp_attack: 95,
  sp_defense: 77,
  speed: 91,
  type_1: Type.find_by(name: 'Electric'),
  ability_1: Ability.find_by(name: 'levitate'),
)

Pokemon.create!(
  id: 480,
  name: 'Uxie',
  classification: 'Knowledge',
  height: 0.3,
  weight: 0.3,
  capture_rate: 3,
  base_egg_steps: 20480,
  experience_growth: 1_250_000,
  base_happiness: 140,
  hp: 75,
  attack: 75,
  defense: 130,
  sp_attack: 75,
  sp_defense: 130,
  speed: 95,
  type_1: Type.find_by(name: 'Psychic'),
  ability_1: Ability.find_by(name: 'levitate'),
)
