Pokemon.create!(
  id: 481,
  name: 'Mesprit',
  classification: 'Emotion',
  height: 0.3,
  weight: 0.3,
  capture_rate: 3,
  base_egg_steps: 20480,
  experience_growth: 1_250_000,
  base_happiness: 140,
  hp: 80,
  attack: 105,
  defense: 105,
  sp_attack: 105,
  sp_defense: 105,
  speed: 80,
  type_1: Type.find_by(name: 'Psychic'),
  ability_1: Ability.find_by(name: 'levitate'),
)

Pokemon.create!(
  id: 482,
  name: 'Azelf',
  classification: 'Willpower',
  height: 0.3,
  weight: 0.3,
  capture_rate: 3,
  base_egg_steps: 20480,
  experience_growth: 1_250_000,
  base_happiness: 140,
  hp: 75,
  attack: 125,
  defense: 70,
  sp_attack: 125,
  sp_defense: 70,
  speed: 115,
  type_1: Type.find_by(name: 'Psychic'),
  ability_1: Ability.find_by(name: 'levitate'),
)

Pokemon.create!(
  id: 483,
  name: 'Dialga',
  classification: 'Temporal',
  height: 5.4,
  weight: 683.0,
  capture_rate: 3,
  base_egg_steps: 30720,
  experience_growth: 1_250_000,
  base_happiness: 0,
  hp: 100,
  attack: 120,
  defense: 120,
  sp_attack: 150,
  sp_defense: 100,
  speed: 90,
  type_1: Type.find_by(name: 'Steel'),
  type_2: Type.find_by(name: 'Dragon'),
  ability_1: Ability.find_by(name: 'pressure'),
  hidden_ability: Ability.find_by(name: 'telepathy'),
)

Pokemon.create!(
  id: 484,
  name: 'Palkia',
  classification: 'Spatial',
  height: 4.2,
  weight: 336.0,
  capture_rate: 3,
  base_egg_steps: 30720,
  experience_growth: 1_250_000,
  base_happiness: 0,
  hp: 90,
  attack: 120,
  defense: 100,
  sp_attack: 150,
  sp_defense: 120,
  speed: 100,
  type_1: Type.find_by(name: 'Water'),
  type_2: Type.find_by(name: 'Dragon'),
  ability_1: Ability.find_by(name: 'pressure'),
  hidden_ability: Ability.find_by(name: 'telepathy'),
)

Pokemon.create!(
  id: 485,
  name: 'Heatran',
  classification: 'Lava Dome',
  height: 1.7,
  weight: 430.0,
  capture_rate: 3,
  base_egg_steps: 2560,
  male_gender_ratio: 50,
  experience_growth: 1_250_000,
  base_happiness: 100,
  hp: 91,
  attack: 90,
  defense: 106,
  sp_attack: 130,
  sp_defense: 106,
  speed: 77,
  type_1: Type.find_by(name: 'Fire'),
  type_2: Type.find_by(name: 'Steel'),
  ability_1: Ability.find_by(name: 'flash_fire'),
  hidden_ability: Ability.find_by(name: 'flame_body'),
)

Pokemon.create!(
  id: 486,
  name: 'Regigigas',
  classification: 'Colossal',
  height: 3.7,
  weight: 420.0,
  capture_rate: 3,
  base_egg_steps: 30720,
  experience_growth: 1_250_000,
  base_happiness: 0,
  hp: 110,
  attack: 160,
  defense: 110,
  sp_attack: 80,
  sp_defense: 110,
  speed: 100,
  type_1: Type.find_by(name: 'Normal'),
  ability_1: Ability.find_by(name: 'slow_start'),
)

Pokemon.create!(
  id: 487,
  name: 'Giratina',
  classification: 'Renegade',
  height: 4.5,
  weight: 750.0,
  capture_rate: 3,
  base_egg_steps: 30720,
  experience_growth: 1_250_000,
  base_happiness: 0,
  hp: 150,
  attack: 100,
  defense: 120,
  sp_attack: 100,
  sp_defense: 120,
  speed: 90,
  type_1: Type.find_by(name: 'Ghost'),
  type_2: Type.find_by(name: 'Dragon'),
  ability_1: Ability.find_by(name: 'pressure'),
  ability_2: Ability.find_by(name: 'telepathy'),
  hidden_ability: Ability.find_by(name: 'levitate'),
)

Pokemon.create!(
  id: 488,
  name: 'Cresselia',
  classification: 'Lunar',
  height: 1.5,
  weight: 85.6,
  capture_rate: 3,
  base_egg_steps: 30720,
  male_gender_ratio: 0,
  experience_growth: 1_250_000,
  base_happiness: 100,
  hp: 120,
  attack: 70,
  defense: 120,
  sp_attack: 75,
  sp_defense: 130,
  speed: 85,
  type_1: Type.find_by(name: 'Psychic'),
  ability_1: Ability.find_by(name: 'levitate'),
)

Pokemon.create!(
  id: 489,
  name: 'Phione',
  classification: 'Sea Drifter',
  height: 0.4,
  weight: 3.1,
  capture_rate: 30,
  base_egg_steps: 10240,
  experience_growth: 1_250_000,
  base_happiness: 70,
  hp: 80,
  attack: 80,
  defense: 80,
  sp_attack: 80,
  sp_defense: 80,
  speed: 80,
  type_1: Type.find_by(name: 'Water'),
  ability_1: Ability.find_by(name: 'hydration'),
)

Pokemon.create!(
  id: 490,
  name: 'Manaphy',
  classification: 'Seafaring',
  height: 0.3,
  weight: 1.4,
  capture_rate: 3,
  base_egg_steps: 2560,
  experience_growth: 1_250_000,
  base_happiness: 70,
  hp: 100,
  attack: 100,
  defense: 100,
  sp_attack: 100,
  sp_defense: 100,
  speed: 100,
  type_1: Type.find_by(name: 'Water'),
  ability_1: Ability.find_by(name: 'hydration'),
)

Pokemon.create!(
  id: 491,
  name: 'Darkrai',
  classification: 'Pitch-Black',
  height: 1.5,
  weight: 50.5,
  capture_rate: 3,
  base_egg_steps: 30720,
  experience_growth: 1_250_000,
  base_happiness: 0,
  hp: 70,
  attack: 90,
  defense: 90,
  sp_attack: 135,
  sp_defense: 90,
  speed: 125,
  type_1: Type.find_by(name: 'Dark'),
  ability_1: Ability.find_by(name: 'bad_dreams'),
)

Pokemon.create!(
  id: 492,
  name: 'Shaymin',
  classification: 'Gratitude',
  height: 0.2,
  weight: 2.1,
  capture_rate: 45,
  base_egg_steps: 30720,
  experience_growth: 1_059_860,
  base_happiness: 100,
  hp: 100,
  attack: 100,
  defense: 100,
  sp_attack: 100,
  sp_defense: 100,
  speed: 100,
  type_1: Type.find_by(name: 'Grass'),
  ability_1: Ability.find_by(name: 'natural_cure'),
  hidden_ability: Ability.find_by(name: 'serene_grace'),
)

Pokemon.create!(
  id: 493,
  name: 'Arceus',
  classification: 'Alpha',
  height: 3.2,
  weight: 320.0,
  capture_rate: 3,
  base_egg_steps: 30720,
  experience_growth: 1_250_000,
  base_happiness: 0,
  hp: 120,
  attack: 120,
  defense: 120,
  sp_attack: 120,
  sp_defense: 120,
  speed: 120,
  type_1: Type.find_by(name: 'Normal'),
  ability_1: Ability.find_by(name: 'multitype'),
)

Pokemon.create!(
  id: 494,
  name: 'Victini',
  classification: 'Victory',
  height: 0.4,
  weight: 4.0,
  capture_rate: 3,
  base_egg_steps: 30720,
  experience_growth: 1_250_000,
  base_happiness: 100,
  hp: 100,
  attack: 100,
  defense: 100,
  sp_attack: 100,
  sp_defense: 100,
  speed: 100,
  type_1: Type.find_by(name: 'Psychic'),
  type_2: Type.find_by(name: 'Fire'),
  ability_1: Ability.find_by(name: 'victory_star'),
)

Pokemon.create!(
  id: 495,
  name: 'Snivy',
  classification: 'Grass Snake',
  height: 0.6,
  weight: 8.1,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 87.5,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 45,
  attack: 45,
  defense: 55,
  sp_attack: 45,
  sp_defense: 55,
  speed: 63,
  type_1: Type.find_by(name: 'Grass'),
  ability_1: Ability.find_by(name: 'overgrow'),
  hidden_ability: Ability.find_by(name: 'contrary'),
)

Pokemon.create!(
  id: 496,
  name: 'Servine',
  classification: 'Grass Snake',
  height: 0.8,
  weight: 16.0,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 87.5,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 60,
  attack: 60,
  defense: 75,
  sp_attack: 60,
  sp_defense: 75,
  speed: 83,
  type_1: Type.find_by(name: 'Grass'),
  ability_1: Ability.find_by(name: 'overgrow'),
  hidden_ability: Ability.find_by(name: 'contrary'),
)

Pokemon.create!(
  id: 497,
  name: 'Serperior',
  classification: 'Regal',
  height: 3.3,
  weight: 63.0,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 87.5,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 75,
  attack: 75,
  defense: 95,
  sp_attack: 75,
  sp_defense: 95,
  speed: 113,
  type_1: Type.find_by(name: 'Grass'),
  ability_1: Ability.find_by(name: 'overgrow'),
  hidden_ability: Ability.find_by(name: 'contrary'),
)

Pokemon.create!(
  id: 498,
  name: 'Tepig',
  classification: 'Fire Pig',
  height: 0.5,
  weight: 9.9,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 87.5,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 65,
  attack: 63,
  defense: 45,
  sp_attack: 45,
  sp_defense: 45,
  speed: 45,
  type_1: Type.find_by(name: 'Fire'),
  ability_1: Ability.find_by(name: 'blaze'),
  hidden_ability: Ability.find_by(name: 'thick_fat'),
)

Pokemon.create!(
  id: 499,
  name: 'Pignite',
  classification: 'Fire Pig',
  height: 1.0,
  weight: 55.5,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 87.5,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 90,
  attack: 93,
  defense: 55,
  sp_attack: 70,
  sp_defense: 55,
  speed: 55,
  type_1: Type.find_by(name: 'Fire'),
  type_2: Type.find_by(name: 'Fighting'),
  ability_1: Ability.find_by(name: 'blaze'),
  hidden_ability: Ability.find_by(name: 'thick_fat'),
)

Pokemon.create!(
  id: 500,
  name: 'Emboar',
  classification: 'Mega Fire Pig',
  height: 1.6,
  weight: 150.0,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 87.5,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 110,
  attack: 123,
  defense: 65,
  sp_attack: 100,
  sp_defense: 65,
  speed: 65,
  type_1: Type.find_by(name: 'Fire'),
  type_2: Type.find_by(name: 'Fighting'),
  ability_1: Ability.find_by(name: 'blaze'),
  hidden_ability: Ability.find_by(name: 'reckless'),
)
