Pokemon.create!(
  id: 501,
  name: 'Oshawott',
  classification: 'Sea Otter',
  height: 0.5,
  weight: 5.9,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 87.5,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 55,
  attack: 55,
  defense: 45,
  sp_attack: 63,
  sp_defense: 45,
  speed: 45,
  type_1: Type.find_by(name: 'Water'),
  ability_1: Ability.find_by(name: 'torrent'),
  hidden_ability: Ability.find_by(name: 'shell_armor')
)

Pokemon.create!(
  id: 502,
  name: 'Dewott',
  classification: 'Discipline',
  height: 0.8,
  weight: 24.5,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 87.5,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 75,
  attack: 75,
  defense: 60,
  sp_attack: 83,
  sp_defense: 60,
  speed: 60,
  type_1: Type.find_by(name: 'Water'),
  ability_1: Ability.find_by(name: 'torrent'),
  hidden_ability: Ability.find_by(name: 'shell_armor')
)

Pokemon.create!(
  id: 503,
  name: 'Samurott',
  classification: 'Formidable',
  height: 1.5,
  weight: 94.6,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 87.5,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 95,
  attack: 100,
  defense: 85,
  sp_attack: 108,
  sp_defense: 70,
  speed: 70,
  type_1: Type.find_by(name: 'Water'),
  ability_1: Ability.find_by(name: 'torrent'),
  hidden_ability: Ability.find_by(name: 'shell_armor')
)

Pokemon.create!(
  id: 504,
  name: 'Patrat',
  classification: 'Scout',
  height: 0.5,
  weight: 11.6,
  capture_rate: 255,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 45,
  attack: 55,
  defense: 39,
  sp_attack: 35,
  sp_defense: 39,
  speed: 42,
  type_1: Type.find_by(name: 'Normal'),
  ability_1: Ability.find_by(name: 'run_away'),
  ability_2: Ability.find_by(name: 'keen_eye'),
  hidden_ability: Ability.find_by(name: 'analytic')
)

Pokemon.create!(
  id: 505,
  name: 'Watchog',
  classification: 'Lookout',
  height: 1.1,
  weight: 27.0,
  capture_rate: 255,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 60,
  attack: 85,
  defense: 69,
  sp_attack: 60,
  sp_defense: 69,
  speed: 77,
  type_1: Type.find_by(name: 'Normal'),
  ability_1: Ability.find_by(name: 'illuminate'),
  ability_2: Ability.find_by(name: 'keen_eye'),
  hidden_ability: Ability.find_by(name: 'analytic')
)

Pokemon.create!(
  id: 506,
  name: 'Lillipup',
  classification: 'Puppy',
  height: 0.4,
  weight: 4.1,
  capture_rate: 255,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 45,
  attack: 60,
  defense: 45,
  sp_attack: 25,
  sp_defense: 45,
  speed: 55,
  type_1: Type.find_by(name: 'Normal'),
  ability_1: Ability.find_by(name: 'vital_spirit'),
  ability_2: Ability.find_by(name: 'pickup'),
  hidden_ability: Ability.find_by(name: 'run_away')
)

Pokemon.create!(
  id: 507,
  name: 'Herdier',
  classification: 'Loyal Dog',
  height: 0.9,
  weight: 14.7,
  capture_rate: 120,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 65,
  attack: 80,
  defense: 65,
  sp_attack: 35,
  sp_defense: 65,
  speed: 60,
  type_1: Type.find_by(name: 'Normal'),
  ability_1: Ability.find_by(name: 'intimidate'),
  ability_2: Ability.find_by(name: 'sand_rush'),
  hidden_ability: Ability.find_by(name: 'scrappy')
)

Pokemon.create!(
  id: 508,
  name: 'Stoutland',
  classification: 'Big-Hearted',
  height: 1.2,
  weight: 61.0,
  capture_rate: 45,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 85,
  attack: 110,
  defense: 90,
  sp_attack: 45,
  sp_defense: 90,
  speed: 80,
  type_1: Type.find_by(name: 'Normal'),
  ability_1: Ability.find_by(name: 'intimidate'),
  ability_2: Ability.find_by(name: 'sand_rush'),
  hidden_ability: Ability.find_by(name: 'scrappy')
)

Pokemon.create!(
  id: 509,
  name: 'Purrloin',
  classification: 'Devious',
  height: 0.4,
  weight: 10.1,
  capture_rate: 255,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 41,
  attack: 50,
  defense: 37,
  sp_attack: 50,
  sp_defense: 37,
  speed: 66,
  type_1: Type.find_by(name: 'Dark'),
  ability_1: Ability.find_by(name: 'limber'),
  ability_2: Ability.find_by(name: 'unburden'),
  hidden_ability: Ability.find_by(name: 'prankster')
)

Pokemon.create!(
  id: 510,
  name: 'Liepard',
  classification: 'Cruel',
  height: 1.1,
  weight: 37.5,
  capture_rate: 90,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 64,
  attack: 88,
  defense: 50,
  sp_attack: 88,
  sp_defense: 50,
  speed: 106,
  type_1: Type.find_by(name: 'Dark'),
  ability_1: Ability.find_by(name: 'limber'),
  ability_2: Ability.find_by(name: 'unburden'),
  hidden_ability: Ability.find_by(name: 'prankster')
)

Pokemon.create!(
  id: 511,
  name: 'Pansage',
  classification: 'Grass Monkey',
  height: 0.6,
  weight: 10.5,
  capture_rate: 190,
  base_egg_steps: 5120,
  male_gender_ratio: 87.5,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 50,
  attack: 53,
  defense: 48,
  sp_attack: 53,
  sp_defense: 48,
  speed: 64,
  type_1: Type.find_by(name: 'Grass'),
  ability_1: Ability.find_by(name: 'gluttony'),
  hidden_ability: Ability.find_by(name: 'overgrow')
)

Pokemon.create!(
  id: 512,
  name: 'Simisage',
  classification: 'Thorn Monkey',
  height: 1.1,
  weight: 30.5,
  capture_rate: 75,
  base_egg_steps: 5120,
  male_gender_ratio: 87.5,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 75,
  attack: 98,
  defense: 63,
  sp_attack: 98,
  sp_defense: 63,
  speed: 101,
  type_1: Type.find_by(name: 'Grass'),
  ability_1: Ability.find_by(name: 'gluttony'),
  hidden_ability: Ability.find_by(name: 'overgrow')
)

Pokemon.create!(
  id: 513,
  name: 'Pansear',
  classification: 'High Temp',
  height: 0.6,
  weight: 11.0,
  capture_rate: 190,
  base_egg_steps: 5120,
  male_gender_ratio: 87.5,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 50,
  attack: 53,
  defense: 48,
  sp_attack: 53,
  sp_defense: 48,
  speed: 64,
  type_1: Type.find_by(name: 'Fire'),
  ability_1: Ability.find_by(name: 'gluttony'),
  hidden_ability: Ability.find_by(name: 'blaze')
)

Pokemon.create!(
  id: 514,
  name: 'Simisear',
  classification: 'Ember',
  height: 1.0,
  weight: 28.0,
  capture_rate: 75,
  base_egg_steps: 5120,
  male_gender_ratio: 87.5,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 75,
  attack: 98,
  defense: 63,
  sp_attack: 98,
  sp_defense: 63,
  speed: 101,
  type_1: Type.find_by(name: 'Fire'),
  ability_1: Ability.find_by(name: 'gluttony'),
  hidden_ability: Ability.find_by(name: 'blaze')
)

Pokemon.create!(
  id: 515,
  name: 'Panpour',
  classification: 'Spray',
  height: 0.6,
  weight: 13.5,
  capture_rate: 190,
  base_egg_steps: 5120,
  male_gender_ratio: 87.5,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 50,
  attack: 53,
  defense: 48,
  sp_attack: 53,
  sp_defense: 48,
  speed: 64,
  type_1: Type.find_by(name: 'Water'),
  ability_1: Ability.find_by(name: 'gluttony'),
  hidden_ability: Ability.find_by(name: 'torrent')
)

Pokemon.create!(
  id: 516,
  name: 'Simipour',
  classification: 'Geyser',
  height: 1.0,
  weight: 29.0,
  capture_rate: 75,
  base_egg_steps: 5120,
  male_gender_ratio: 87.5,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 75,
  attack: 98,
  defense: 63,
  sp_attack: 98,
  sp_defense: 63,
  speed: 101,
  type_1: Type.find_by(name: 'Water'),
  ability_1: Ability.find_by(name: 'gluttony'),
  hidden_ability: Ability.find_by(name: 'torrent')
)

Pokemon.create!(
  id: 517,
  name: 'Munna',
  classification: 'Dream Eater',
  height: 0.6,
  weight: 23.3,
  capture_rate: 190,
  base_egg_steps: 2560,
  male_gender_ratio: 50,
  experience_growth: 800_000,
  base_happiness: 70,
  hp: 76,
  attack: 25,
  defense: 45,
  sp_attack: 67,
  sp_defense: 55,
  speed: 24,
  type_1: Type.find_by(name: 'Psychic'),
  ability_1: Ability.find_by(name: 'forewarn'),
  ability_2: Ability.find_by(name: 'synchronize'),
  hidden_ability: Ability.find_by(name: 'telepathy')
)

Pokemon.create!(
  id: 518,
  name: 'Musharna',
  classification: 'Drowsing',
  height: 1.1,
  weight: 60.5,
  capture_rate: 75,
  base_egg_steps: 2560,
  male_gender_ratio: 50,
  experience_growth: 800_000,
  base_happiness: 70,
  hp: 116,
  attack: 55,
  defense: 85,
  sp_attack: 107,
  sp_defense: 95,
  speed: 29,
  type_1: Type.find_by(name: 'Psychic'),
  ability_1: Ability.find_by(name: 'forewarn'),
  ability_2: Ability.find_by(name: 'synchronize'),
  hidden_ability: Ability.find_by(name: 'telepathy')
)

Pokemon.create!(
  id: 519,
  name: 'Pidove',
  classification: 'Tiny Pigeon',
  height: 0.3,
  weight: 2.1,
  capture_rate: 255,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 50,
  attack: 55,
  defense: 50,
  sp_attack: 36,
  sp_defense: 30,
  speed: 43,
  type_1: Type.find_by(name: 'Normal'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'big_pecks'),
  ability_2: Ability.find_by(name: 'super_luck'),
  hidden_ability: Ability.find_by(name: 'rivalry')
)

Pokemon.create!(
  id: 520,
  name: 'Tranquill',
  classification: 'Wild Pigeon',
  height: 0.6,
  weight: 15.0,
  capture_rate: 120,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 62,
  attack: 77,
  defense: 62,
  sp_attack: 50,
  sp_defense: 42,
  speed: 65,
  type_1: Type.find_by(name: 'Normal'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'big_pecks'),
  ability_2: Ability.find_by(name: 'super_luck'),
  hidden_ability: Ability.find_by(name: 'rivalry')
)
