Pokemon.create!(
  id: 521,
  name: 'Unfezant',
  classification: 'Proud',
  height: 1.2,
  weight: 29.0,
  capture_rate: 45,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 80,
  attack: 115,
  defense: 80,
  sp_attack: 65,
  sp_defense: 55,
  speed: 93,
  type_1: Type.find_by(name: 'Normal'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'big_pecks'),
  ability_2: Ability.find_by(name: 'super_luck'),
  hidden_ability: Ability.find_by(name: 'rivalry')
)

Pokemon.create!(
  id: 522,
  name: 'Blitzle',
  classification: 'Electrified',
  height: 0.8,
  weight: 29.8,
  capture_rate: 190,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 45,
  attack: 60,
  defense: 32,
  sp_attack: 50,
  sp_defense: 32,
  speed: 76,
  type_1: Type.find_by(name: 'Electric'),
  ability_1: Ability.find_by(name: 'lightningrod'),
  ability_2: Ability.find_by(name: 'motor_drive'),
  hidden_ability: Ability.find_by(name: 'sap_sipper')
)

Pokemon.create!(
  id: 523,
  name: 'Zebstrika',
  classification: 'Thunderbolt',
  height: 1.6,
  weight: 79.5,
  capture_rate: 75,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 75,
  attack: 100,
  defense: 63,
  sp_attack: 80,
  sp_defense: 63,
  speed: 116,
  type_1: Type.find_by(name: 'Electric'),
  ability_1: Ability.find_by(name: 'lightningrod'),
  ability_2: Ability.find_by(name: 'motor_drive'),
  hidden_ability: Ability.find_by(name: 'sap_sipper')
)

Pokemon.create!(
  id: 524,
  name: 'Roggenrola',
  classification: 'Mantle',
  height: 0.4,
  weight: 18.0,
  capture_rate: 255,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 55,
  attack: 75,
  defense: 85,
  sp_attack: 25,
  sp_defense: 25,
  speed: 15,
  type_1: Type.find_by(name: 'Rock'),
  ability_1: Ability.find_by(name: 'sturdy'),
  ability_2: Ability.find_by(name: 'weak_armor'),
  hidden_ability: Ability.find_by(name: 'sand_force')
)

Pokemon.create!(
  id: 525,
  name: 'Boldore',
  classification: 'Ore',
  height: 0.9,
  weight: 102.0,
  capture_rate: 120,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 70,
  attack: 105,
  defense: 105,
  sp_attack: 50,
  sp_defense: 40,
  speed: 20,
  type_1: Type.find_by(name: 'Rock'),
  ability_1: Ability.find_by(name: 'sturdy'),
  ability_2: Ability.find_by(name: 'weak_armor'),
  hidden_ability: Ability.find_by(name: 'sand_force')
)

Pokemon.create!(
  id: 526,
  name: 'Gigalith',
  classification: 'Compressed',
  height: 1.7,
  weight: 260.0,
  capture_rate: 45,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 85,
  attack: 135,
  defense: 130,
  sp_attack: 60,
  sp_defense: 80,
  speed: 25,
  type_1: Type.find_by(name: 'Rock'),
  ability_1: Ability.find_by(name: 'sturdy'),
  ability_2: Ability.find_by(name: 'sand_stream'),
  hidden_ability: Ability.find_by(name: 'sand_force')
)

Pokemon.create!(
  id: 527,
  name: 'Woobat',
  classification: 'Bat',
  height: 0.4,
  weight: 2.1,
  capture_rate: 190,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 65,
  attack: 45,
  defense: 43,
  sp_attack: 55,
  sp_defense: 43,
  speed: 72,
  type_1: Type.find_by(name: 'Psychic'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'unaware'),
  ability_2: Ability.find_by(name: 'klutz'),
  hidden_ability: Ability.find_by(name: 'simple')
)

Pokemon.create!(
  id: 528,
  name: 'Swoobat',
  classification: 'Courting',
  height: 0.9,
  weight: 10.5,
  capture_rate: 45,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 67,
  attack: 57,
  defense: 55,
  sp_attack: 77,
  sp_defense: 55,
  speed: 114,
  type_1: Type.find_by(name: 'Psychic'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'unaware'),
  ability_2: Ability.find_by(name: 'klutz'),
  hidden_ability: Ability.find_by(name: 'simple')
)

Pokemon.create!(
  id: 529,
  name: 'Drilbur',
  classification: 'Mole',
  height: 0.3,
  weight: 8.5,
  capture_rate: 120,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 60,
  attack: 85,
  defense: 40,
  sp_attack: 30,
  sp_defense: 45,
  speed: 68,
  type_1: Type.find_by(name: 'Ground'),
  ability_1: Ability.find_by(name: 'sand_rush'),
  ability_2: Ability.find_by(name: 'sand_force'),
  hidden_ability: Ability.find_by(name: 'mold_breaker')
)

Pokemon.create!(
  id: 530,
  name: 'Excadrill',
  classification: 'Subterrene',
  height: 0.7,
  weight: 40.4,
  capture_rate: 60,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 110,
  attack: 135,
  defense: 60,
  sp_attack: 50,
  sp_defense: 65,
  speed: 88,
  type_1: Type.find_by(name: 'Ground'),
  type_2: Type.find_by(name: 'Steel'),
  ability_1: Ability.find_by(name: 'sand_rush'),
  ability_2: Ability.find_by(name: 'sand_force'),
  hidden_ability: Ability.find_by(name: 'mold_breaker')
)

Pokemon.create!(
  id: 531,
  name: 'Audino',
  classification: 'Hearing',
  height: 1.1,
  weight: 31.0,
  capture_rate: 255,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 800_000,
  base_happiness: 70,
  hp: 103,
  attack: 60,
  defense: 86,
  sp_attack: 60,
  sp_defense: 86,
  speed: 50,
  type_1: Type.find_by(name: 'Normal'),
  ability_1: Ability.find_by(name: 'healer'),
  ability_2: Ability.find_by(name: 'regenerator'),
  hidden_ability: Ability.find_by(name: 'klutz')
)

Pokemon.create!(
  id: 532,
  name: 'Timburr',
  classification: 'Muscular',
  height: 0.6,
  weight: 12.5,
  capture_rate: 180,
  base_egg_steps: 5120,
  male_gender_ratio: 75,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 75,
  attack: 80,
  defense: 55,
  sp_attack: 25,
  sp_defense: 35,
  speed: 35,
  type_1: Type.find_by(name: 'Fighting'),
  ability_1: Ability.find_by(name: 'guts'),
  ability_2: Ability.find_by(name: 'sheer_force'),
  hidden_ability: Ability.find_by(name: 'iron_fist')
)

Pokemon.create!(
  id: 533,
  name: 'Gurdurr',
  classification: 'Muscular',
  height: 1.2,
  weight: 40.0,
  capture_rate: 90,
  base_egg_steps: 5120,
  male_gender_ratio: 75,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 85,
  attack: 105,
  defense: 85,
  sp_attack: 40,
  sp_defense: 50,
  speed: 40,
  type_1: Type.find_by(name: 'Fighting'),
  ability_1: Ability.find_by(name: 'guts'),
  ability_2: Ability.find_by(name: 'sheer_force'),
  hidden_ability: Ability.find_by(name: 'iron_fist')
)

Pokemon.create!(
  id: 534,
  name: 'Conkeldurr',
  classification: 'Muscular',
  height: 1.4,
  weight: 87.0,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 75,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 105,
  attack: 140,
  defense: 95,
  sp_attack: 55,
  sp_defense: 65,
  speed: 45,
  type_1: Type.find_by(name: 'Fighting'),
  ability_1: Ability.find_by(name: 'guts'),
  ability_2: Ability.find_by(name: 'sheer_force'),
  hidden_ability: Ability.find_by(name: 'iron_fist')
)

Pokemon.create!(
  id: 535,
  name: 'Tympole',
  classification: 'Tadpole',
  height: 0.5,
  weight: 4.5,
  capture_rate: 255,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 50,
  attack: 50,
  defense: 40,
  sp_attack: 50,
  sp_defense: 40,
  speed: 64,
  type_1: Type.find_by(name: 'Water'),
  ability_1: Ability.find_by(name: 'swift_swim'),
  ability_2: Ability.find_by(name: 'hydration'),
  hidden_ability: Ability.find_by(name: 'water_absorb')
)

Pokemon.create!(
  id: 536,
  name: 'Palpitoad',
  classification: 'Vibration',
  height: 0.8,
  weight: 17.0,
  capture_rate: 120,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 75,
  attack: 65,
  defense: 55,
  sp_attack: 65,
  sp_defense: 55,
  speed: 69,
  type_1: Type.find_by(name: 'Water'),
  type_2: Type.find_by(name: 'Ground'),
  ability_1: Ability.find_by(name: 'swift_swim'),
  ability_2: Ability.find_by(name: 'hydration'),
  hidden_ability: Ability.find_by(name: 'water_absorb')
)

Pokemon.create!(
  id: 537,
  name: 'Seismitoad',
  classification: 'Vibration',
  height: 1.5,
  weight: 62.0,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 105,
  attack: 95,
  defense: 75,
  sp_attack: 85,
  sp_defense: 75,
  speed: 74,
  type_1: Type.find_by(name: 'Water'),
  type_2: Type.find_by(name: 'Ground'),
  ability_1: Ability.find_by(name: 'swift_swim'),
  ability_2: Ability.find_by(name: 'poison_touch'),
  hidden_ability: Ability.find_by(name: 'water_absorb')
)

Pokemon.create!(
  id: 538,
  name: 'Throh',
  classification: 'Judo',
  height: 1.3,
  weight: 55.5,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 100,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 120,
  attack: 100,
  defense: 85,
  sp_attack: 30,
  sp_defense: 85,
  speed: 45,
  type_1: Type.find_by(name: 'Fighting'),
  ability_1: Ability.find_by(name: 'guts'),
  ability_2: Ability.find_by(name: 'inner_focus'),
  hidden_ability: Ability.find_by(name: 'mold_breaker')
)

Pokemon.create!(
  id: 539,
  name: 'Sawk',
  classification: 'Karate',
  height: 1.4,
  weight: 51.0,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 100,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 75,
  attack: 125,
  defense: 75,
  sp_attack: 30,
  sp_defense: 75,
  speed: 85,
  type_1: Type.find_by(name: 'Fighting'),
  ability_1: Ability.find_by(name: 'sturdy'),
  ability_2: Ability.find_by(name: 'inner_focus'),
  hidden_ability: Ability.find_by(name: 'mold_breaker')
)

Pokemon.create!(
  id: 540,
  name: 'Sewaddle',
  classification: 'Sewing',
  height: 0.3,
  weight: 2.5,
  capture_rate: 255,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 45,
  attack: 53,
  defense: 70,
  sp_attack: 40,
  sp_defense: 60,
  speed: 42,
  type_1: Type.find_by(name: 'Bug'),
  type_2: Type.find_by(name: 'Grass'),
  ability_1: Ability.find_by(name: 'swarm'),
  ability_2: Ability.find_by(name: 'chlorophyll'),
  hidden_ability: Ability.find_by(name: 'overcoat')
)
