Pokemon.create!(
  id: 641,
  name: 'Tornadus',
  classification: 'Cyclone',
  height: 1.5,
  weight: 63.0,
  capture_rate: 3,
  base_egg_steps: 30_720,
  male_gender_ratio: 100,
  experience_growth: 1_250_000,
  base_happiness: 90,
  hp: 79,
  attack: 115,
  defense: 70,
  sp_attack: 125,
  sp_defense: 80,
  speed: 111,
  type_1: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'prankster'),
  ability_2: Ability.find_by(name: 'defiant'),
  hidden_ability: Ability.find_by(name: 'regenerator')
)

Pokemon.create!(
  id: 642,
  name: 'Thundurus',
  classification: 'Bolt Strike',
  height: 1.5,
  weight: 61.0,
  capture_rate: 3,
  base_egg_steps: 30_720,
  male_gender_ratio: 100,
  experience_growth: 1_250_000,
  base_happiness: 90,
  hp: 79,
  attack: 115,
  defense: 70,
  sp_attack: 125,
  sp_defense: 80,
  speed: 111,
  type_1: Type.find_by(name: 'Electric'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'prankster'),
  ability_2: Ability.find_by(name: 'defiant'),
  hidden_ability: Ability.find_by(name: 'volt_absorb')
)

Pokemon.create!(
  id: 643,
  name: 'Reshiram',
  classification: 'Vast White',
  height: 3.2,
  weight: 330.0,
  capture_rate: 3,
  base_egg_steps: 30_720,
  experience_growth: 1_250_000,
  base_happiness: 0,
  hp: 100,
  attack: 120,
  defense: 100,
  sp_attack: 150,
  sp_defense: 120,
  speed: 90,
  type_1: Type.find_by(name: 'Dragon'),
  type_2: Type.find_by(name: 'Fire'),
  ability_1: Ability.find_by(name: 'turboblaze')
)

Pokemon.create!(
  id: 644,
  name: 'Zekrom',
  classification: 'Deep Black',
  height: 2.9,
  weight: 345.0,
  capture_rate: 3,
  base_egg_steps: 30_720,
  experience_growth: 1_250_000,
  base_happiness: 0,
  hp: 100,
  attack: 150,
  defense: 120,
  sp_attack: 120,
  sp_defense: 100,
  speed: 90,
  type_1: Type.find_by(name: 'Dragon'),
  type_2: Type.find_by(name: 'Electric'),
  ability_1: Ability.find_by(name: 'teravolt')
)

Pokemon.create!(
  id: 645,
  name: 'Landorus',
  classification: 'Abundance',
  height: 1.5,
  weight: 68.0,
  capture_rate: 3,
  base_egg_steps: 30_720,
  male_gender_ratio: 100,
  experience_growth: 1_250_000,
  base_happiness: 90,
  hp: 89,
  attack: 125,
  defense: 90,
  sp_attack: 115,
  sp_defense: 80,
  speed: 101,
  type_1: Type.find_by(name: 'Ground'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'sand_force'),
  ability_2: Ability.find_by(name: 'sheer_force'),
  hidden_ability: Ability.find_by(name: 'intimidate')
)

Pokemon.create!(
  id: 646,
  name: 'Kyurem',
  classification: 'Boundary',
  height: 3.0,
  weight: 325.0,
  capture_rate: 3,
  base_egg_steps: 30_720,
  experience_growth: 1_250_000,
  base_happiness: 0,
  hp: 125,
  attack: 130,
  defense: 90,
  sp_attack: 130,
  sp_defense: 90,
  speed: 95,
  type_1: Type.find_by(name: 'Dragon'),
  type_2: Type.find_by(name: 'Ice'),
  ability_1: Ability.find_by(name: 'pressure'),
  ability_2: Ability.find_by(name: 'teravolt'),
  hidden_ability: Ability.find_by(name: 'turboblaze')
)

Pokemon.create!(
  id: 647,
  name: 'Keldeo',
  classification: 'Colt',
  height: 1.4,
  weight: 48.5,
  capture_rate: 3,
  base_egg_steps: 20_480,
  experience_growth: 1_250_000,
  base_happiness: 35,
  hp: 91,
  attack: 72,
  defense: 90,
  sp_attack: 129,
  sp_defense: 90,
  speed: 108,
  type_1: Type.find_by(name: 'Water'),
  type_2: Type.find_by(name: 'Fighting'),
  ability_1: Ability.find_by(name: 'justified')
)

Pokemon.create!(
  id: 648,
  name: 'Meloetta',
  classification: 'Melody',
  height: 0.6,
  weight: 6.5,
  capture_rate: 3,
  base_egg_steps: 30_720,
  experience_growth: 1_250_000,
  base_happiness: 100,
  hp: 100,
  attack: 77,
  defense: 77,
  sp_attack: 128,
  sp_defense: 128,
  speed: 90,
  type_1: Type.find_by(name: 'Normal'),
  ability_1: Ability.find_by(name: 'serene_grace')
)

Pokemon.create!(
  id: 649,
  name: 'Genesect',
  classification: 'Paleozoic',
  height: 1.5,
  weight: 82.5,
  capture_rate: 3,
  base_egg_steps: 30_720,
  experience_growth: 1_250_000,
  base_happiness: 0,
  hp: 71,
  attack: 120,
  defense: 95,
  sp_attack: 120,
  sp_defense: 95,
  speed: 99,
  type_1: Type.find_by(name: 'Bug'),
  type_2: Type.find_by(name: 'Steel'),
  ability_1: Ability.find_by(name: 'download')
)

Pokemon.create!(
  id: 650,
  name: 'Chespin',
  classification: 'Spiky Nut',
  height: 0.4,
  weight: 9.0,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 87.5,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 56,
  attack: 61,
  defense: 65,
  sp_attack: 48,
  sp_defense: 45,
  speed: 38,
  type_1: Type.find_by(name: 'Grass'),
  ability_1: Ability.find_by(name: 'overgrow'),
  hidden_ability: Ability.find_by(name: 'bulletproof')
)

Pokemon.create!(
  id: 651,
  name: 'Quilladin',
  classification: 'Spiny Armor',
  height: 0.7,
  weight: 29.0,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 87.5,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 61,
  attack: 78,
  defense: 95,
  sp_attack: 56,
  sp_defense: 58,
  speed: 57,
  type_1: Type.find_by(name: 'Grass'),
  ability_1: Ability.find_by(name: 'overgrow'),
  hidden_ability: Ability.find_by(name: 'bulletproof')
)

Pokemon.create!(
  id: 652,
  name: 'Chesnaught',
  classification: 'Spiny Armor',
  height: 1.6,
  weight: 90.0,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 87.5,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 88,
  attack: 107,
  defense: 122,
  sp_attack: 74,
  sp_defense: 75,
  speed: 64,
  type_1: Type.find_by(name: 'Grass'),
  type_2: Type.find_by(name: 'Fighting'),
  ability_1: Ability.find_by(name: 'overgrow'),
  hidden_ability: Ability.find_by(name: 'bulletproof')
)

Pokemon.create!(
  id: 653,
  name: 'Fennekin',
  classification: 'Fox',
  height: 0.4,
  weight: 9.4,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 87.5,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 40,
  attack: 45,
  defense: 40,
  sp_attack: 62,
  sp_defense: 60,
  speed: 60,
  type_1: Type.find_by(name: 'Fire'),
  ability_1: Ability.find_by(name: 'blaze'),
  hidden_ability: Ability.find_by(name: 'magician')
)

Pokemon.create!(
  id: 654,
  name: 'Braixen',
  classification: 'Fox',
  height: 1.0,
  weight: 14.5,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 87.5,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 59,
  attack: 59,
  defense: 58,
  sp_attack: 90,
  sp_defense: 70,
  speed: 73,
  type_1: Type.find_by(name: 'Fire'),
  ability_1: Ability.find_by(name: 'blaze'),
  hidden_ability: Ability.find_by(name: 'magician')
)

Pokemon.create!(
  id: 655,
  name: 'Delphox',
  classification: 'Fox',
  height: 1.5,
  weight: 39.0,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 87.5,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 75,
  attack: 69,
  defense: 72,
  sp_attack: 114,
  sp_defense: 100,
  speed: 104,
  type_1: Type.find_by(name: 'Fire'),
  type_2: Type.find_by(name: 'Psychic'),
  ability_1: Ability.find_by(name: 'blaze'),
  hidden_ability: Ability.find_by(name: 'magician')
)

Pokemon.create!(
  id: 656,
  name: 'Froakie',
  classification: 'Bubble Frog',
  height: 0.3,
  weight: 7.0,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 87.5,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 41,
  attack: 56,
  defense: 40,
  sp_attack: 62,
  sp_defense: 44,
  speed: 71,
  type_1: Type.find_by(name: 'Water'),
  ability_1: Ability.find_by(name: 'torrent'),
  hidden_ability: Ability.find_by(name: 'protean')
)

Pokemon.create!(
  id: 657,
  name: 'Frogadier',
  classification: 'Bubble Frog',
  height: 0.6,
  weight: 10.9,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 87.5,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 54,
  attack: 63,
  defense: 52,
  sp_attack: 83,
  sp_defense: 56,
  speed: 97,
  type_1: Type.find_by(name: 'Water'),
  ability_1: Ability.find_by(name: 'torrent'),
  hidden_ability: Ability.find_by(name: 'protean')
)

Pokemon.create!(
  id: 658,
  name: 'Greninja',
  classification: 'Ninja',
  height: 1.5,
  weight: 40.0,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 87.5,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 72,
  attack: 95,
  defense: 67,
  sp_attack: 103,
  sp_defense: 71,
  speed: 122,
  type_1: Type.find_by(name: 'Water'),
  type_2: Type.find_by(name: 'Dark'),
  ability_1: Ability.find_by(name: 'torrent'),
  ability_2: Ability.find_by(name: 'protean'),
  hidden_ability: Ability.find_by(name: 'battle_bond')
)

Pokemon.create!(
  id: 659,
  name: 'Bunnelby',
  classification: 'Digging',
  height: 0.4,
  weight: 5.0,
  capture_rate: 255,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 38,
  attack: 36,
  defense: 38,
  sp_attack: 32,
  sp_defense: 36,
  speed: 57,
  type_1: Type.find_by(name: 'Normal'),
  ability_1: Ability.find_by(name: 'pickup'),
  ability_2: Ability.find_by(name: 'cheek_pouch'),
  hidden_ability: Ability.find_by(name: 'huge_power')
)

Pokemon.create!(
  id: 660,
  name: 'Diggersby',
  classification: 'Digging',
  height: 1.0,
  weight: 42.4,
  capture_rate: 127,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 85,
  attack: 56,
  defense: 77,
  sp_attack: 50,
  sp_defense: 77,
  speed: 78,
  type_1: Type.find_by(name: 'Normal'),
  type_2: Type.find_by(name: 'Ground'),
  ability_1: Ability.find_by(name: 'pickup'),
  ability_2: Ability.find_by(name: 'cheek_pouch'),
  hidden_ability: Ability.find_by(name: 'huge_power')
)
