Pokemon.create!(
  id: 661,
  name: 'Fletchling',
  classification: 'Tiny Robin',
  height: 0.3,
  weight: 1.7,
  capture_rate: 255,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 45,
  attack: 50,
  defense: 43,
  sp_attack: 40,
  sp_defense: 38,
  speed: 62,
  type_1: Type.find_by(name: 'Normal'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'big_pecks'),
  hidden_ability: Ability.find_by(name: 'gale_wings'),
)

Pokemon.create!(
  id: 662,
  name: 'Fletchinder',
  classification: 'Ember',
  height: 0.7,
  weight: 16.0,
  capture_rate: 120,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 62,
  attack: 73,
  defense: 55,
  sp_attack: 56,
  sp_defense: 52,
  speed: 84,
  type_1: Type.find_by(name: 'Fire'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'flame_body'),
  hidden_ability: Ability.find_by(name: 'gale_wings'),
)

Pokemon.create!(
  id: 663,
  name: 'Talonflame',
  classification: 'Scorching',
  height: 1.2,
  weight: 24.5,
  capture_rate: 45,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 78,
  attack: 81,
  defense: 71,
  sp_attack: 74,
  sp_defense: 69,
  speed: 126,
  type_1: Type.find_by(name: 'Fire'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'flame_body'),
  hidden_ability: Ability.find_by(name: 'gale_wings'),
)

Pokemon.create!(
  id: 664,
  name: 'Scatterbug',
  classification: 'Scatterdust',
  height: 0.3,
  weight: 2.5,
  capture_rate: 255,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 38,
  attack: 35,
  defense: 40,
  sp_attack: 27,
  sp_defense: 25,
  speed: 35,
  type_1: Type.find_by(name: 'Bug'),
  ability_1: Ability.find_by(name: 'shield_dust'),
  ability_2: Ability.find_by(name: 'compoundeyes'),
  hidden_ability: Ability.find_by(name: 'friend_guard'),
)

Pokemon.create!(
  id: 665,
  name: 'Spewpa',
  classification: 'Scatterdust',
  height: 0.3,
  weight: 8.4,
  capture_rate: 120,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 45,
  attack: 22,
  defense: 60,
  sp_attack: 27,
  sp_defense: 30,
  speed: 29,
  type_1: Type.find_by(name: 'Bug'),
  ability_1: Ability.find_by(name: 'shed_skin'),
  hidden_ability: Ability.find_by(name: 'friend_guard'),
)

Pokemon.create!(
  id: 666,
  name: 'Vivillon',
  classification: 'Scale',
  height: 1.2,
  weight: 17.0,
  capture_rate: 45,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 80,
  attack: 52,
  defense: 50,
  sp_attack: 90,
  sp_defense: 50,
  speed: 89,
  type_1: Type.find_by(name: 'Bug'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'shield_dust'),
  ability_2: Ability.find_by(name: 'compoundeyes'),
  hidden_ability: Ability.find_by(name: 'friend_guard'),
)

Pokemon.create!(
  id: 667,
  name: 'Litleo',
  classification: 'Lion Cub',
  height: 0.6,
  weight: 13.5,
  capture_rate: 220,
  base_egg_steps: 5120,
  male_gender_ratio: 12.5,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 62,
  attack: 50,
  defense: 58,
  sp_attack: 73,
  sp_defense: 54,
  speed: 72,
  type_1: Type.find_by(name: 'Fire'),
  type_2: Type.find_by(name: 'Normal'),
  ability_1: Ability.find_by(name: 'rivalry'),
  ability_2: Ability.find_by(name: 'unnerve'),
  hidden_ability: Ability.find_by(name: 'moxie'),
)

Pokemon.create!(
  id: 668,
  name: 'Pyroar',
  classification: 'Royal',
  height: 1.5,
  weight: 81.5,
  capture_rate: 65,
  base_egg_steps: 5120,
  male_gender_ratio: 12.5,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 86,
  attack: 68,
  defense: 72,
  sp_attack: 109,
  sp_defense: 66,
  speed: 106,
  type_1: Type.find_by(name: 'Fire'),
  type_2: Type.find_by(name: 'Normal'),
  ability_1: Ability.find_by(name: 'rivalry'),
  ability_2: Ability.find_by(name: 'unnerve'),
  hidden_ability: Ability.find_by(name: 'moxie'),
)

Pokemon.create!(
  id: 669,
  name: 'Flabébé',
  classification: 'Single Bloom',
  height: 0.1,
  weight: 0.1,
  capture_rate: 225,
  base_egg_steps: 5120,
  male_gender_ratio: 0,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 44,
  attack: 38,
  defense: 39,
  sp_attack: 61,
  sp_defense: 79,
  speed: 42,
  type_1: Type.find_by(name: 'Fairy'),
  ability_1: Ability.find_by(name: 'flower_veil'),
  hidden_ability: Ability.find_by(name: 'symbiosis'),
)

Pokemon.create!(
  id: 670,
  name: 'Floette',
  classification: 'Fairy',
  height: 0.2,
  weight: 0.9,
  capture_rate: 120,
  base_egg_steps: 5120,
  male_gender_ratio: 0,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 54,
  attack: 45,
  defense: 47,
  sp_attack: 75,
  sp_defense: 98,
  speed: 52,
  type_1: Type.find_by(name: 'Fairy'),
  ability_1: Ability.find_by(name: 'flower_veil'),
  hidden_ability: Ability.find_by(name: 'symbiosis'),
)

Pokemon.create!(
  id: 671,
  name: 'Florges',
  classification: 'Garden',
  height: 1.1,
  weight: 10.0,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 0,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 78,
  attack: 65,
  defense: 68,
  sp_attack: 112,
  sp_defense: 154,
  speed: 75,
  type_1: Type.find_by(name: 'Fairy'),
  ability_1: Ability.find_by(name: 'flower_veil'),
  hidden_ability: Ability.find_by(name: 'symbiosis'),
)

Pokemon.create!(
  id: 672,
  name: 'Skiddo',
  classification: 'Mount',
  height: 0.9,
  weight: 31.0,
  capture_rate: 200,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 66,
  attack: 65,
  defense: 48,
  sp_attack: 62,
  sp_defense: 57,
  speed: 52,
  type_1: Type.find_by(name: 'Grass'),
  ability_1: Ability.find_by(name: 'sap_sipper'),
  hidden_ability: Ability.find_by(name: 'grass_pelt'),
)

Pokemon.create!(
  id: 673,
  name: 'Gogoat',
  classification: 'Mount',
  height: 1.7,
  weight: 91.0,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 123,
  attack: 100,
  defense: 62,
  sp_attack: 97,
  sp_defense: 81,
  speed: 68,
  type_1: Type.find_by(name: 'Grass'),
  ability_1: Ability.find_by(name: 'sap_sipper'),
  hidden_ability: Ability.find_by(name: 'grass_pelt'),
)

Pokemon.create!(
  id: 674,
  name: 'Pancham',
  classification: 'Playful',
  height: 0.6,
  weight: 8.0,
  capture_rate: 220,
  base_egg_steps: 6400,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 67,
  attack: 82,
  defense: 62,
  sp_attack: 46,
  sp_defense: 48,
  speed: 43,
  type_1: Type.find_by(name: 'Fighting'),
  ability_1: Ability.find_by(name: 'iron_fist'),
  ability_2: Ability.find_by(name: 'mold_breaker'),
  hidden_ability: Ability.find_by(name: 'scrappy'),
)

Pokemon.create!(
  id: 675,
  name: 'Pangoro',
  classification: 'Daunting',
  height: 2.1,
  weight: 136.0,
  capture_rate: 65,
  base_egg_steps: 6400,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 95,
  attack: 124,
  defense: 78,
  sp_attack: 69,
  sp_defense: 71,
  speed: 58,
  type_1: Type.find_by(name: 'Fighting'),
  type_2: Type.find_by(name: 'Dark'),
  ability_1: Ability.find_by(name: 'iron_fist'),
  ability_2: Ability.find_by(name: 'mold_breaker'),
  hidden_ability: Ability.find_by(name: 'scrappy'),
)

Pokemon.create!(
  id: 676,
  name: 'Furfrou',
  classification: 'Poodle',
  height: 1.2,
  weight: 28.0,
  capture_rate: 160,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 75,
  attack: 80,
  defense: 60,
  sp_attack: 65,
  sp_defense: 90,
  speed: 102,
  type_1: Type.find_by(name: 'Normal'),
  ability_1: Ability.find_by(name: 'fur_coat'),
)

Pokemon.create!(
  id: 677,
  name: 'Espurr',
  classification: 'Restraint',
  height: 0.3,
  weight: 3.5,
  capture_rate: 190,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 62,
  attack: 48,
  defense: 54,
  sp_attack: 63,
  sp_defense: 60,
  speed: 68,
  type_1: Type.find_by(name: 'Psychic'),
  ability_1: Ability.find_by(name: 'keen_eye'),
  ability_2: Ability.find_by(name: 'infiltrator'),
  hidden_ability: Ability.find_by(name: 'own_tempo'),
)

Pokemon.create!(
  id: 678,
  name: 'Meowstic',
  classification: 'Constraint',
  height: 0.6,
  weight: 8.5,
  capture_rate: 75,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 74,
  attack: 48,
  defense: 76,
  sp_attack: 83,
  sp_defense: 81,
  speed: 104,
  type_1: Type.find_by(name: 'Psychic'),
  ability_1: Ability.find_by(name: 'keen_eye'),
  ability_2: Ability.find_by(name: 'infiltrator'),
  hidden_ability: Ability.find_by(name: 'prankster_(male)'),
)

Pokemon.create!(
  id: 679,
  name: 'Honedge',
  classification: 'Sword',
  height: 0.8,
  weight: 2.0,
  capture_rate: 180,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 45,
  attack: 80,
  defense: 100,
  sp_attack: 35,
  sp_defense: 37,
  speed: 28,
  type_1: Type.find_by(name: 'Steel'),
  type_2: Type.find_by(name: 'Ghost'),
  ability_1: Ability.find_by(name: 'no_guard'),
)

Pokemon.create!(
  id: 680,
  name: 'Doublade',
  classification: 'Sword',
  height: 0.8,
  weight: 4.5,
  capture_rate: 90,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 59,
  attack: 110,
  defense: 150,
  sp_attack: 45,
  sp_defense: 49,
  speed: 35,
  type_1: Type.find_by(name: 'Steel'),
  type_2: Type.find_by(name: 'Ghost'),
  ability_1: Ability.find_by(name: 'no_guard'),
)
