Pokemon.create!(
  id: 721,
  name: 'Volcanion',
  classification: 'Steam',
  height: 1.7,
  weight: 195.0,
  capture_rate: 3,
  base_egg_steps: 30_720,
  experience_growth: 1_250_000,
  base_happiness: 100,
  hp: 80,
  attack: 110,
  defense: 120,
  sp_attack: 130,
  sp_defense: 90,
  speed: 70,
  type_1: Type.find_by(name: 'Fire'),
  type_2: Type.find_by(name: 'Water'),
  ability_1: Ability.find_by(name: 'water_absorb')
)

Pokemon.create!(
  id: 722,
  name: 'Rowlet',
  classification: 'Grass Quill',
  height: 0.3,
  weight: 1.5,
  capture_rate: 45,
  base_egg_steps: 3840,
  male_gender_ratio: 87.5,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 68,
  attack: 55,
  defense: 55,
  sp_attack: 50,
  sp_defense: 50,
  speed: 42,
  type_1: Type.find_by(name: 'Grass'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'overgrow'),
  hidden_ability: Ability.find_by(name: 'long_reach')
)

Pokemon.create!(
  id: 723,
  name: 'Dartrix',
  classification: 'Blade Quill',
  height: 0.7,
  weight: 16.0,
  capture_rate: 45,
  base_egg_steps: 3840,
  male_gender_ratio: 87.5,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 78,
  attack: 75,
  defense: 75,
  sp_attack: 70,
  sp_defense: 70,
  speed: 52,
  type_1: Type.find_by(name: 'Grass'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'overgrow'),
  hidden_ability: Ability.find_by(name: 'long_reach')
)

Pokemon.create!(
  id: 724,
  name: 'Decidueye',
  classification: 'Arrow Quill',
  height: 1.6,
  weight: 36.6,
  capture_rate: 45,
  base_egg_steps: 3840,
  male_gender_ratio: 87.5,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 78,
  attack: 107,
  defense: 75,
  sp_attack: 100,
  sp_defense: 100,
  speed: 70,
  type_1: Type.find_by(name: 'Grass'),
  type_2: Type.find_by(name: 'Ghost'),
  ability_1: Ability.find_by(name: 'overgrow'),
  hidden_ability: Ability.find_by(name: 'long_reach')
)

Pokemon.create!(
  id: 725,
  name: 'Litten',
  classification: 'Fire Cat',
  height: 0.4,
  weight: 4.3,
  capture_rate: 45,
  base_egg_steps: 3840,
  male_gender_ratio: 87.5,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 45,
  attack: 65,
  defense: 40,
  sp_attack: 60,
  sp_defense: 40,
  speed: 70,
  type_1: Type.find_by(name: 'Fire'),
  ability_1: Ability.find_by(name: 'blaze'),
  hidden_ability: Ability.find_by(name: 'intimidate')
)

Pokemon.create!(
  id: 726,
  name: 'Torracat',
  classification: 'Fire Cat',
  height: 0.7,
  weight: 25.0,
  capture_rate: 45,
  base_egg_steps: 3840,
  male_gender_ratio: 87.5,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 65,
  attack: 85,
  defense: 50,
  sp_attack: 80,
  sp_defense: 50,
  speed: 90,
  type_1: Type.find_by(name: 'Fire'),
  ability_1: Ability.find_by(name: 'blaze'),
  hidden_ability: Ability.find_by(name: 'intimidate')
)

Pokemon.create!(
  id: 727,
  name: 'Incineroar',
  classification: 'Heel',
  height: 1.8,
  weight: 83.0,
  capture_rate: 45,
  base_egg_steps: 3840,
  male_gender_ratio: 87.5,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 95,
  attack: 115,
  defense: 90,
  sp_attack: 80,
  sp_defense: 90,
  speed: 60,
  type_1: Type.find_by(name: 'Fire'),
  type_2: Type.find_by(name: 'Dark'),
  ability_1: Ability.find_by(name: 'blaze'),
  hidden_ability: Ability.find_by(name: 'intimidate')
)

Pokemon.create!(
  id: 728,
  name: 'Popplio',
  classification: 'Sea Lion',
  height: 0.4,
  weight: 7.5,
  capture_rate: 45,
  base_egg_steps: 3840,
  male_gender_ratio: 87.5,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 50,
  attack: 54,
  defense: 54,
  sp_attack: 66,
  sp_defense: 56,
  speed: 40,
  type_1: Type.find_by(name: 'Water'),
  ability_1: Ability.find_by(name: 'torrent'),
  hidden_ability: Ability.find_by(name: 'liquid_voice')
)

Pokemon.create!(
  id: 729,
  name: 'Brionne',
  classification: 'Pop Star',
  height: 0.6,
  weight: 17.5,
  capture_rate: 45,
  base_egg_steps: 3840,
  male_gender_ratio: 87.5,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 60,
  attack: 69,
  defense: 69,
  sp_attack: 91,
  sp_defense: 81,
  speed: 50,
  type_1: Type.find_by(name: 'Water'),
  ability_1: Ability.find_by(name: 'torrent'),
  hidden_ability: Ability.find_by(name: 'liquid_voice')
)

Pokemon.create!(
  id: 730,
  name: 'Primarina',
  classification: 'Soloist',
  height: 1.8,
  weight: 44.0,
  capture_rate: 45,
  base_egg_steps: 3840,
  male_gender_ratio: 87.5,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 80,
  attack: 74,
  defense: 74,
  sp_attack: 126,
  sp_defense: 116,
  speed: 60,
  type_1: Type.find_by(name: 'Water'),
  type_2: Type.find_by(name: 'Fairy'),
  ability_1: Ability.find_by(name: 'torrent'),
  hidden_ability: Ability.find_by(name: 'liquid_voice')
)

Pokemon.create!(
  id: 731,
  name: 'Pikipek',
  classification: 'Woodpecker',
  height: 0.3,
  weight: 1.2,
  capture_rate: 255,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 35,
  attack: 75,
  defense: 30,
  sp_attack: 30,
  sp_defense: 30,
  speed: 65,
  type_1: Type.find_by(name: 'Normal'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'keen_eye'),
  ability_2: Ability.find_by(name: 'skill_link'),
  hidden_ability: Ability.find_by(name: 'pickup')
)

Pokemon.create!(
  id: 732,
  name: 'Trumbeak',
  classification: 'Bugle Beak',
  height: 0.6,
  weight: 14.8,
  capture_rate: 120,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 55,
  attack: 85,
  defense: 50,
  sp_attack: 40,
  sp_defense: 50,
  speed: 75,
  type_1: Type.find_by(name: 'Normal'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'keen_eye'),
  ability_2: Ability.find_by(name: 'skill_link'),
  hidden_ability: Ability.find_by(name: 'pickup')
)

Pokemon.create!(
  id: 733,
  name: 'Toucannon',
  classification: 'Cannon',
  height: 1.1,
  weight: 26.0,
  capture_rate: 45,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 80,
  attack: 120,
  defense: 75,
  sp_attack: 75,
  sp_defense: 75,
  speed: 60,
  type_1: Type.find_by(name: 'Normal'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'keen_eye'),
  ability_2: Ability.find_by(name: 'skill_link'),
  hidden_ability: Ability.find_by(name: 'sheer_force')
)

Pokemon.create!(
  id: 734,
  name: 'Yungoos',
  classification: 'Loitering',
  height: 0.4,
  weight: 6.0,
  capture_rate: 255,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 48,
  attack: 70,
  defense: 30,
  sp_attack: 30,
  sp_defense: 30,
  speed: 45,
  type_1: Type.find_by(name: 'Normal'),
  ability_1: Ability.find_by(name: 'stakeout'),
  ability_2: Ability.find_by(name: 'strong_jaw'),
  hidden_ability: Ability.find_by(name: 'adaptability')
)

Pokemon.create!(
  id: 735,
  name: 'Gumshoos',
  classification: 'Stakeout',
  height: 0.7,
  weight: 14.2,
  capture_rate: 127,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 88,
  attack: 110,
  defense: 60,
  sp_attack: 55,
  sp_defense: 60,
  speed: 45,
  type_1: Type.find_by(name: 'Normal'),
  ability_1: Ability.find_by(name: 'stakeout'),
  ability_2: Ability.find_by(name: 'strong_jaw'),
  hidden_ability: Ability.find_by(name: 'adaptability')
)

Pokemon.create!(
  id: 736,
  name: 'Grubbin',
  classification: 'Larva',
  height: 0.4,
  weight: 4.4,
  capture_rate: 255,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 47,
  attack: 62,
  defense: 45,
  sp_attack: 55,
  sp_defense: 45,
  speed: 46,
  type_1: Type.find_by(name: 'Bug'),
  ability_1: Ability.find_by(name: 'swarm')
)

Pokemon.create!(
  id: 737,
  name: 'Charjabug',
  classification: 'Battery',
  height: 0.5,
  weight: 10.5,
  capture_rate: 120,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 57,
  attack: 82,
  defense: 95,
  sp_attack: 55,
  sp_defense: 75,
  speed: 36,
  type_1: Type.find_by(name: 'Bug'),
  type_2: Type.find_by(name: 'Electric'),
  ability_1: Ability.find_by(name: 'battery')
)

Pokemon.create!(
  id: 738,
  name: 'Vikavolt',
  classification: 'Stag Beetle',
  height: 1.5,
  weight: 45.0,
  capture_rate: 45,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 77,
  attack: 70,
  defense: 90,
  sp_attack: 145,
  sp_defense: 75,
  speed: 43,
  type_1: Type.find_by(name: 'Bug'),
  type_2: Type.find_by(name: 'Electric'),
  ability_1: Ability.find_by(name: 'levitate')
)

Pokemon.create!(
  id: 739,
  name: 'Crabrawler',
  classification: 'Boxing',
  height: 0.6,
  weight: 7.0,
  capture_rate: 225,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 47,
  attack: 82,
  defense: 57,
  sp_attack: 42,
  sp_defense: 47,
  speed: 63,
  type_1: Type.find_by(name: 'Fighting'),
  ability_1: Ability.find_by(name: 'hyper_cutter'),
  ability_2: Ability.find_by(name: 'iron_fist'),
  hidden_ability: Ability.find_by(name: 'anger_point')
)

Pokemon.create!(
  id: 740,
  name: 'Crabominable',
  classification: 'Woolly Crab',
  height: 1.7,
  weight: 180.0,
  capture_rate: 60,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 97,
  attack: 132,
  defense: 77,
  sp_attack: 62,
  sp_defense: 67,
  speed: 43,
  type_1: Type.find_by(name: 'Fighting'),
  type_2: Type.find_by(name: 'Ice'),
  ability_1: Ability.find_by(name: 'hyper_cutter'),
  ability_2: Ability.find_by(name: 'iron_fist'),
  hidden_ability: Ability.find_by(name: 'anger_point')
)
