Pokemon.create!(
  id: 761,
  name: 'Bounsweet',
  classification: 'Fruit',
  height: 0.3,
  weight: 3.2,
  capture_rate: 235,
  base_egg_steps: 5120,
  male_gender_ratio: 0,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 42,
  attack: 30,
  defense: 38,
  sp_attack: 30,
  sp_defense: 38,
  speed: 32,
  type_1: Type.find_by(name: 'Grass'),
  ability_1: Ability.find_by(name: 'leaf_guard'),
  ability_2: Ability.find_by(name: 'oblivious'),
  hidden_ability: Ability.find_by(name: 'sweet_veil'),
)

Pokemon.create!(
  id: 762,
  name: 'Steenee',
  classification: 'Fruit',
  height: 0.7,
  weight: 8.2,
  capture_rate: 120,
  base_egg_steps: 5120,
  male_gender_ratio: 0,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 52,
  attack: 40,
  defense: 48,
  sp_attack: 40,
  sp_defense: 48,
  speed: 62,
  type_1: Type.find_by(name: 'Grass'),
  ability_1: Ability.find_by(name: 'leaf_guard'),
  ability_2: Ability.find_by(name: 'oblivious'),
  hidden_ability: Ability.find_by(name: 'sweet_veil'),
)

Pokemon.create!(
  id: 763,
  name: 'Tsareena',
  classification: 'Fruit',
  height: 1.2,
  weight: 21.4,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 0,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 72,
  attack: 120,
  defense: 98,
  sp_attack: 50,
  sp_defense: 98,
  speed: 72,
  type_1: Type.find_by(name: 'Grass'),
  ability_1: Ability.find_by(name: 'leaf_guard'),
  ability_2: Ability.find_by(name: 'queenly_majesty'),
  hidden_ability: Ability.find_by(name: 'sweet_veil'),
)

Pokemon.create!(
  id: 764,
  name: 'Comfey',
  classification: 'Posy Picker',
  height: 0.1,
  weight: 0.3,
  capture_rate: 60,
  base_egg_steps: 5120,
  male_gender_ratio: 25,
  experience_growth: 800_000,
  base_happiness: 70,
  hp: 51,
  attack: 52,
  defense: 90,
  sp_attack: 82,
  sp_defense: 110,
  speed: 100,
  type_1: Type.find_by(name: 'Fairy'),
  ability_1: Ability.find_by(name: 'flower_veil'),
  ability_2: Ability.find_by(name: 'triage'),
  hidden_ability: Ability.find_by(name: 'natural_cure'),
)

Pokemon.create!(
  id: 765,
  name: 'Oranguru',
  classification: 'Sage',
  height: 1.5,
  weight: 76.0,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_250_000,
  base_happiness: 70,
  hp: 90,
  attack: 60,
  defense: 80,
  sp_attack: 90,
  sp_defense: 110,
  speed: 60,
  type_1: Type.find_by(name: 'Normal'),
  type_2: Type.find_by(name: 'Psychic'),
  ability_1: Ability.find_by(name: 'inner_focus'),
  ability_2: Ability.find_by(name: 'telepathy'),
  hidden_ability: Ability.find_by(name: 'symbiosis'),
)

Pokemon.create!(
  id: 766,
  name: 'Passimian',
  classification: 'Teamwork',
  height: 2.0,
  weight: 82.8,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_250_000,
  base_happiness: 70,
  hp: 100,
  attack: 120,
  defense: 90,
  sp_attack: 40,
  sp_defense: 60,
  speed: 80,
  type_1: Type.find_by(name: 'Fighting'),
  ability_1: Ability.find_by(name: 'receiver'),
  hidden_ability: Ability.find_by(name: 'defiant'),
)

Pokemon.create!(
  id: 767,
  name: 'Wimpod',
  classification: 'Turn Tail',
  height: 0.5,
  weight: 12.0,
  capture_rate: 90,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 25,
  attack: 35,
  defense: 40,
  sp_attack: 20,
  sp_defense: 30,
  speed: 80,
  type_1: Type.find_by(name: 'Bug'),
  type_2: Type.find_by(name: 'Water'),
  ability_1: Ability.find_by(name: 'wimp_out'),
)

Pokemon.create!(
  id: 768,
  name: 'Golisopod',
  classification: 'Hard Scale',
  height: 2.0,
  weight: 108.0,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 75,
  attack: 125,
  defense: 140,
  sp_attack: 60,
  sp_defense: 90,
  speed: 40,
  type_1: Type.find_by(name: 'Bug'),
  type_2: Type.find_by(name: 'Water'),
  ability_1: Ability.find_by(name: 'emergency_exit'),
)

Pokemon.create!(
  id: 769,
  name: 'Sandygast',
  classification: 'Sand Heap',
  height: 0.5,
  weight: 70.0,
  capture_rate: 140,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 55,
  attack: 55,
  defense: 80,
  sp_attack: 70,
  sp_defense: 45,
  speed: 15,
  type_1: Type.find_by(name: 'Ghost'),
  type_2: Type.find_by(name: 'Ground'),
  ability_1: Ability.find_by(name: 'water_compaction'),
  hidden_ability: Ability.find_by(name: 'sand_veil'),
)

Pokemon.create!(
  id: 770,
  name: 'Palossand',
  classification: 'Sand Castle',
  height: 1.3,
  weight: 250.0,
  capture_rate: 60,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 85,
  attack: 75,
  defense: 110,
  sp_attack: 100,
  sp_defense: 75,
  speed: 35,
  type_1: Type.find_by(name: 'Ghost'),
  type_2: Type.find_by(name: 'Ground'),
  ability_1: Ability.find_by(name: 'water_compaction'),
  hidden_ability: Ability.find_by(name: 'sand_veil'),
)

Pokemon.create!(
  id: 771,
  name: 'Pyukumuku',
  classification: 'Sea Cucumber',
  height: 0.3,
  weight: 1.2,
  capture_rate: 60,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 800_000,
  base_happiness: 70,
  hp: 55,
  attack: 60,
  defense: 130,
  sp_attack: 30,
  sp_defense: 130,
  speed: 5,
  type_1: Type.find_by(name: 'Water'),
  ability_1: Ability.find_by(name: 'innards_out'),
  hidden_ability: Ability.find_by(name: 'unaware'),
)

Pokemon.create!(
  id: 772,
  name: 'Type: Null',
  classification: 'Synthetic',
  height: 1.9,
  weight: 120.5,
  capture_rate: 3,
  base_egg_steps: 30720,
  experience_growth: 1_250_000,
  base_happiness: 0,
  hp: 95,
  attack: 95,
  defense: 95,
  sp_attack: 95,
  sp_defense: 95,
  speed: 59,
  type_1: Type.find_by(name: 'Normal'),
  ability_1: Ability.find_by(name: 'battle_armor'),
)

Pokemon.create!(
  id: 773,
  name: 'Silvally',
  classification: 'Synthetic',
  height: 2.3,
  weight: 100.5,
  capture_rate: 3,
  base_egg_steps: 30720,
  experience_growth: 1_250_000,
  base_happiness: 0,
  hp: 95,
  attack: 95,
  defense: 95,
  sp_attack: 95,
  sp_defense: 95,
  speed: 95,
  type_1: Type.find_by(name: 'Normal'),
  ability_1: Ability.find_by(name: 'rks_system'),
)

Pokemon.create!(
  id: 774,
  name: 'Minior',
  classification: 'Meteor',
  height: 0.3,
  weight: 40.0,
  capture_rate: 30,
  base_egg_steps: 6400,
  experience_growth: 1_059_860,
  base_happiness: 70,
  hp: 60,
  attack: 60,
  defense: 100,
  sp_attack: 60,
  sp_defense: 100,
  speed: 60,
  type_1: Type.find_by(name: 'Rock'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'shields_down'),
)

Pokemon.create!(
  id: 775,
  name: 'Komala',
  classification: 'Drowsing',
  height: 0.4,
  weight: 19.9,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_250_000,
  base_happiness: 70,
  hp: 65,
  attack: 115,
  defense: 65,
  sp_attack: 75,
  sp_defense: 95,
  speed: 65,
  type_1: Type.find_by(name: 'Normal'),
  ability_1: Ability.find_by(name: 'comatose'),
  ability_2: Ability.find_by(name: 'snore'),
  hidden_ability: Ability.find_by(name: 'sleep_talk'),
)

Pokemon.create!(
  id: 776,
  name: 'Turtonator',
  classification: 'Blast Turtle',
  height: 2.0,
  weight: 212.0,
  capture_rate: 70,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 60,
  attack: 78,
  defense: 135,
  sp_attack: 91,
  sp_defense: 85,
  speed: 36,
  type_1: Type.find_by(name: 'Fire'),
  type_2: Type.find_by(name: 'Dragon'),
  ability_1: Ability.find_by(name: 'shell_armor'),
)

Pokemon.create!(
  id: 777,
  name: 'Togedemaru',
  classification: 'Roly-Poly',
  height: 0.3,
  weight: 3.3,
  capture_rate: 180,
  base_egg_steps: 2560,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 65,
  attack: 98,
  defense: 63,
  sp_attack: 40,
  sp_defense: 73,
  speed: 96,
  type_1: Type.find_by(name: 'Electric'),
  type_2: Type.find_by(name: 'Steel'),
  ability_1: Ability.find_by(name: 'iron_barbs'),
  ability_2: Ability.find_by(name: 'lightningrod'),
  hidden_ability: Ability.find_by(name: 'sturdy'),
)

Pokemon.create!(
  id: 778,
  name: 'Mimikyu',
  classification: 'Disguise',
  height: 0.2,
  weight: 0.7,
  capture_rate: 45,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 55,
  attack: 90,
  defense: 80,
  sp_attack: 50,
  sp_defense: 105,
  speed: 96,
  type_1: Type.find_by(name: 'Ghost'),
  type_2: Type.find_by(name: 'Fairy'),
  ability_1: Ability.find_by(name: 'disguise'),
)

Pokemon.create!(
  id: 779,
  name: 'Bruxish',
  classification: 'Gnash Teeth',
  height: 0.9,
  weight: 19.0,
  capture_rate: 80,
  base_egg_steps: 3840,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 68,
  attack: 105,
  defense: 70,
  sp_attack: 70,
  sp_defense: 70,
  speed: 92,
  type_1: Type.find_by(name: 'Water'),
  type_2: Type.find_by(name: 'Psychic'),
  ability_1: Ability.find_by(name: 'dazzling'),
  ability_2: Ability.find_by(name: 'strong_jaw'),
  hidden_ability: Ability.find_by(name: 'wonder_skin_'),
)

Pokemon.create!(
  id: 780,
  name: 'Drampa',
  classification: 'Placid',
  height: 3.0,
  weight: 185.0,
  capture_rate: 70,
  base_egg_steps: 5120,
  male_gender_ratio: 50,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 78,
  attack: 60,
  defense: 85,
  sp_attack: 135,
  sp_defense: 91,
  speed: 36,
  type_1: Type.find_by(name: 'Normal'),
  type_2: Type.find_by(name: 'Dragon'),
  ability_1: Ability.find_by(name: 'berserk'),
  ability_2: Ability.find_by(name: 'sap_sipper'),
  hidden_ability: Ability.find_by(name: 'cloud_nine'),
)
