Pokemon.create!(
  id: 781,
  name: 'Dhelmise',
  classification: 'Sea Creeper',
  height: 3.9,
  weight: 210.0,
  capture_rate: 25,
  base_egg_steps: 6400,
  experience_growth: 1_000_000,
  base_happiness: 70,
  hp: 70,
  attack: 131,
  defense: 100,
  sp_attack: 86,
  sp_defense: 90,
  speed: 40,
  type_1: Type.find_by(name: 'Ghost'),
  type_2: Type.find_by(name: 'Grass'),
  ability_1: Ability.find_by(name: 'steelworker')
)

Pokemon.create!(
  id: 782,
  name: 'Jangmo-o',
  classification: 'Scaly',
  height: 0.6,
  weight: 29.7,
  capture_rate: 45,
  base_egg_steps: 10_240,
  male_gender_ratio: 50,
  experience_growth: 1_250_000,
  base_happiness: 70,
  hp: 45,
  attack: 55,
  defense: 65,
  sp_attack: 45,
  sp_defense: 45,
  speed: 45,
  type_1: Type.find_by(name: 'Dragon'),
  ability_1: Ability.find_by(name: 'bulletproof'),
  ability_2: Ability.find_by(name: 'soundproof'),
  hidden_ability: Ability.find_by(name: 'overcoat')
)

Pokemon.create!(
  id: 783,
  name: 'Hakamo-o',
  classification: 'Scaly',
  height: 1.2,
  weight: 47.0,
  capture_rate: 45,
  base_egg_steps: 10_240,
  male_gender_ratio: 50,
  experience_growth: 1_250_000,
  base_happiness: 70,
  hp: 55,
  attack: 75,
  defense: 90,
  sp_attack: 65,
  sp_defense: 70,
  speed: 65,
  type_1: Type.find_by(name: 'Dragon'),
  type_2: Type.find_by(name: 'Fighting'),
  ability_1: Ability.find_by(name: 'bulletproof'),
  ability_2: Ability.find_by(name: 'soundproof'),
  hidden_ability: Ability.find_by(name: 'overcoat')
)

Pokemon.create!(
  id: 784,
  name: 'Kommo-o',
  classification: 'Scaly',
  height: 1.6,
  weight: 78.2,
  capture_rate: 45,
  base_egg_steps: 10_240,
  male_gender_ratio: 50,
  experience_growth: 1_250_000,
  base_happiness: 70,
  hp: 75,
  attack: 110,
  defense: 125,
  sp_attack: 100,
  sp_defense: 105,
  speed: 85,
  type_1: Type.find_by(name: 'Dragon'),
  type_2: Type.find_by(name: 'Fighting'),
  ability_1: Ability.find_by(name: 'bulletproof'),
  ability_2: Ability.find_by(name: 'soundproof'),
  hidden_ability: Ability.find_by(name: 'overcoat')
)

Pokemon.create!(
  id: 785,
  name: 'Tapu Koko',
  classification: 'Land Spirit',
  height: 1.8,
  weight: 20.5,
  capture_rate: 3,
  base_egg_steps: 3840,
  experience_growth: 1_250_000,
  base_happiness: 70,
  hp: 70,
  attack: 115,
  defense: 85,
  sp_attack: 95,
  sp_defense: 75,
  speed: 130,
  type_1: Type.find_by(name: 'Electric'),
  type_2: Type.find_by(name: 'Fairy'),
  ability_1: Ability.find_by(name: 'electric_surge'),
  hidden_ability: Ability.find_by(name: 'telepathy')
)

Pokemon.create!(
  id: 786,
  name: 'Tapu Lele',
  classification: 'Land Spirit',
  height: 1.2,
  weight: 18.6,
  capture_rate: 3,
  base_egg_steps: 3840,
  experience_growth: 1_250_000,
  base_happiness: 70,
  hp: 70,
  attack: 85,
  defense: 75,
  sp_attack: 130,
  sp_defense: 115,
  speed: 95,
  type_1: Type.find_by(name: 'Psychic'),
  type_2: Type.find_by(name: 'Fairy'),
  ability_1: Ability.find_by(name: 'psychic_surge'),
  hidden_ability: Ability.find_by(name: 'telepathy')
)

Pokemon.create!(
  id: 787,
  name: 'Tapu Bulu',
  classification: 'Land Spirit',
  height: 1.9,
  weight: 45.5,
  capture_rate: 3,
  base_egg_steps: 3840,
  experience_growth: 1_250_000,
  base_happiness: 70,
  hp: 70,
  attack: 130,
  defense: 115,
  sp_attack: 85,
  sp_defense: 95,
  speed: 75,
  type_1: Type.find_by(name: 'Grass'),
  type_2: Type.find_by(name: 'Fairy'),
  ability_1: Ability.find_by(name: 'grassy_surge'),
  hidden_ability: Ability.find_by(name: 'telepathy')
)

Pokemon.create!(
  id: 788,
  name: 'Tapu Fini',
  classification: 'Land Spirit',
  height: 1.3,
  weight: 21.2,
  capture_rate: 3,
  base_egg_steps: 3840,
  experience_growth: 1_250_000,
  base_happiness: 70,
  hp: 70,
  attack: 75,
  defense: 115,
  sp_attack: 95,
  sp_defense: 130,
  speed: 85,
  type_1: Type.find_by(name: 'Water'),
  type_2: Type.find_by(name: 'Fairy'),
  ability_1: Ability.find_by(name: 'misty_surge'),
  hidden_ability: Ability.find_by(name: 'telepathy')
)

Pokemon.create!(
  id: 789,
  name: 'Cosmog',
  classification: 'Nebula',
  height: 0.2,
  weight: 0.1,
  capture_rate: 45,
  base_egg_steps: 30_720,
  experience_growth: 1_250_000,
  base_happiness: 0,
  hp: 43,
  attack: 29,
  defense: 31,
  sp_attack: 29,
  sp_defense: 31,
  speed: 37,
  type_1: Type.find_by(name: 'Psychic'),
  ability_1: Ability.find_by(name: 'unaware')
)

Pokemon.create!(
  id: 790,
  name: 'Cosmoem',
  classification: 'Protostar',
  height: 0.1,
  weight: 999.9,
  capture_rate: 45,
  base_egg_steps: 30_720,
  experience_growth: 1_250_000,
  base_happiness: 0,
  hp: 43,
  attack: 29,
  defense: 131,
  sp_attack: 29,
  sp_defense: 131,
  speed: 37,
  type_1: Type.find_by(name: 'Psychic'),
  ability_1: Ability.find_by(name: 'sturdy')
)

Pokemon.create!(
  id: 791,
  name: 'Solgaleo',
  classification: 'Sunne',
  height: 3.4,
  weight: 230.0,
  capture_rate: 45,
  base_egg_steps: 30_720,
  experience_growth: 1_250_000,
  base_happiness: 0,
  hp: 137,
  attack: 137,
  defense: 107,
  sp_attack: 113,
  sp_defense: 89,
  speed: 97,
  type_1: Type.find_by(name: 'Psychic'),
  type_2: Type.find_by(name: 'Steel'),
  ability_1: Ability.find_by(name: 'full_metal_body')
)

Pokemon.create!(
  id: 792,
  name: 'Lunala',
  classification: 'Moone',
  height: 4.0,
  weight: 120.0,
  capture_rate: 45,
  base_egg_steps: 30_720,
  experience_growth: 1_250_000,
  base_happiness: 0,
  hp: 137,
  attack: 113,
  defense: 89,
  sp_attack: 137,
  sp_defense: 107,
  speed: 97,
  type_1: Type.find_by(name: 'Psychic'),
  type_2: Type.find_by(name: 'Ghost'),
  ability_1: Ability.find_by(name: 'shadow_shield')
)

Pokemon.create!(
  id: 793,
  name: 'Nihilego',
  classification: 'Parasite',
  height: 1.2,
  weight: 55.5,
  capture_rate: 45,
  base_egg_steps: 30_720,
  experience_growth: 1_250_000,
  base_happiness: 0,
  hp: 109,
  attack: 53,
  defense: 47,
  sp_attack: 127,
  sp_defense: 131,
  speed: 103,
  type_1: Type.find_by(name: 'Rock'),
  type_2: Type.find_by(name: 'Poison'),
  ability_1: Ability.find_by(name: 'beast_boost')
)

Pokemon.create!(
  id: 794,
  name: 'Buzzwole',
  classification: 'Swollen',
  height: 2.4,
  weight: 333.6,
  capture_rate: 25,
  base_egg_steps: 30_720,
  experience_growth: 1_250_000,
  base_happiness: 0,
  hp: 107,
  attack: 139,
  defense: 139,
  sp_attack: 53,
  sp_defense: 53,
  speed: 79,
  type_1: Type.find_by(name: 'Bug'),
  type_2: Type.find_by(name: 'Fighting'),
  ability_1: Ability.find_by(name: 'beast_boost')
)

Pokemon.create!(
  id: 795,
  name: 'Pheromosa',
  classification: 'Lissome',
  height: 1.8,
  weight: 25.0,
  capture_rate: 255,
  base_egg_steps: 30_720,
  experience_growth: 1_250_000,
  base_happiness: 0,
  hp: 71,
  attack: 137,
  defense: 37,
  sp_attack: 137,
  sp_defense: 37,
  speed: 151,
  type_1: Type.find_by(name: 'Bug'),
  type_2: Type.find_by(name: 'Fighting'),
  ability_1: Ability.find_by(name: 'beast_boost')
)

Pokemon.create!(
  id: 796,
  name: 'Xurkitree',
  classification: 'Glowing',
  height: 3.8,
  weight: 100.0,
  capture_rate: 30,
  base_egg_steps: 30_720,
  experience_growth: 1_250_000,
  base_happiness: 0,
  hp: 83,
  attack: 89,
  defense: 71,
  sp_attack: 173,
  sp_defense: 71,
  speed: 83,
  type_1: Type.find_by(name: 'Electric'),
  ability_1: Ability.find_by(name: 'beast_boost')
)

Pokemon.create!(
  id: 797,
  name: 'Celesteela',
  classification: 'Launch',
  height: 9.2,
  weight: 999.9,
  capture_rate: 25,
  base_egg_steps: 30_720,
  experience_growth: 1_250_000,
  base_happiness: 0,
  hp: 97,
  attack: 101,
  defense: 103,
  sp_attack: 107,
  sp_defense: 101,
  speed: 61,
  type_1: Type.find_by(name: 'Steel'),
  type_2: Type.find_by(name: 'Flying'),
  ability_1: Ability.find_by(name: 'beast_boost')
)

Pokemon.create!(
  id: 798,
  name: 'Kartana',
  classification: 'Drawn Sword',
  height: 0.3,
  weight: 0.1,
  capture_rate: 255,
  base_egg_steps: 30_720,
  experience_growth: 1_250_000,
  base_happiness: 0,
  hp: 59,
  attack: 181,
  defense: 131,
  sp_attack: 59,
  sp_defense: 31,
  speed: 109,
  type_1: Type.find_by(name: 'Grass'),
  type_2: Type.find_by(name: 'Steel'),
  ability_1: Ability.find_by(name: 'beast_boost')
)

Pokemon.create!(
  id: 799,
  name: 'Guzzlord',
  classification: 'Junkivore',
  height: 5.5,
  weight: 888.0,
  capture_rate: 15,
  base_egg_steps: 30_720,
  experience_growth: 1_250_000,
  base_happiness: 0,
  hp: 223,
  attack: 101,
  defense: 53,
  sp_attack: 97,
  sp_defense: 53,
  speed: 43,
  type_1: Type.find_by(name: 'Dark'),
  type_2: Type.find_by(name: 'Dragon'),
  ability_1: Ability.find_by(name: 'beast_boost')
)

Pokemon.create!(
  id: 800,
  name: 'Necrozma',
  classification: 'Prism',
  height: 2.4,
  weight: 230.0,
  capture_rate: 3,
  base_egg_steps: 30_720,
  experience_growth: 1_250_000,
  base_happiness: 0,
  hp: 97,
  attack: 107,
  defense: 101,
  sp_attack: 127,
  sp_defense: 89,
  speed: 79,
  type_1: Type.find_by(name: 'Psychic'),
  ability_1: Ability.find_by(name: 'prism_armor')
)
