Pokemon.create!(
  id: 801,
  name: 'Magearna',
  classification: 'Artificial',
  height: 1.0,
  weight: 80.5,
  capture_rate: 3,
  base_egg_steps: 30720,
  experience_growth: 1_250_000,
  base_happiness: 0,
  hp: 80,
  attack: 95,
  defense: 115,
  sp_attack: 130,
  sp_defense: 115,
  speed: 65,
  type_1: Type.find_by(name: 'Steel'),
  type_2: Type.find_by(name: 'Fairy'),
  ability_1: Ability.find_by(name: 'soul-heart'),
)

Pokemon.create!(
  id: 802,
  name: 'Marshadow',
  classification: 'Gloomdweller',
  height: 0.7,
  weight: 22.2,
  capture_rate: 3,
  base_egg_steps: 30720,
  experience_growth: 1_250_000,
  base_happiness: 0,
  hp: 90,
  attack: 125,
  defense: 80,
  sp_attack: 90,
  sp_defense: 90,
  speed: 125,
  type_1: Type.find_by(name: 'Fighting'),
  type_2: Type.find_by(name: 'Ghost'),
  ability_1: Ability.find_by(name: 'technician'),
)
