Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods:
    - 'describe'

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'test/test_helper.rb'
    - 'bin/spring'
