Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  ExcludedMethods:
    - 'describe'

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'config.ru'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'test/test_helper.rb'
