language: ruby

rvm:
    - 2.3.0

env:
    - DB=postgresql

script:
    - RAILS_ENV=test bundle exec rake db:migrate db:seed
    - bundle exec rspec spec
    - bundle exec rubocop -R

before_script:
    - psql -c 'create database travis;' -U postgres
